-- Criterios:
-- * Usar solo comillas simples dentro de los strings
-- no eliminar
-- no eliminar

CREATE TABLE IF NOT EXISTS heroku_bf7cb810553a372.`word` (
id INT PRIMARY KEY AUTO_INCREMENT, 
word_name VARCHAR(100),
word_description VARCHAR(150),
word_root VARCHAR(25)
);

TRUNCATE TABLE heroku_bf7cb810553a372.`word`;

INSERT IGNORE INTO heroku_bf7cb810553a372.`word` (`word_name`, `word_description`, `word_root`) 
VALUES
("Äw", "Palabra originante tradicional", "Äw"),
("Fejfeg", "Palabra originante tradicional", "Fejf"),
("Fejfeges", "Lit. 'Relativo a palabra'", "Fejfeg"),
("Fejfar", "Palabra originante tradicional", "Fejf"),
("Fejflĵneg", "De 'Fejfeg' y 'Ljneg', lit. 'Línea de palabras'", "Fejf"),
("Dejtug", "Palabra originante tradicional", "Dejt"),
("Fejfegur", "Lit. 'Colectivo de palabras'", "Fejfeg"),
("Fejfegures", "Lit. 'Relativo a colectivo de palabras'", "Fejfeg"),
("Fejfuget", "Lit. 'Texto pequeño'", "Fejfug"),
("Fejfug", "Palabra originante tradicional", "Fejf"),
("Fejfaurkĵgug", "De 'Fejfug', 'Aurag' y 'Kjgug', lit. 'edificio de reunión de textos'", "Fejf"),
("Fejfaurkĵguges", "De 'Fejfug', 'Aurag' y 'Kjgug', lit. 'Relativo a edificio de reunión de textos'", "Fejfaurkĵgug"),
("Fejfkĵgug", "De 'Fejfug' y 'Kjgug', lit. 'edificio de textos'", "Fejf"),
("Fejfànördnug", "De 'Fejfar' y 'Anördnug', lit. 'Máquina para escribir'", "Fejf"),
("Rjgëlar", "Palabra originante tradicional", "Rjgël"),
("Rjgëlug", "Palabra originante tradicional", "Rjgël"),
("Rjgëlkèfjeg", "De 'Rjgëlug' y 'Kefjeg', lit. 'Persona que dibuja'", "Rjgël"),
("Lajtrĵgëlar", "De 'Lajteg' y 'Rjgëlar', lit. 'Dibujar con luz'", "Lajt"),
("Lajtrĵgëlug", "De 'Lajteg' y 'Rjgëlug', lit. 'Dibujo de luz'", "Lajt"),
("Lajtrĵgëluges", "De 'Lajteg' y 'Rjgëlug', lit. 'Relativo a dibujo de luz'", "Lajtrĵgëlug"),
("Lajtrjgëlànördnug", "De 'Lajteg', 'Rjgëlug' y 'Anördnug', lit. 'Máquina de dibujos de luz'", "Lajt"),
("Lajtrjgëlkèfjeg", "De 'Lajteg', 'Rjgëlug' y 'Kefjeg', lit. 'Persona de dibujos de luz'", "Lajt"),
("Lajtrjgëlfèjregur", "De 'Lajteg', 'Rjgëlug' y 'Fëjregur', lit. 'Colectivo de conocimientos de dibujos de luz'", "Lajt"),
("Ljngar", "Palabra originante tradicional", "Ljng"),
("Ljngeg", "Palabra originante tradicional", "Ljng"),
("Ljngeges", "Lit. 'Relativo a idioma'", "Ljngeg"),
("Blaekaj", "Palabra originante tradicional", "Blaek"),
("Blaekar", "Palabra originante tradicional", "Blaek"),
("Blaekrjgëlfùtaj", "De 'Blaekaj', 'Rjgël' y 'Futaj', lit. 'Herramienta para dibujar con tinta'", "Blaek"),
("Blaekfejfùtaj", "De 'Blaekaj', 'Fejfar' y 'Futaj', lit. 'Herramienta para escribir con tinta'", "Blaek"),
("Golunaj", "Palabra originante tradicional", "Golun"),
("Golunajes", "Lit. 'Relativo a sabor'", "Golunaj"),
("Golunar", "Palabra originante tradicional", "Golun"),
("Golunwĵkolaj", "De 'Golunar' y 'Wjkolaj', lit. 'Acción de la boca para saborear'", "Golun"),
("Süjkgòlunaj", "De 'Süjkaj' y 'Golunaj', lit. 'Sabor de azúcar'", "Süjk"),
("Süjkgòlunajes", "De 'Süjkaj' y 'Golunaj', lit. 'Relativo a sabor de azúcar'", "Süjkgòlunaj"),
("Swejaer", "Palabra originante tradicional", "Sweja"),
("Swejaeg", "Palabra originante tradicional", "Sweja"),
("Swejaeges", "Lit. 'Relativo a sexo'", "Swejaeg"),
("Swejaug", "Palabra originante tradicional", "Sweja"),
("Swejauges", "Lit. 'Relativo a sexo'", "Swejaug"),
("Wjwjtaj", "Palabra originante tradicional", "Wjwjt"),
("Wjwjtar", "Palabra originante tradicional", "Wjwjt"),
("Wjwjtgòlunaj", "De 'Wjwjtaj' y 'Gölunaj', lit. 'Sabor de sal'", "Wjwjt"),
("Wjwjtgòlunajes", "De 'Wjwjtaj' y 'Gölunaj', lit. 'Relativo a sabor de sal'", "Wjwjtgòlunaj"),
("Süjkaj", "Palabra originante tradicional", "Süjk"),
("Süjkajes", "Lit. 'Relativo a azúcar'", "Süjkaj"),
("Süjkar", "Palabra originante tradicional", "Süjk"),
("Süjkaenjàgaj", "De 'Süjkaj', 'Kaener' y 'Jagaj', lit. 'Agua enfriada con azúcar'", "Süjk"),
("Ärger", "Palabra originante tradicional", "Ärg"),
("Ärgug", "Palabra originante tradicional", "Ärg"),
("Ärguges", "Lit. 'Relativo a olor'", "Ärgug"),
("Enäjàrgug", "De 'Enäjeg' y 'Ärgug', lit. 'Olor con buena condición'", "Enäj"),
("Enäjàrguges", "De 'Enäjeg' y 'Ärgug', lit. 'Relativo a olor con buena condición'", "Enäjàrgug"),
("Färalàrgug", "De 'Färaleg' y 'Ärgug', lit. 'Olor con mala condición'", "Färal"),
("Färalàrguges", "De 'Färaleg' y 'Ärgug', lit. 'Relativo a olor con mala condición'", "Färalàrgug"),
("Üwlaed", "Palabra originante tradicional", "Üwlaed"),
("Üwlaedug", "Palabra originante tradicional", "Üwlaed"),
("Ënskj", "Palabra originante tradicional", "Ënskj"),
("Ënskjeg", "Palabra originante tradicional", "Ënskj"),
("Ënskjeges", "Lit. 'Relativo a utilización'", "Ënskjeg"),
("Tekler", "Palabra originante tradicional", "Tekl"),
("Teklug", "Palabra originante tradicional", "Tekl"),
("Söjw", "Palabra originante tradicional", "Söjw"),
("Söjwaj", "Palabra originante tradicional", "Söjw"),
("Söjwajes", "Lit. 'Relativo a diálogo'", "Söjw"),
("Söjwajaf", "Lit. 'Sin diálogo'", "Söjwaj"),
("Söjwajafer", "Lit. 'Hacer sin diálogo'", "Söjwaj"),
("Tänstar", "Palabra originante tradicional", "Tänst"),
("Tänsteg", "Palabra originante tradicional", "Tänst"),
("Tänsteges", "Lit. 'Relativo a trabajo'", "Tänsteg"),
("Tänstegaf", "Lit. 'Sin trabajo'", "Tänsteg"),
("Tänslùjkaj", "De 'Tänsteg' y 'Lujkaj', lit. 'Dinero de trabajo'", "Tänst"),
("Tänskèfjeg", "De 'Tänstar' y 'Kefjeg', lit. 'Persona que trabaja'", "Tänst"),
("Tänswenkèfjeg", "De 'Tänstar', 'Wenkeg' y 'Kefjeg', lit. 'Persona con igualdad que trabaja'", "Tänst"),
("Wjkolaj", "Palabra originante tradicional", "Wjkol"),
("Wjkolajes", "Lit. 'Relativo a boca'", "Wjkolaj"),
("Wjkolar", "Palabra originante tradicional, lit. 'Accionar la boca'", "Wjkol"),
("Bjselwĵkolaj", "De 'Bjseler' y 'Wjkolaj', lit. 'Acción de la boca para airear'", "Bjsel"),
("Jagwĵkolar", "De 'Jagar' y 'Wjkolar', lit. 'Accionar la boca para mojar'", "Jag"),
("Laekwĵkolar", "De 'Laeker' y 'Wjkolar', lit. 'Accionar la boca para comer'", "Laek"),
("Traewĵkolaj", "De 'Traewer' y 'Wjkolar', lit. 'Acción de la boca para atacar'", "Traew"),
("Traewĵkolar", "De 'Traewer' y 'Wjkolar', lit. 'Accionar la boca para atacar'", "Traew"),
("Glaewĵkolar", "De 'Glaer' y 'Wjkolar', lit. 'Accionar la boca para amar'", "Glae"),
("Glaewĵkolaj", "De 'Glaer' y 'Wjkolar', lit. 'Acción de la boca para amar'", "Glae"),
("Laejrwĵkolar", "De 'Laejreg' y 'Wjkolar', lit. 'Accionar la boca para musicalizar'", "Laejr"),
("Laejrwĵkolaj", "De 'Laejreg' y 'Wjkolaj', lit. 'Acción de la boca para musicalizar'", "Laejr"),
("Roglug", "Palabra originante tradicional", "Rogl"),
("Rogler", "Palabra originante tradicional", "Rogl"),
("Frët", "Palabra originante tradicional", "Frët"),
("Frëteg", "Palabra originante tradicional", "Frët"),
("Fälòj", "Palabra originante tradicional", "Fälòj"),
("Täkenar", "Palabra originante tradicional", "Täken"),
("Täkenaj", "Palabra originante tradicional", "Täken"),
("Täkenajes", "Lit. 'Relativo a pregunta'", "Täkenaj"),
("Wälejer", "Palabra originante tradicional", "Wälej"),
("Wälejeg", "Palabra originante tradicional", "Wälej"),
("Wälejeges", "Lit. 'Relativo a amistad'", "Wälejeg"),
("Wälejegon", "Lit. 'Amistad grande'", "Wälejeg"),
("Wälejegones", "Lit. 'Relativo a amistad grande'", "Wälejeg"),
("Wälejegaf", "Lit. 'Sin amistad'", "Wälejeg"),
("Wälejegafer", "Lit. 'Hacer sin amistad'", "Wälejeg"),
("Wälejkèfjeg", "De 'Wälejeg' y 'Kefjeg', lit. 'Persona con amistad'", "Wälej"),
("Üsker", "Palabra originante tradicional", "Üsk"),
("Üskug", "Palabra originante tradicional", "Üsk"),
("Kjn", "Palabra originante tradicional", "Kjn"),
("Knajkar", "Palabra originante tradicional", "Knajk"),
("Knajkeg", "Palabra originante tradicional", "Knajk"),
("Knajkeges", "Lit. 'Relativo a pedido'", "Knajkeg"),
("Knajkegon", "Lit. 'Pedido grande'", "Knajkeg"),
("Knajkegones", "Lit. 'Relativo a pedido grande'", "Knajkeg"),
("Knajkegonar", "Lit. 'Hacer pedido grande'", "Knajkeg"),
("Änslar", "Palabra originante tradicional", "Änsl"),
("Änslaj", "Palabra originante tradicional", "Änsl"),
("Änslajes", "Lit. 'Relativo a disculpa'", "Änslaj"),
("Änslajaf", "Lit. 'Sin disculpa'", "Änslaj"),
("Änslajafes", "Lit. 'Relativo a sin disculpa'", "Änslaj"),
("Änslajafar", "Lit. 'Hacer sin disculpa'", "Änslaj"),
("Alentar", "Palabra originante tradicional", "Alent"),
("Alentaj", "Palabra originante tradicional", "Alent"),
("Alentajes", "Lit. 'Relativo a aceptación'", "Alentaj"),
("Alentajaf", "Lit. 'Sin aceptación'", "Alentaj"),
("Alentajafes", "Lit. 'Relativo a sin aceptación'", "Alentaj"),
("Alentajafar", "Lit. 'Hacer sin aceptación'", "Alentaj"),
("Kulkar", "Palabra originante tradicional", "Kulk"),
("Kulkeg", "Palabra originante tradicional", "Kulk"),
("Kulkeges", "Lit. 'Relativo a silencio'", "Kulkeg"),
("Kulkegaf", "Lit. 'Sin silencio'", "Kulkeg"),
("Kulkegafes", "Lit. 'Relativo a sin silencio'", "Kulkeg"),
("Kulkegafar", "lit. 'Hacer sin silencio'", "Kulkeg"),
("Gërfleg", "Palabra originante tradicional", "Gërfl"),
("Gërfleges", "Lit. 'Relativo a tamaño'", "Gërfleg"),
("Gërflegon", "Lit. 'Tamaño grande'", "Gërfleg"),
("Gërflegones", "Lit. 'Relativo a tamaño grande'", "Gërfleg"),
("Gërflegoner", "Lit. 'Hacer tamaño grande'", "Gërfleg"),
("Gërfleget", "Lit. 'Tamaño pequeño'", "Gërfleg"),
("Gërflegetes", "Lit. 'Relativo a tamaño pequeño'", "Gërfleg"),
("Gërflegeter", "Lit. 'Hacer tamaño pequeño'", "Gërfleg"),
("Gërfler", "Palabra originante tradicional", "Gërfl"),
("Awendeg", "Palabra originante tradicional", "Awend"),
("Awendeges", "Lit. 'Relativo a suavidad'", "Awendeg"),
("Awendegaf", "Lit. 'Sin suavidad'", "Awendeg"),
("Awendegafes", "Lit. 'Relativo a sin suavidad'", "Awendeg"),
("Awendar", "Palabra originante tradicional", "Awend"),
("Daentaj", "Palabra originante tradicional", "Daent"),
("Daentajes", "Lit. 'Relativo a la blandura'", "Daentaj"),
("Daentajaf", "Lit. 'Sin blandura'", "Daentaj"),
("Daentajafes", "Lit. 'Relativo a sin blandura'", "Daentaj"),
("Daentajafar", "Lit. 'Hacer sin blandura'", "Daentaj"),
("Daentar", "Palabra originante tradicional", "Daent"),
("Fräjg", "Palabra originante tradicional", "Fräjg"),
("Fülw", "Palabra originante tradicional", "Fülw"),
("Fülwuj", "Palabra originante tradicional", "Fülw"),
("Fülweg", "Palabra originante tradicional", "Fülw"),
("Fülweges", "Lit. 'Relativo a parte'", "Fülweg"),
("Fülwegur", "Lit. 'Colectivo de partes'", "Fülweg"),
("Fülwegures", "Lit. 'Relativo a colectivo de partes'", "Fülweg"),
("Fülwer", "Palabra originante tradicional", "Fülw"),
("Grägaj", "Palabra originante tradicional", "Gräg"),
("Grägajes", "Lit. 'Relativo a paz'", "Grägaj"),
("Grägar", "Palabra originante tradicional", "Gräg"),
("Grägajaf", "Lit. 'Sin paz'", "Grägaj"),
("Grägajafes", "Lit. 'Relativo a sin paz'", "Grägaj"),
("Grägajafon", "Lit. 'Sin paz grande'", "Grägaj"),
("Grägajafones", "Lit. 'Relativo a sin paz grande'", "Grägaj"),
("Grägajafet", "Lit. 'Sin paz pequeña'", "Grägaj"),
("Grägajafar", "Lit. 'Hacer sin paz'", "Grägaj"),
("Grägkèfjeg", "De 'Grägaj' y 'Kefjeg', lit. 'Persona de paz'", "Gräg"),
("Grägajafkèfjeg", "De 'Grägajaf' y 'Kefjeg', lit. 'Persona de batalla'", "Gräg"),
("Tëfjaj", "Palabra originante tradicional", "Tëfj"),
("Tëfjajes", "Lit. 'Relativo a capa'", "Tëfjaj"),
("Tëfjar", "Palabra originante tradicional", "Tëfj"),
("Tëfjajet", "Lit. 'Capa pequeña'", "Tëfjaj"),
("Tëfjajon", "Lit. 'Capa grande'", "Tëfjaj"),
("Tëfjajones", "Lit. 'Relativo a capa grande'", "Tëfjaj"),
("Rjntèfjajon", "De 'Rjnlug' y 'Tëfjajon', lit. 'Capa grande de cuerpo'", "Rjntèfjaj"),
("Rjntèfjajones", "De 'Rjnlug' y 'Tëfjajon', lit. 'Relativo a capa grande de cuerpo'", "Rjntèfjaj"),
("Käjktèfjajet", "De 'Käjker' y 'Tëfjajet', lit. 'Capa pequeña para cortar'", "Käjk"),
("Traewug", "Palabra originante tradicional", "Traew"),
("Traewuges", "Lit. 'Relativo a ataque'", "Traewug"),
("Traewer", "Palabra originante tradicional", "Traew"),
("Elkjug", "Palabra originante tradicional", "Elkj"),
("Elkjuges", "Lit. 'Relativo a defensa'", "Elkjug"),
("Elkjugaf", "Lit. 'Sin protección'", "Elkjug"),
("Elkjugafer", "Lit. 'Sin protección'", "Elkjug"),
("Elkjer", "Palabra originante tradicional", "Elkj"),
("Dawegaj", "Palabra de patrimonio nacional", "Daweg"),
("Dawegeg", "Palabra originante tradicional", "Daweg"),
("Dawegeges", "Lit. 'Relativo a altura'", "Dawegeg"),
("Daweger", "Palabra originante tradicional", "Daweg"),
("Dawegegaf", "Lit. 'Sin altura'", "Dawegeg"),
("Dawegegafes", "Lit. 'Relativo a sin altura'", "Dawegeg"),
("Dawegegafar", "Lit. 'Hacer sin altura'", "Dawegeg"),
("Ljneg", "Palabra originante tradicional", "Ljn"),
("Ljneges", "Lit. 'Relativo a línea'", "Ljneg"),
("Sontar", "Palabra originante tradicional", "Sont"),
("Sonteg", "Palabra originante tradicional", "Sont"),
("Felder", "Palabra originante tradicional", "Feld"),
("Feldug", "Palabra originante tradicional", "Feld"),
("Felduges", "Lit. 'Relativo a pensamiento'", "Feldug"),
("Rëndfèldug", "De 'Rëndeg' y 'Feldug', lit. 'Pensamiento de solución'", "Rënd"),
("Rëndfèlder", "De 'Rëndeg' y 'Felder', lit. 'Pensar (una) solución'", "Rënd"),
("Ljnrĵnlug", "De 'Ljneg' y 'Rjnlug', lit. 'Cuerpo de líneas'", "Ljn"),
("Wänlĵneg", "De 'Wän' y 'Ljneg', lit. 'Una línea'", "Wän"),
("Trjlĵneg", "De 'Trj' y 'Ljneg', lit. 'Tres líneas'", "Trj"),
("Fjrlĵneg", "De 'Fjr' y 'Ljneg', lit. 'Cuatro líneas'", "Fjr"),
("Fajwlĵneg", "De 'Fajw' y 'Ljneg', lit. 'Cinco líneas'", "Fajw"),
("Sekslĵneg", "De 'Seks' y 'Ljneg', lit. 'Seis líneas'", "Seks"),
("Wjljnar", "Palabra originante tradicional", "Wjljn"),
("Wjljnaj", "Palabra originante tradicional", "Wjljn"),
("Wjljnajes", "Lit. 'Relativo a libertad'", "Wjljnaj"),
("Wjljnajaf", "Lit. 'Sin libertad'", "Wjljnaj"),
("Wjljnajafes", "Lit. 'Relativo a sin libertad'", "Wjljnaj"),
("Wjljnajafar", "Lit. 'Hacer sin libertad'", "Wjljnaj"),
("Wjljnajafkèfjeg", "De 'Wjljnajaf' y 'Kefjeg', lit. 'Persona sin libertad'", "Wjljn"),
("Gräjug", "Palabra originante tradicional", "Gräj"),
("Gräjuges", "Lit. 'Relativo a fuerza'", "Gräjug"),
("Gräjer", "Palabra originante tradicional", "Gräj"),
("Gräjugaf", "Lit. 'Sin fuerza'", "Gräjug"),
("Gräjugafes", "Lit. 'Relativo a sin fuerza'", "Gräjug"),
("Gräjugafer", "Lit. 'Hacer sin fuerza'", "Gräjug"),
("Göwelar", "Palabra originante tradicional", "Göwel"),
("Göwelaj", "Palabra originante tradicional", "Göwel"),
("Göwelsfàejug", "De 'Göwelar' y 'Sfaejug', lit. 'Capacidad de recordar'", "Göwel"),
("Göwelsfàejuges", "De 'Göwelar' y 'Sfaejug', lit. 'Relativo a capacidad de recordar'", "Göwelsfàejug"),
("Göwelsfàejugaf", "De 'Göwelar' y 'Sfaejugaf', lit. 'Sin capacidad de recordar'", "Göwelsfàejug"),
("Göwelsfàejugafes", "De 'Göwelar' y 'Sfaejugaf', lit. 'Relativo a sin capacidad de recordar'", "Göwelsfàejugaf"),
("Göwelajaf", "Lit. 'Sin recuerdo'", "Göwelaj"),
("Göwelajafar", "Lit. 'Hacer sin recuerdo'", "Göwelaj"),
("Talwug", "Palabra originante tradicional", "Talw"),
("Talwuges", "Lit. 'Relativo a nombre'", "Talwug"),
("Talwer", "Palabra originante tradicional", "Talw"),
("Frejeg", "Palabra originante tradicional", "Frej"),
("Frejeges", "Lit. 'Relativo a facilidad'", "Frejeg"),
("Frejegaf", "Lit. 'Sin facilidad'", "Frejeg"),
("Frejegafes", "Lit. 'Relativo a sin facilidad'", "Frejeg"),
("Wlaejaj", "Palabra originante tradicional", "Wlaej"),
("Wlaejar", "Palabra originante tradicional", "Wlaej"),
("Walèrja", "Palabra de patrimonio nacional", "Walèrja"),
("Walèrjaes", "Palabra de patrimonio nacional, lit. 'Relativo a Valeria'", "Walèrja"),
("Gërtaj", "Palabra de patrimonio nacional", "Gërt"),
("Gërtajes", "Palabra de patrimonio nacional, lit. 'Relativo a la Gran Duquesa'", "Gërtaj"),
("Gërteg", "Palabra de patrimonio nacional", "Gërt"),
("Gërtar", "Palabra originante tradicional", "Gërt"),
("Autonòwajl", "Palabra adoptada artificialmente del inglés 'Automobile'", "Autonòwajl"),
("Autonòwajles", "Lit. 'Relativo a automóvil'", "Autonòwajl"),
("Konpjùter", "Palabra adoptada artificialmente del inglés 'Computer'", "Konpjùter"),
("Konpjùteres", "Lit. 'Relativo a computadora'", "Konpjùter"),
("Telefön", "Palabra adoptada artificialmente del inglés 'Telephone'", "Telefön"),
("Telefönes", "Lit. 'Relativo a teléfono'", "Telefön"),
("Telefönar", "Lit. 'Hacer (uso de) teléfono'", "Telefön"),
("Kälatèlefön", "De 'Kälaeg' y 'Telefön', lit. 'Teléfono con movimiento'", "Käla"),
("Kokolàt", "Palabra adoptada artificialmente del español 'Chocolate'", "Kokolàt"),
("Jä", "Palabra originante tradicional", "Jä"),
("Tejgün", "Palabra originante tradicional", "Tejgün"),
("Jkë", "Palabra originante tradicional", "Jkë"),
("Tojsün", "Palabra originante tradicional", "Tojsün"),
("Üke", "Palabra originante tradicional", "Üke"),
("Ükon", "Palabra originante tradicional", "Üke"),
("Fjke", "Palabra originante tradicional", "Fjke"),
("Loke", "Palabra originante tradicional", "Loke"),
("Frät", "Palabra originante tradicional", "Frät"),
("Sälk", "Palabra originante tradicional", "Sälk"),
("Ësjl", "Palabra originante tradicional", "Ësjl"),
("Rädow", "Palabra originante tradicional", "Rädow"),
("Tösal", "Palabra originante tradicional", "Tösal"),
("Tösaler", "Palabra originante tradicional", "Tösal"),
("Tösaleg", "Palabra originante tradicional", "Tösal"),
("Wünsal", "Palabra originante tradicional", "Wünsal"),
("Wünsaler", "Palabra originante tradicional", "Wünsal"),
("Wünsaleg", "Palabra originante tradicional", "Wünsal"),
("Lödew", "Palabra originante tradicional", "Lödew"),
("Lödewug", "Palabra originante tradicional", "Lödew"),
("Kläsj", "Palabra originante tradicional", "Kläsj"),
("Kläsjug", "Palabra originante tradicional", "Kläsj"),
("Kläsjuges", "Lit. 'Relativo a deber'", "Kläsjug"),
("Lujklàsjug", "De 'Lujkaj' y 'Kläsjug', lit. 'Obligación de dinero'", "Lujk"),
("Laedenlujklàsjug", "De 'Ladenug', 'Lujkaj' y 'Kläsjug', lit. 'Obligación de dinero de país'", "Laeden"),
("Laedenlujklàsjuges", "De 'Ladenug', 'Lujkaj' y 'Kläsjug', lit. 'Relativo a obligación de dinero de país'", "Laedenlujklàsjug"),
("Wülasj", "Palabra originante tradicional", "Wülasj"),
("Wülasjeg", "Palabra originante tradicional", "Wülasj"),
("Wülasjeges", "Lit. 'Relativo a necesidad'", "Wülasjeg"),
("Sëjntug", "Palabra originante tradicional", "Sëjnt"),
("Sëjnteg", "Palabra originante tradicional", "Sëjnt"),
("Sëjnteges", "Lit. 'Relativo a unicidad'", "Sëjnteg"),
("Sëjnter", "Palabra originante tradicional", "Sëjnt"),
("Sëjntegaf", "Lit. 'Sin unicidad'", "Sëjnteg"),
("Sëjntegafer", "Lit. 'Hacer sin unicidad'", "Sëjnteg"),
("Ewjd", "Palabra originante tradicional", "Ewjd"),
("Ewjdeg", "Palabra originante tradicional", "Ewjd"),
("Ewlän", "Palabra originante tradicional", "Ewlän"),
("Ewläneg", "Palabra originante tradicional", "Ewlän"),
("Ewläneges", "Lit. 'Relativo a recepción'", "Ewläneg"),
("Knäler", "Palabra originante tradicional", "Knäl"),
("Knälug", "Palabra originante tradicional", "Knäl"),
("Knäluges", "Lit. 'Relativo a elección'", "Knälug"),
("Rënder", "Palabra originante tradicional", "Rënd"),
("Rëndeg", "Palabra originante tradicional", "Rënd"),
("Rëndeges", "Lit. 'Relativo a resolución'", "Rëndeg"),
("Rëndegaf", "Lit. 'Sin solución'", "Rëndeg"),
("Rëndegafes", "Lit. 'Relativo a sin solución'", "Rëndeg"),
("Güwlan", "Palabra originante tradicional", "Güwl"),
("Güwluj", "Palabra originante tradicional", "Güwl"),
("Güwler", "Palabra originante tradicional", "Güwl"),
("Güwlug", "Palabra originante tradicional", "Güwl"),
("Sënsar", "Palabra originante tradicional", "Sëns"),
("Sënseg", "Palabra originante tradicional", "Sëns"),
("Sënseges", "Lit. 'Relativo a causa'", "Sënseg"),
("Froj", "Palabra originante tradicional", "Froj"),
("Wëroj", "Palabra originante tradicional", "Wëroj"),
("Wërojkàlaer", "De 'Wëroj' y 'Kalaer', lit. 'Mover allí'", "Wëroj"),
("Føjleg", "Palabra originante tradicional", "Føjl"),
("Føjleges", "Lit. 'Relativo al norte'", "Føjleg"),
("Føjlar", "Palabra originante tradicional", "Føjl"),
("Frjweg", "Palabra originante tradicional", "Frjw"),
("Frjweges", "Lit. 'Relativo a sur'", "Frjweg"),
("Ruwlejneg", "Palabra originante tradicional", "Ruwlejn"),
("Ruwlejneges", "Lit. 'Relativo a occidente'", "Ruwlejneg"),
("Ruwtaeneg", "Palabra originante tradicional", "Ruwtaen"),
("Ruwtaeneges", "Lit. 'Relativo a oriente'", "Ruwtaeneg"),
("Stjlaw", "Palabra originante tradicional", "Stjlaw"),
("Sëlg", "Palabra originante tradicional", "Sëlg"),
("Sëlgeg", "Palabra originante tradicional", "Sëlg"),
("Sëlgeges", "Lit. 'Relativo a tardanza'", "Sëlgeg"),
("Sëlger", "Palabra originante tradicional", "Sëlg"),
("Gënw", "Palabra originante tradicional", "Gënw"),
("Gënwaj", "Palabra originante tradicional", "Gënw"),
("Gënwajes", "Lit. 'Relativo a tempranez'", "Gënwaj"),
("Gënwar", "Palabra originante tradicional", "Gënw"),
("Kanskë", "Palabra originante tradicional", "Kanskë"),
("Alëred", "Palabra originante tradicional", "Alëred"),
("Raewenj", "Palabra originante tradicional", "Raewenj"),
("Wäld", "Palabra originante tradicional", "Wäld"),
("Tjsälk", "Palabra originante tradicional", "Tjsälk"),
("Künk", "Palabra originante tradicional", "Künk"),
("Laswäld", "Palabra originante tradicional", "Laswäld"),
("Dëjwel", "Palabra originante tradicional", "Dëjwel"),
("Jlaek", "Palabra originante tradicional", "Jlaek"),
("Bäjgun", "Palabra originante tradicional", "Bäjgun"),
("Sästan", "Palabra originante tradicional", "Sästan"),
("Arwjl", "Palabra originante tradicional", "Arwjl"),
("Arwjles", "Lit. 'Relativo a izquierda'", "Arwjl"),
("Ökerjl", "Palabra originante tradicional", "Ökerjl"),
("Ökerjles", "Lit. 'Relativo a derecha'", "Ökerjl"),
("J", "Palabra originante tradicional", "J"),
("Ö", "Palabra originante tradicional", "Ö"),
("Daj", "Palabra originante tradicional", "Daj"),
("Dajes", "Lit. 'Relativo a día'", "Daj"),
("Wàjdaj", "De 'Wajug' y 'Daj', lit. 'Día de nacimiento'", "Waj"),
("Wajdajkèfjeg", "De 'Wajug', 'Daj' y 'Kefjeg', lit. 'Persona con día de nacimiento'", "Waj"),
("Wĵljndaj", "De 'Wjljnaj' y 'Daj', lit. 'Día con libertad'", "Wjljn"),
("Sĵwedaj", "De 'Sjwe' y 'Daj', lit. 'Siete días'", "Sjwe"),
("Sĵwedajes", "De 'Sjwe' y 'Daj', lit. 'Relativo a siete días'", "Sjwe"),
("Trĵtjödaj", "De 'Trj', 'Tjö' y 'Daj', lit. 'Tres decenas de días'", "Trj"),
("Trĵtjödajes", "De 'Trj', 'Tjö' y 'Daj', lit. 'Relativo a tres decenas de días'", "Trĵtjödaj"),
("Dëwoneg", "Palabra originante tradicional", "Dëwon"),
("Dëwoneges", "Lit. 'Relativo a favoritismo'", "Dëwoneg"),
("Dëwonar", "Palabra originante tradicional", "Dëwon"),
("Jgjaeg", "Palabra originante tradicional", "Jgja"),
("Jgjaeges", "Lit. 'Relativo a año'", "Jgjaeg"),
("Jgjaeget", "Lit. 'Año pequeño'", "Jgjaeg"),
("Fajwĵgjaeg", "De 'Fajw' e 'Jgjaeg', lit. 'Cinco años'", "Fajw"),
("Tjöĵgjaeg", "De 'Tjö' e 'Jgjaeg', lit. 'Diez años'", "Tjö"),
("Anküĵgjaeg", "De 'Anküj' e 'Jgjaeg', lit. 'Cien años'", "Anküj"),
("Kaenĵgjaeget", "De 'Kaenaj' y 'Jgjaeget', lit. 'Año pequeño con nieve'", "Kaenĵgjaeg"),
("Kaenĵgjaegetes", "De 'Kaenaj' y 'Jgjaeget', lit. 'Relativo a año pequeño con nieve'", "Kaenĵgjaeg"),
("Sjonĵgjaeget", "De 'Sjonug' y 'Jgjaeget', lit. 'Año pequeño con sol'", "Sjonĵgjaeg"),
("Sjonĵgjaegetes", "De 'Sjonug' y 'Jgjaeget', lit. 'Relativo a año pequeño con sol'", "Sjonĵgjaeg"),
("Wuljgĵgjaeget", "De 'Wuljgaj' y 'Jgjaeget', lit. 'Año pequeño con plantas'", "Wuljgĵgjaeg"),
("Wuljgĵgjaegetes", "De 'Wuljgaj' y 'Jgjaeget', lit. 'Relativo a año pequeño con plantas'", "Wuljgĵgjaeg"),
("Döjkĵgjaeget", "De 'Döjkug' y 'Jgjaeg', lit. 'Año pequeño con caída'", "Döjkĵgjaeg"),
("Döjkĵgjaegetes", "De 'Döjkug' y 'Jgjaeg', lit. 'Relativo a año pequeño con caída'", "Döjkĵgjaeg"),
("Fölwe", "Palabra originante tradicional", "Fölwe"),
("Gölj", "Palabra originante tradicional", "Gölj"),
("Udaj", "Palabra originante tradicional", "Udaj"),
("Gägul", "Palabra originante tradicional", "Gägul"),
("Gägules", "Lit. 'Relativo a presente'", "Gägul"),
("Fjügul", "Palabra originante tradicional", "Fjügul"),
("Fjügules", "Lit. 'Relativo a pasado'", "Fjügul"),
("Trölj", "Palabra originante tradicional", "Trölj"),
("Trudaj", "Palabra originante tradicional", "Trudaj"),
("Följ", "Palabra originante tradicional", "Följ"),
("Wändaj", "De 'Wän' y 'Daj'", "Wändaj"),
("Kängul", "Palabra originante tradicional", "Kängul"),
("Kängules", "Lit. 'Relativo a futuro'", "Kängul"),
("Knöj", "Palabra originante tradicional", "Knöj"),
("Knöjan", "Palabra originante tradicional", "Knöj"),
("Knöjar", "Palabra originante tradicional", "Knöj"),
("Knöjaj", "Palabra originante tradicional", "Knöj"),
("Döjk", "Palabra originante tradicional", "Döjk"),
("Döjkan", "Palabra originante tradicional", "Döjk"),
("Döjker", "Palabra originante tradicional", "Döjk"),
("Döjkug", "Palabra originante tradicional", "Döjk"),
("Sëgt", "Palabra originante tradicional", "Sëgt"),
("Sëgtan", "Palabra originante tradicional", "Sëgt"),
("Sëgtar", "Palabra originante tradicional", "Sëgt"),
("Sëgtaj", "Palabra originante tradicional", "Sëgt"),
("Sëgtajes", "Lit. 'Relativo a entrada'", "Sëgtaj"),
("Sëgteg", "Palabra originante tradicional", "Sëgt"),
("Sëgteges", "Lit. 'Relativo a interior'", "Sëgteg"),
("Fjndar", "Palabra originante tradicional", "Fjnd"),
("Fjndaj", "Palabra originante tradicional", "Fjnd"),
("Fjndajes", "Palabra originante tradicional", "Fjndaj"),
("Tensgar", "Palabra originante tradicional", "Tensg"),
("Tensgaj", "Palabra originante tradicional", "Tensg"),
("Tensgajes", "Lit. 'Relativo a cierre'", "Tensgaj"),
("Kjgsègtaj", "De 'Kjgug' y 'Sëgtaj', lit. 'Entrada de edificio'", "Kjg"),
("Kjglàedejug", "De 'Kjgug' y 'Laedejug', lit. 'Suelo de edificio'", "Kjg"),
("Kjgtèfjajon", "De 'Kjgug' y 'Tëfjajon', lit. 'Capa grande de edificio'", "Kjg"),
("Këngt", "Palabra originante tradicional", "Këngt"),
("Këngtan", "Palabra originante tradicional", "Këngt"),
("Këngter", "Palabra originante tradicional", "Këngt"),
("Këngtug", "Palabra originante tradicional", "Këngt"),
("Këngtuges", "Lit. 'Relativo a salida'", "Këngtug"),
("Këngteg", "Palabra originante tradicional", "Këngt"),
("Këngteges", "Lit. 'Relativo a exterior'", "Këngteg"),
("Önder", "Palabra originante tradicional", "Önd"),
("Öndug", "Palabra originante tradicional", "Önd"),
("Önduges", "Lit. 'Relativo a hogar'", "Öndug"),
("Öndkĵgug", "De 'Öndug' y 'Kjgug', lit. 'edificio de vivienda'", "Önd"),
("Öndkĵguget", "De 'Öndug' y 'Kjgug', lit. 'edificio de vivienda pequeño'", "Öndkĵgug"),
("Öndkĵgugetur", "De 'Öndug' y 'Kjgug', lit. 'Colectivo de edificioes de vivienda pequeños'", "Öndkĵgug"),
("Öndkĵgugon", "De 'Öndug' y 'Kjgug', lit. 'edificio de vivienda grande'", "Öndkĵgug"),
("Öndkèfjeg", "De 'Önder' y 'Kefjeg', lit. 'Persona que habita'", "Önd"),
("Sjfjöndkèfjeg", "De 'Sjfjeg', 'Önder' y 'Kefjeg', lit. 'Persona que habita con tiempo'", "Sjfj"),
("Öndugur", "Lit. 'Colectivo de hogares'", "Öndug"),
("Öndugures", "Lit. 'Relativo a colectivo de hogares'", "Öndug"),
("Anördnug", "Palabra originante tradicional", "Anördn"),
("Öndànördnug", "De 'Öndug' y 'Anördnug', lit. 'Aparato del hogar'", "Önd"),
("Laekaenànördnug", "De 'Laekug', 'Kaenar' y 'Anördnug', lit. 'Aparato para enfriar comida'", "Laek"),
("Laektajklànördnug", "De 'Laekug', 'Tajklar' y 'Anördnug', lit. 'Aparato para quemar comida'", "Laek"),
("Sjfjànördnug", "De 'Sjfjeg' y 'Anördnug', lit. 'Dispositivo del tiempo'", "Sjfj"),
("Wünelànördnug", "De 'Wünelaj' y 'Anördnug', lit. 'Dispositivo de respiración'", "Wünel"),
("Kefjànördnug", "De 'Kefjeg' y 'Anördnug', lit. 'Máquina de persona'", "Kefj"),
("Wjndlànördnug", "De 'Wjndleg' y 'Anördnug', lit. 'Dispositivo de viento'", "Wjndl"),
("Wjndfùtaj", "De 'Wjndleg' y 'Futaj', lit. 'Herramienta de viento'", "Wjndl"),
("Laejreg", "Palabra originante tradicional", "Laejr"),
("Laejreges", "Lit. 'Relativo a música'", "Laejreg"),
("Laejrar", "Palabra originante tradicional", "Laejr"),
("Laejreget", "Lit. 'Música pequeña'", "Laejreg"),
("Laejrfùtaj", "De 'Laejreg' y 'Futaj', lit. 'Herramienta de música'", "Laejr"),
("Laejrfutkèfjeg", "De 'Laejreg', 'Futaj' y 'Kefjeg', lit. 'Persona con herramienta de música'", "Laejr"),
("Laejrfejfkèfjeg", "De 'Laejreg', 'Fejfar' y 'Kefjeg', lit. 'Persona que escribe música'", "Laejr"),
("Laedenlàejreg", "De 'Laedenug' y 'Laejreg', lit. 'Música de país'", "Laeden"),
("Glaer", "Palabra originante tradicional", "Glae"),
("Glaeg", "Palabra originante tradicional", "Glae"),
("Glaeges", "Lit. 'Relativo a amor'", "Glaeg"),
("Glaegaf", "Lit. 'Sin amor'", "Glaeg"),
("Glaegafes", "Lit. 'Relativo a sin amor'", "Glaeg"),
("Glaegafar", "Lit. 'Hacer sin amor'", "Glaeg"),
("Glaeget", "Lit. 'Amor pequeño'", "Glaeg"),
("Glaegetes", "Lit. 'Relativo a amor pequeño'", "Glaeg"),
("Glaegeter", "Lit. 'Hacer amor pequeño'", "Glaeg"),
("Glaegon", "Lit. 'Amor grande'", "Glaeg"),
("Glaekèfjeg", "De 'Glaeg' y 'Kefjeg', lit. 'Persona con amor'", "Glae"),
("Glaekèfjegur", "De 'Glaeg' y 'Kefjeg', lit. 'Colectivo de personas con amor'", "Glaekèfjeg"),
("Fjsljkèfjeg", "De 'Fjsljeg' y 'Kefjeg', lit. 'Persona con cercanía'", "Fjslj"),
("Fjsljkèfjegur", "De 'Fjsljeg' y 'Kefjeg', lit. 'Colectivo de personas con cercanía'", "Fjsljkèfjeg"),
("Lünder", "Palabra originante tradicional", "Lünd"),
("Lündug", "Palabra originante tradicional", "Lünd"),
("Lündkèfjer", "De 'Lündug' y 'Kefjer', lit. 'Crear (una) promesa'", "Lünd"),
("Lündkèfjeg", "De 'Lündug' y 'Kefjeg', lit. 'Persona con promesa'", "Lünd"),
("Lündsjonkèfjeg", "De 'Lündug', 'Sjonug' y 'Kefjeg', lit. 'Persona del sol con promesa'", "Lünd"),
("Lündawalkèfjeg", "De 'Lündug', 'Awalaj' y 'Kefjeg', lit. 'Persona de la luna con promesa'", "Lünd"),
("Lündkèfjegur", "De 'Lündug' y 'Kefjeg', lit. 'Colectivo de personas con promesa'", "Lündkèfjeg"),
("Ljwkeg", "Palabra originante tradicional", "Ljwk"),
("Ljwkeges", "Lit. 'Relativo a felicidad'", "Ljwkeg"),
("Ljwkar", "Palabra originante tradicional", "Ljwk"),
("Ljwkegaf", "Lit. 'Sin felicidad'", "Ljwkeg"),
("Ljwkegafes", "Lit. 'Relativo a sin felicidad'", "Ljwkeg"),
("Ljwkegafar", "Lit. 'Hacer sin felicidad'", "Ljwkeg"),
("Fjslj", "Palabra originante tradicional", "Fjslj"),
("Fjsljar", "Palabra originante tradicional", "Fjslj"),
("Fjsljeg", "Palabra originante tradicional", "Fjslj"),
("Fjsljeges", "Lit. 'Relativo a cercanía'", "Fjsljeg"),
("Ösjwat", "Palabra originante tradicional", "Ösjwat"),
("Ösjwateg", "Palabra originante tradicional", "Ösjwat"),
("Ösjwateges", "Lit. 'Relativo a lejanía'", "Ösjwateg"),
("Ösjwater", "Palabra originante tradicional", "Ösjwat"),
("Täg", "Palabra originante tradicional", "Täg"),
("Tägeg", "Palabra originante tradicional", "Täg"),
("Bljst", "Palabra originante tradicional", "Bljst"),
("Bljsteg", "Palabra originante tradicional", "Bljst"),
("Bljsteges", "Lit. 'Relativo a creencia'", "Bljsteg"),
("Klën", "Palabra originante tradicional", "Klën"),
("Klënug", "Palabra originante tradicional", "Klën"),
("Dasker", "Palabra originante tradicional", "Dask"),
("Daskeg", "Palabra originante tradicional", "Dask"),
("Daskeges", "Lit. 'Relativo a valentía'", "Daskeg"),
("Daskegon", "Lit. 'Valentía grande'", "Daskeg"),
("Daskegones", "Lit. 'Relativo a valentía grande'", "Daskeg"),
("Daskegaf", "Lit. 'Sin valentía'", "Daskeg"),
("Daskegafes", "Lit. 'Relativo a sin valentía'", "Daskeg"),
("Daskegafon", "Lit. 'Sin valentía grande'", "Daskeg"),
("Daskegafer", "Lit. 'Hacer sin valentía'", "Daskeg"),
("Fëjr", "Palabra originante tradicional", "Fëjr"),
("Fëjreg", "Palabra originante tradicional", "Fëjr"),
("Fëjregur", "Lit. 'Colectivo de conocimientos'", "Fëjreg"),
("Fëjregures", "Lit. 'Relativo a colectivo de conocimientos'", "Fëjreg"),
("Fëjregaf", "Lit. 'Sin conocimiento'", "Fëjreg"),
("Fëjregafes", "Lit. 'Relativo a sin conocimiento'", "Fëjreg"),
("Fëjregafer", "Lit. 'Hacer sin conocimiento'", "Fëjreg"),
("Fëjrsfàejug", "De 'Fëjreg' y 'Sfaejug', lit. 'Capacidad de saber'", "Fëjr"),
("Fëjrsfàejuges", "De 'Fëjreg' y 'Sfaejug', lit. 'Relativo a capacidad de saber'", "Fëjrsfàejug"),
("Glas", "Palabra originante tradicional", "Glas"),
("Glasug", "Palabra originante tradicional", "Glas"),
("Glasuges", "Lit. 'Relativo a gusto'", "Glasug"),
("Glasugaf", "Lit. 'Sin gusto'", "Glasug"),
("Glasugafes", "Lit. 'Relativo a sin gusto'", "Glasug"),
("Glasugafer", "Lit. 'Hacer sin gusto'", "Glasug"),
("Glasugon", "Lit. 'Gusto grande'", "Glasug"),
("Glasugones", "Lit. 'Relativo a gusto grande'", "Glasug"),
("Glasugoner", "Lit. 'Hacer gusto grande'", "Glasug"),
("Ertjeg", "Palabra originante tradicional", "Ertj"),
("Ertjeges", "Lit. 'Relativo a paciencia'", "Ertjeg"),
("Ertjegaf", "Lit. 'Sin paciencia'", "Ertjeg"),
("Ertjegafes", "Lit. 'Relativo a sin paciencia'", "Ertjeg"),
("Wüjk", "Palabra originante tradicional", "Wüjk"),
("Wüjkug", "Palabra originante tradicional", "Wüjk"),
("Wüjkuges", "Lit. 'Relativo a deseo'", "Wüjkug"),
("Wüjkugon", "Lit. 'Deseo grande'", "Wüjkug"),
("Wüjkugones", "Lit. 'Relativo a deseo grande'", "Wüjkug"),
("Wüjkugoner", "Lit. 'Hacer deseo grande'", "Wüjkug"),
("Kolörar", "Palabra originante tradicional", "Kolör"),
("Kolöreg", "Palabra originante tradicional", "Kolör"),
("Kolöreges", "Lit. 'Relativo a color'", "Kolöreg"),
("Kolöregaf", "Lit. 'Sin color'", "Kolöreg"),
("Kolöregafes", "Lit. 'Relativo a sin color'", "Kolöreg"),
("Wärteg", "Palabra originante tradicional", "Wärt"),
("Wärtkèfjeg", "De 'Wärteg' y 'Kefjeg', lit. 'Persona con negro'", "Wärt"),
("Wärter", "Palabra originante tradicional", "Wärt"),
("Wjteg", "Palabra originante tradicional", "Wjt"),
("Wjter", "Palabra originante tradicional", "Wjt"),
("Wjtkèfjeg", "De 'Wjteg' y 'Kefjeg', lit. 'Persona con blanco'", "Wjt"),
("Grjneg", "Palabra originante tradicional", "Grjn"),
("Rödeg", "Palabra originante tradicional", "Röd"),
("Jeloweg", "Palabra originante tradicional", "Jelow"),
("Blutbeg", "Palabra originante tradicional", "Blutb"),
("Öraeneg", "Palabra originante tradicional", "Öraen"),
("Sølweg", "Palabra originante tradicional", "Sølw"),
("Gjldeg", "Palabra originante tradicional", "Gjld"),
("Fjaler", "Palabra originante tradicional", "Fjal"),
("Fjalaj", "Palabra originante tradicional", "Fjal"),
("Tjröl", "Palabra originante tradicional", "Tjröl"),
("Tjrölug", "Palabra originante tradicional", "Tjröl"),
("Sfaej", "Palabra originante tradicional", "Sfaej"),
("Sfaejug", "Palabra originante tradicional", "Sfaej"),
("Sfaejuges", "Lit. 'Relativo a capacidad'", "Sfaejug"),
("Sfaejugaf", "Lit. 'Sin capacidad'", "Sfaejug"),
("Sfaejugafes", "Lit. 'Relativo a sin capacidad'", "Sfaejug"),
("Sfaejugafer", "Lit. 'Hacer sin capacidad'", "Sfaejug"),
("Wast", "Palabra originante tradicional", "Wast"),
("Wasteg", "Palabra originante tradicional", "Wast"),
("Wasteget", "Lit. 'Mirada pequeña'", "Wasteg"),
("Wastegetar", "Lit. 'Hacer mirada pequeña'", "Wasteg"),
("Wastsfàejug", "De 'Wasteg' y 'Sfaejug', lit. 'Capacidad de vista'", "Wast"),
("Dalënar", "Palabra originante tradicional", "Dalën"),
("Dalënaj", "Palabra originante tradicional", "Dalën"),
("Dalënajet", "Lit. 'Caminata pequeña'", "Dalënaj"),
("Dalënajetar", "Lit. 'Hacer caminata pequeña'", "Dalënaj"),
("Dalënajon", "Lit. 'Caminata grande'", "Dalënaj"),
("Knoter", "Palabra originante tradicional", "Knot"),
("Knotug", "Palabra originante tradicional", "Knot"),
("Knotuget", "Palabra originante tradicional", "Knotug"),
("Knotugeter", "Palabra originante tradicional", "Knotug"),
("Kaj", "Palabra originante tradicional", "Kaj"),
("Kajeg", "Palabra originante tradicional", "Kaj"),
("Kajfùteg", "De 'Kaj' y 'Futeg', lit. 'Cosa que vive'", "Kaj"),
("Futeg", "Palabra originante tradicional", "Fut"),
("Futaj", "Palabra originante tradicional", "Fut"),
("Knjfajeg", "Palabra originante tradicional", "Knjfaj"),
("Towlajug", "Palabra originante tradicional", "Towlaj"),
("Sølwtòwlajug", "De 'Sølweg' y 'Towlajug', lit. 'Metal plateado'", "Sølw"),
("Gjldtòwlajug", "De 'Gjldeg' y 'Towlajug', lit. 'Metal dorado'", "Gjld"),
("Alar", "Palabra originante tradicional", "Al"),
("Aleg", "Palabra originante tradicional", "Al"),
("Tänksaj", "Palabra originante tradicional", "Tänks"),
("Tänksajaf", "Lit. 'Sin agradecimiento'", "Tänksaj"),
("Tänksajafar", "Lit. 'Hacer sin agradecimiento'", "Tänksaj"),
("Tänksar", "Palabra originante tradicional", "Tänks"),
("Kojwkèfjeg", "De 'Kojweg' y 'Kefjeg', lit. 'Persona del cielo'", "Kojw"),
("Kojwkèfjegur", "De 'Kojweg' y 'Kefjeg', lit. 'Colectivo de personas del cielo'", "Kojwkèfjeg"),
("Fejfkèfjeg", "De 'Fejfar' y 'Kefjeg', lit. 'Persona que escribe'", "Fejf"),
("Knotkèfjeg", "De 'Knoter' y 'Kefjeg', lit. 'Persona que canta'", "Knot"),
("Tökèfjegur", "De 'Tö' y 'Kefjeg', lit. 'Colectivo de dos personas'", "Tökèfjeg"),
("Trjkèfjeg", "De 'Trj' y 'Kefjeg', lit. 'Tres personas'", "Trj"),
("Jagnar", "Palabra originante tradicional", "Jagn"),
("Jagneg", "Palabra originante tradicional", "Jagn"),
("Üstal", "Palabra originante tradicional", "Üstal"),
("Üstaleg", "Palabra originante tradicional", "Üstal"),
("Üstalsfàejug", "De 'Üstal' y 'Sfaejug', lit. 'Capacidad de sentir'", "Üstal"),
("Ündjl", "Palabra originante tradicional", "Ündjl"),
("Träsjl", "Palabra originante tradicional", "Träsjl"),
("Rjwdar", "Palabra originante tradicional", "Rjwd"),
("Rjwdeg", "Palabra originante tradicional", "Rjwd"),
("Rjnlug", "Palabra originante tradicional", "Rjnl"),
("Rjnljàgar", "De 'Rjnlug' y 'Jagar', lit. 'Mojar (un) cuerpo'", "Rjnl"),
("Rjnljàgaj", "De 'Rjnlug' y 'Jagaj', lit. 'Agua de cuerpo'", "Rjnl"),
("Rjnler", "Palabra originante tradicional", "Rjnl"),
("Knawar", "Palabra originante tradicional", "Knaw"),
("Knaweg", "Palabra originante tradicional", "Knaw"),
("Knawsfàejug", "De 'Knawar' y 'Sfaejug', lit. 'Capacidad de morir'", "Knaw"),
("Knawsfàejugaf", "De 'Knawar' y 'Sfaejug', lit. 'Sin capacidad de morir'", "Knawsfàejug"),
("Knawsfàejugafar", "De 'Knawar' y 'Sfaejugaf', lit. 'Hacer sin capacidad de morir'", "Knawsfàejug"),
("Knawkèfjeg", "De 'Knaweg' y 'Kefjeg', lit. 'Persona con muerte'", "Knaw"),
("Knawegafkèfjeg", "De 'Knawegaf' y 'Kefjeg', lit. 'Persona sin muerte'", "Knaw"),
("Jneger", "Palabra originante tradicional", "Jneg"),
("Jnegeg", "Palabra originante tradicional", "Jneg"),
("Fönler", "Palabra originante tradicional", "Fönl"),
("Fönleg", "Palabra originante tradicional", "Fönl"),
("Laedenfònleg", "De 'Laedenug' y 'Fönleg', lit. 'Símbolo de país'", "Laeden"),
("Daljar", "Palabra originante tradicional", "Dalj"),
("Daljaj", "Palabra originante tradicional", "Dalj"),
("Daljajaf", "Lit. 'Sin verdad'", "Daljaj"),
("Daljajafar", "Lit. 'Hacer sin verdad'", "Daljaj"),
("Laewün", "Palabra originante tradicional", "Laewün"),
("Laewüneg", "Palabra originante tradicional", "Laewün"),
("Laewünsfàejug", "De 'Laewüneg' y 'Sfaejug', lit. 'Capacidad de escucha'", "Laewün"),
("Laewünsfàejugaf", "De 'Laewüneg' y 'Sfaejug', lit. 'Sin capacidad de escucha'", "Laewünsfàejug"),
("Laewünkèfjeg", "De 'Laewün' y 'Kefjeg', lit. 'Persona que escucha'", "Laewün"),
("Laewünkèfjegur", "De 'Laewün' y 'Kefjegur', lit. 'Colectivo de personas que escuchan'", "Laewünkèfjeg"),
("Wejkrjner", "Palabra originante tradicional", "Wejkrjn"),
("Wejkrjneg", "Palabra originante tradicional", "Wejkrjn"),
("Knawèjkrjner", "De 'Knaweg' y 'Wejkrjner', lit. 'Delinquir en muerte'", "Knaw"),
("Knawèjkrjneg", "De 'Knaweg' y 'Wejkrjneg', lit. 'Delito de muerte'", "Knaw"),
("Lujkwèjkrjner", "De 'Lujkaj' y 'Wejkrjner', lit. 'Delinquir en dinero'", "Lujk"),
("Lujkwèjkrjneg", "De 'Lujkaj' y 'Wejkrjneg', lit. 'Delito de dinero'", "Lujk"),
("Traewèjkrjneg", "De 'Traewug' y 'Wejkrjneg', lit. 'Delito de ataque'", "Traew"),
("Traewèjkrjner", "De 'Traewug' y 'Wejkrjner', lit. 'Delinquir en ataque'", "Traew"),
("Wöjlegafwèjkrjneg", "De 'Wöjlegaf' y 'Wejkrjneg', lit. 'Delito de sufrimiento'", "Wöjl"),
("Wöjlegafwèjkrjner", "De 'Wöjlegaf' y 'Wejkrjner', lit. 'Hacer delito de sufrimiento'", "Wöjl"),
("Wejkrjnkèfjeg", "De 'Wejkrjner' y 'Kefjeg', lit. 'Persona que delinque'", "Wejkrjn"),
("Djlug", "Palabra originante tradicional", "Djl"),
("Djluget", "Lit. 'Filamento pequeño'", "Djlug"),
("Djlugetur", "Lit. 'Colectivo de filamentos pequeños'", "Djlug"),
("Kefjdĵlugetur", "De 'Kefjeg' y 'Djlugetur', lit. 'Colectivo de filamentos pequeños para persona'", "Kefj"),
("Blöder", "Palabra originante tradicional", "Blöd"),
("Blödug", "Palabra originante tradicional", "Blöd"),
("Blödfjalkèfjeg", "De 'Blödug', 'Fjaler' y 'Kefjeg', lit. 'Persona que bebe sangre'", "Blöd"),
("Blödùrnug", "De 'Blödug' y 'Ürnug', lit. 'Órgano de sangre'", "Blöd"),
("Blödlĵneg", "De 'Blödug' y 'Ljneg', lit. 'Línea de sangre'", "Blöd"),
("Blödlĵneget", "De 'Blödug' y 'Ljneg', lit. 'Línea de sangre pequeña'", "Blödlĵneg"),
("Kefjer", "Palabra originante tradicional", "Kefj"),
("Kefjeg", "Palabra originante tradicional, lit. 'Persona/Concepción'", "Kefj"),
("Kefjegur", "Lit. 'Colectivo de personas'", "Kefjeg"),
("Kefjeget", "Lit. 'Persona pequeña'", "Kefjeg"),
("Kefjegeter", "Lit. 'Hacer persona pequeña'", "Kefjeg"),
("Kefjegetur", "Lit. 'Colectivo de personas pequeñas'", "Kefjeget"),
("Kefjegetkĵgug", "De 'Kefjeget' y 'Kjgug', lit. 'edificio de personas pequeñas'", "Kefj"),
("Kefjegon", "Lit. 'Persona grande'", "Kefjeg"),
("Kefjegonkĵgug", "De 'Kefjegon' y 'Kjgug', lit. 'edificio de personas grandes'", "Kefj"),
("Kefjegoner", "Lit. 'Hacer(se) persona grande'", "Kefjeg"),
("Kefjegonur", "Lit. 'Colectivo de personas grandes'", "Kefjeg"),
("Enljar", "Palabra originante tradicional", "Enlj"),
("Enljeg", "Palabra originante tradicional", "Enlj"),
("Enljegaf", "Lit. 'Sin juventud'", "Enljeg"),
("Enljegafar", "Lit. 'Hacer sin juventud'", "Enljeg"),
("Bljunar", "Palabra originante tradicional", "Bljun"),
("Bljuneg", "Palabra originante tradicional", "Bljun"),
("Bljunegaf", "Lit. 'Sin belleza'", "Bljuneg"),
("Bljunegafar", "Lit. 'Hacer sin belleza'", "Bljuneg"),
("Bljunegafèjfeg", "De 'Bljunegaf' y 'Fejfeg', lit. 'Palabra sin hermosura'", "Bljun"),
("Läjrar", "Palabra originante tradicional", "Läjr"),
("Läjraj", "Palabra originante tradicional", "Läjr"),
("Läjreg", "Palabra originante tradicional", "Läjr"),
("Läjrkĵgug", "De 'Läjreg' y 'Kjgug', lit. 'edificio de educación'", "Läjr"),
("Läjraurkĵgug", "De 'Läjreg', 'Aurag' y 'Kjgug', lit. 'edificio de reunión de educación'", "Läjr"),
("Läjrkèfjeg", "De 'Läjrar' y 'Kefjeg', lit. 'Persona que educa'", "Läjr"),
("Fenser", "Palabra originante tradicional", "Fens"),
("Fenseg", "Palabra originante tradicional", "Fens"),
("Fenskèfjeg", "De 'Fenser' y 'Kefjeg', lit. 'Persona que aprende'", "Fens"),
("Rawolar", "Palabra originante tradicional", "Rawol"),
("Rawolaj", "Palabra originante tradicional", "Rawol"),
("Rawolajaf", "Lit. 'Sin victoria'", "Rawolaj"),
("Rawolajafar", "Lit. 'Hacer sin victoria'", "Rawolaj"),
("Sjonkèfjeg", "De 'Sjonug' y 'Kefjeg', lit. 'Persona del sol'", "Sjon"),
("Sjonkèfjeget", "De 'Sjonug' y 'Kefjeget', lit. 'Persona pequeña del sol'", "Sjon"),
("Awalkèfjeg", "De 'Awalaj' y 'Kefjeg', lit. 'Persona de la luna'", "Awal"),
("Awalkèfjeget", "De 'Awalaj' y 'Kefjeget', lit. 'Persona pequeña de la luna'", "Awalkèfjeg"),
("Fatjgeg", "Palabra originante tradicional", "Fatjg"),
("Fatjger", "Palabra originante tradicional", "Fatjg"),
("Wülejtug", "Palabra originante tradicional", "Wülejt"),
("Kjltwùlejtug", "De 'Kjltaj' y 'Wülejtug', lit. 'Animal con leche'", "Kjlt"),
("Gaelwùlejtug", "De 'Gaelwar' y 'Wülejtug', lit. 'Animal que vuela'", "Gaelw"),
("Gaelwar", "Palabra originante tradicional", "Gaelw"),
("Gaelwaj", "Palabra originante tradicional", "Gaelw"),
("Öndwùlejtug", "De 'Öndug' y 'Wülejtug', lit. 'Animal de hogar'", "Önd"),
("Wülejwàjug", "De 'Wülejtug' y 'Wajug', lit. 'Bebé de animal'", "Wülejt"),
("Wuljgar", "Palabra originante tradicional", "Wuljg"),
("Wuljgaj", "Palabra originante tradicional", "Wuljg"),
("Wuljgajet", "Lit. 'Planta pequeña'", "Wuljgaj"),
("Wuljgajetar", "Lit. 'Hacer planta pequeña'", "Wuljgaj"),
("Wuljgajon", "Lit. 'Planta grande'", "Wuljgaj"),
("Wuljgajonur", "Lit. 'Colectivo de plantas grandes'", "Wuljgaj"),
("Bljunwùljgajar", "De 'Bljuneg' y 'Wuljgar', lit. 'Hacer una planta hermosa'", "Bljun"),
("Bljunwùljgaj", "De 'Bljuneg' y 'Wuljgaj', lit. 'Planta hermosa'", "Bljun"),
("Wjtbljunwùljgaj", "Palabra de patrimonio nacional, de 'Wjteg', 'Bljuneg' y 'Wuljgaj', lit. 'Planta hermosa blanca'", "Wjt"),
("Jagwùljgaj", "De 'Jagaj' y 'Wuljgaj', lit. 'Planta del agua'", "Jag"),
("Laedejwùljgaj", "De 'Laedejug' y 'Wuljgaj', lit. 'Planta de la tierra'", "Laedej"),
("Laedejwùljgajur", "De 'Laedejug' y 'Wuljgaj', lit. 'Colectivo de plantas de la tierra'", "Laedejwùljgaj"),
("Wuljgtèfjajet", "De 'Wuljgaj' y 'Tëfjajet', lit. 'Capa pequeña de planta'", "Wuljg"),
("Wuljgtèfjajetur", "De 'Wuljgaj' y 'Tëfjajet', lit. 'Conjunto de capas pequeñas de planta'", "Wuljg"),
("Daweglàedejug", "De 'Dawegeg' y 'Laedejug', lit. 'Tierra con altura'", "Daweg"),
("Tajkdaweglàedejug", "De 'Tajkleg', 'Dawegeg' y 'Laedejug', lit. 'Tierra con altura con fuego'", "Tajkl"),
("Daweglàedejuget", "De 'Dawegeg' y 'Laedejug', lit. 'Tierra con altura pequeña'", "Daweglàedejug"),
("Daweglàedejugur", "De 'Dawegeg' y 'Laedejug', lit. 'Colectivo de tierras con altura'", "Daweglàedejug"),
("Kaenlàedejug", "De 'Kaenaj' y 'Laedejug', lit. 'Tierra de nieve'", "Kaen"),
("Wöjler", "Palabra originante tradicional", "Wöjl"),
("Wöjleg", "Palabra originante tradicional", "Wöjl"),
("Wöjlegaf", "Lit. 'Sin placer'", "Wöjleg"),
("Wöjlegafar", "Lit. 'Hacer sin placer'", "Wöjleg"),
("Dönjlaj", "Palabra originante tradicional", "Dönjl"),
("Dönjlar", "Palabra originante tradicional", "Dönjl"),
("Dönjlajaf", "Lit. 'Sin cura'", "Dönjlaj"),
("Dönjlajafar", "Lit. 'Hacer sin cura'", "Dönjlaj"),
("Dönjleg", "Palabra originante tradicional", "Dönjl"),
("Dönjlegaf", "Palabra originante tradicional", "Dönjleg"),
("Dönjlfèjregur", "De 'Dönjlaj' y 'Fëjregur', lit. 'Colectivo de conocimientos de curas'", "Dönjl"),
("Dönjlkèfjeg", "De 'Dönjlar' y 'Kefjeg', lit. 'Persona que cura'", "Dönjl"),
("Wjrus", "Palabra adoptada artificialmente del inglés 'Virus'", "Wjrus"),
("Denokrätĵa", "Palabra adoptada artificialmente del griego 'Dēmokratía'", "Denokrätĵa"),
("Laedejug", "Palabra originante tradicional", "Laedej"),
("Laedejar", "Palabra originante tradicional", "Laedej"),
("Jaglàedejug", "De 'Jagaj' y 'Laedejug', lit. 'Tierra con agua'", "Jag"),
("Jagbĵseleg", "De 'Jagaj' y 'Bjseleg', lit. 'Aire con agua'", "Jag"),
("Laedenar", "Palabra originante tradicional", "Laeden"),
("Laedenug", "Palabra originante tradicional", "Laeden"),
("Laedenuget", "Lit. 'País pequeño'", "Laedenug"),
("Laedenugur", "Lit. 'Colectivo de países'", "Laedenug"),
("Laedenkèfjeg", "De 'Laedenug' y 'Kefjeg', lit. 'Persona de país'", "Laeden"),
("Laedenkèfjegur", "De 'Laedenug' y 'Kefjeg', lit. 'Colectivo de personas de país'", "Laedenkèfjeg"),
("Laedenugafkèfjeg", "De 'Laedenugaf' y 'Kefjeg', lit. 'Persona sin país'", "Laeden"),
("Laedenwenkèfjeg", "De 'Laedenug', 'Wenkeg' y 'Kefjeg', lit. 'Persona con igualdad de país'", "Laeden"),
("Swolug", "Palabra originante tradicional", "Swol"),
("Swoluget", "Lit. 'Ciudad pequeña'", "Swolug"),
("Swolugon", "Lit. 'Ciudad grande'", "Swolug"),
("Swolkèfjeg", "De 'Swolug' y 'Kefjeg', lit. 'Persona de ciudad'", "Swol"),
("Wenkar", "Palabra originante tradicional", "Wenk"),
("Wenkeg", "Palabra originante tradicional", "Wenk"),
("Wenkeget", "Lit. 'Igualdad pequeña'", "Wenkeg"),
("Wenkegaf", "Lit. 'Sin igualdad'", "Wenkeg"),
("Wenkèfjeg", "De 'Wenkeg' y 'Kefjeg', lit. 'Persona con igualdad'", "Wenk"),
("Wenkfèjfeg", "De 'Wenkeg' y 'Fejfeg', lit. 'Palabra con igualdad'", "Wenk"),
("Kjgeg", "Palabra originante tradicional", "Kjg"),
("Kjger", "Palabra originante tradicional", "Kjg"),
("Kördar", "Palabra originante tradicional", "Körd"),
("Kördaj", "Palabra originante tradicional", "Körd"),
("Kördajaf", "Lit. 'Sin cordura'", "Kördaj"),
("Kördajafar", "Lit. 'Hacer sin cordura'", "Kördaj"),
("Sjfjeg", "Palabra originante tradicional", "Sjfj"),
("Wenksĵfjeg", "De 'Wenkeg' y 'Sjfjeg', lit. 'Tiempo con igualdad'", "Wenk"),
("Wenksĵfjeges", "De 'Wenkeg' y 'Sjfjeg', lit. 'Relativo a tiempos con igualdad'", "Wenksĵfjeg"),
("Fostar", "Palabra originante tradicional", "Fost"),
("Fosteg", "Palabra originante tradicional", "Fost"),
("Fostegon", "Lit. 'Delgadez grande'", "Fosteg"),
("Fostegaf", "Lit. 'Sin delgadez'", "Fosteg"),
("Fostegafar", "Lit. 'Hacer sin delgadez'", "Fosteg"),
("Fostegafon", "Lit. 'Sin delgadez grande'", "Fosteg"),
("Wjster", "Palabra originante tradicional", "Wjst"),
("Wjsteg", "Palabra originante tradicional", "Wjst"),
("Öwader", "Palabra originante tradicional", "Öwad"),
("Öwadeg", "Palabra originante tradicional", "Öwad"),
("Öwadegaf", "Lit. 'Sin encuentro'", "Öwadeg"),
("Öwadegafer", "Lit. 'Hacer sin encuentro'", "Öwadeg"),
("Laegjer", "Palabra originante tradicional", "Laegj"),
("Laegjug", "Palabra originante tradicional", "Laegj"),
("Jagar", "Palabra originante tradicional", "Jag"),
("Jagaj", "Palabra originante tradicional", "Jag"),
("Jager", "Palabra originante tradicional", "Jag"),
("Jageg", "Palabra originante tradicional", "Jag"),
("Jagegaf", "Lit. 'Sin hidratación'", "Jageg"),
("Jagegafar", "Lit. 'Hacer sin hidratación'", "Jageg"),
("Jagegaflàedejug", "De 'Jagegaf' y 'Laedejug', lit. 'Tierra sin hidratación'", "Jag"),
("Jagajet", "Lit. 'Agua pequeña'", "Jagaj"),
("Jagajon", "Lit. 'Agua grande'", "Jagaj"),
("Jagajur", "Lit. 'Colectivo de aguas'", "Jagaj"),
("Jagajuron", "Lit. 'Colectivo de aguas grande'", "Jagaj"),
("Jaglĵneg", "De 'Jagaj' y 'Ljneg', lit. 'Línea de agua'", "Jag"),
("Jaglĵneget", "De 'Jagaj' y 'Ljneg', lit. 'Línea de agua pequeña'", "Jaglĵneg"),
("Waelar", "Palabra originante tradicional", "Wael"),
("Waeleg", "Palabra originante tradicional", "Wael"),
("Kjltar", "Palabra originante tradicional", "Kjlt"),
("Kjlteg", "Palabra originante tradicional", "Kjlt"),
("Kjltaj", "Palabra originante tradicional", "Kjlt"),
("Süjkĵltaj", "De 'Süjkaj' y 'Kjltaj', lit. 'Leche de azúcar'", "Süjk"),
("Grüfer", "Palabra originante tradicional", "Grüf"),
("Grüfug", "Palabra originante tradicional", "Grüf"),
("Grüfwùljgajet", "De 'Grüfug' y 'Wuljgajet', lit. 'Planta pequeña de café'", "Grüf"),
("Süjkjltgrùfug", "De 'Süjkaj', 'Kjltaj' y 'Grüfug', lit. 'Café con leche con azúcar'", "Süjk"),
("Tënkaj", "Palabra originante tradicional", "Tënk"),
("Ökjler", "Palabra originante tradicional", "Ökjl"),
("Ökjlug", "Palabra originante tradicional", "Ökjl"),
("Ökjlugaf", "Lit. 'Sin reparación'", "Ökjlug"),
("Ökjlugafer", "Lit. 'Hacer sin reparación'", "Ökjlug"),
("Beräter", "Palabra originante tradicional", "Berät"),
("Beräteg", "Palabra originante tradicional", "Berät"),
("Beräteget", "Lit. 'Historia pequeña'", "Beräteg"),
("Awalbèräteg", "De 'Awalaj' y 'Beräteg', lit. 'Historia de la luna'", "Awal"),
("Färalawalbèräteg", "De 'Färaleg', 'Awalaj' y 'Beräteg', lit. 'Historia de la luna de mala condición'", "Färal"),
("Awalbèräter", "De 'Awalaj' y 'Beräter', lit. 'Narrar con la luna'", "Awal"),
("Ürnug", "Palabra originante tradicional", "Ürn"),
("Wastùrnug", "De 'Wasteg' y 'Ürnug', lit. 'Órgano de vista'", "Wast"),
("Laewünùrnug", "De 'Laewüneg' y 'Ürnug', lit. 'Órgano de escucha'", "Laewün"),
("Golunùrnug", "De 'Golunar' y 'Ürnug', lit. 'Órgano para degustar'", "Golun"),
("Öwelug", "Palabra originante tradicional", "Öwel"),
("Öwelugur", "Lit. 'Colectivo de cabellos'", "Öwelug"),
("Öweluguraf", "Lit. 'Sin colectivo de cabellos'", "Öwelug"),
("Gjldòwelugur", "De 'Gjldeg' y 'Öwelugur', lit. 'Colectivo de cabellos dorados'", "Gjld"),
("Wärtòwelugur", "De 'Wärteg' y 'Öwelugur', lit. 'Colectivo de cabellos negros'", "Wärt"),
("Kaenòwelug", "De 'Kaenaj' y 'Öwelug', lit. 'Cabello de nieve'", "Kaen"),
("Tajklar", "Palabra originante tradicional", "Tajkl"),
("Tajkleg", "Palabra originante tradicional", "Tajkl"),
("Bjseleg", "Palabra originante tradicional", "Bjsel"),
("Bjseler", "Palabra originante tradicional", "Bjsel"),
("Wünelar", "Palabra originante tradicional", "Wünel"),
("Wünelaj", "Palabra originante tradicional", "Wünel"),
("Sëgwùnelar", "De 'Sëgtan' y 'Wünelar', lit. 'Respirar adentro'", "Sëgt"),
("Sëgwùnelaj", "De 'Sëgtan' y 'Wünelaj', lit. 'Respiración adentro'", "Sëgt"),
("Bjselùrnug", "De 'Bjseleg' y 'Ürnug', lit. 'Órgano de aire'", "Bjsel"),
("Bejnar", "Palabra originante tradicional", "Bejn"),
("Bejnaj", "Palabra originante tradicional", "Bejn"),
("Bejnajaf", "Palabra originante tradicional", "Bejnaj"),
("Bejnajafar", "Palabra originante tradicional", "Bejnaj"),
("Dogöner", "Palabra originante tradicional", "Dogön"),
("Dogönug", "Palabra originante tradicional", "Dogön"),
("Dogönàlentar", "De 'Dogönug' y 'Alentar', lit. 'Aceptar (una) orden'", "Dogön"),
("Dogönàlentaj", "De 'Dogönug' y 'Alentaj', lit. 'Aceptación de orden'", "Dogön"),
("Dogönàlentajes", "De 'Dogönug' y 'Alentaj', lit. 'Relativo a aceptación de orden'", "Dogönàlentaj"),
("Dogönalentkèfjeg", "De 'Dogönug', 'Alentaj' y 'Kefjeg', lit. 'Persona con aceptación de orden'", "Dogön"),
("Bëndjleg", "Palabra originante tradicional", "Bëndjl"),
("Bëndjlar", "Palabra originante tradicional", "Bëndjl"),
("Fändjleg", "Palabra originante tradicional", "Fändjl"),
("Fändjlegaf", "Lit. 'Sin final'", "Fändjleg"),
("Fändjlar", "Palabra originante tradicional", "Fändjl"),
("Fejfàndjleg", "De 'Fejfug' y 'Fändjleg', lit. 'Fin de texto'", "Fejf"),
("Fejfbèndjleg", "De 'Fejfug' y 'Bëndjleg', lit. 'Inicio de texto'", "Fejf"),
("Wenslaj", "Palabra originante tradicional", "Wensl"),
("Wenslar", "Palabra originante tradicional", "Wensl"),
("Söjwènslar", "De 'Söjwaj' y 'Wenslar', lit. 'Leer con diálogo'", "Söjw"),
("Söjwènslaj", "De 'Söjwaj' y 'Wenslaj', lit. 'Lectura con diálogo'", "Söjw"),
("Jöner", "Palabra originante tradicional", "Jön"),
("Jönug", "Palabra originante tradicional", "Jön"),
("Jönugaf", "Lit. 'Sin continuación'", "Jönug"),
("Jönugafer", "Lit. 'Hacer sin continuación'", "Jönug"),
("Enäj", "Palabra originante tradicional", "Enäj"),
("Enäjeg", "Palabra originante tradicional", "Enäj"),
("Enäjer", "Palabra originante tradicional", "Enäj"),
("Färal", "Palabra originante tradicional", "Färal"),
("Färaleg", "Palabra originante tradicional", "Färal"),
("Färaler", "Palabra originante tradicional", "Färal"),
("Färalùjkar", "De 'Färal' y 'Lujkar', lit. 'Gastar mal'", "Färal"),
("Wjndleg", "Palabra originante tradicional", "Wjndl"),
("Wjndleget", "Palabra originante tradicional", "Wjndleg"),
("Aurar", "Palabra originante tradicional", "Aur"),
("Aurug", "Palabra originante tradicional", "Aur"),
("Aurkĵgug", "De 'Aurug', y 'Kjgug', lit. 'edificio de reunión'", "Aur"),
("Laekaurkĵgug", "De 'Laekug', 'Aurug' y 'Kjgug', lit. 'edificio de reunión de comida'", "Laek"),
("Awalaurkĵgug", "De 'Awalar', 'Aurug' y 'Kjgug', lit. 'edificio de reunión para dormir'", "Awal"),
("Jagaurkĵgug", "De 'Jagaj', 'Aurug' y 'Kjgug', lit. 'edificio de reunión de agua'", "Jag"),
("Ëgael", "Palabra originante tradicional", "Ëgael"),
("Frogaelaj", "Palabra originante tradicional", "Frogael"),
("Frogael", "Palabra originante tradicional", "Frogael"),
("Ulerug", "Palabra originante tradicional", "Uler"),
("Ulerfjàlaj", "De 'Ulerug' y 'Fjalaj', lit. 'Bebida con alcohol'", "Uler"),
("Ulerer", "Palabra originante tradicional", "Uler"),
("Laeker", "Palabra originante tradicional", "Laek"),
("Laektàjklar", "De 'Laekug' y 'Tajklar'. lit. 'Quemar comida'", "Laek"),
("Laektàjkleg", "De 'Laekug' y 'Tajklar'. lit. 'Fuego con comida'", "Laek"),
("Laekug", "Palabra originante tradicional", "Laek"),
("Laekuget", "Lit. 'Comida pequeña'", "Laekug"),
("Laekugaf", "Lit. 'Sin comida'", "Laekug"),
("Laekĵgug", "De 'Laekug' y 'Kjgug', lit. 'edificio de comida'", "Laek"),
("Wänlàekug", "De 'Wän' y 'Laekug', lit. 'Primera comida'", "Wän"),
("Wänlàeker", "De 'Wän' y 'Laeker', lit. 'Primer comer'", "Wän"),
("Sjonlàekug", "De 'Sjonug' y 'Laekug', lit. 'Comida del sol'", "Sjon"),
("Sjonlàeker", "De 'Sjonug' y 'Laeker', lit. 'Comer al sol'", "Sjon"),
("Grüflàekug", "De 'Grüfug' y 'Laekug', lit. 'Comida de café'", "Grüf"),
("Grüflàeker", "De 'Grüfug' y 'Laeker', lit. 'Comer del café'", "Grüf"),
("Awalàekug", "De 'Awalaj' y 'Laekug', lit. 'Comida de la luna'", "Awal"),
("Awalàeker", "De 'Awalaj' y 'Laeker', lit. 'Comer de la luna'", "Awal"),
("Käjker", "Palabra originante tradicional", "Käjk"),
("Käjkug", "Palabra originante tradicional", "Käjk"),
("Käjkuget", "Lit. 'Corte pequeño'", "Käjkug"),
("Laekäjkfùtaj", "De 'Laekug', 'Käjker' y 'Futaj', lit. 'Herramienta para cortar comida'", "Laek"),
("Dësljar", "Palabra originante tradicional", "Dëslj"),
("Dësljaj", "Palabra originante tradicional", "Dëslj"),
("Dësljkĵgug", "De 'Dësljar' y 'Kjgug', lit. 'edificio para comprar'", "Dëslj"),
("Ünklar", "Palabra originante tradicional", "Ünkl"),
("Ünklaj", "Palabra originante tradicional", "Ünkl"),
("Lujkar", "Palabra originante tradicional", "Lujk"),
("Lujkaj", "Palabra originante tradicional", "Lujk"),
("Lujkajur", "Lit. 'Colectivo de dinero'", "Lujkaj"),
("Lujkeg", "Palabra originante tradicional", "Lujk"),
("Lujkegaf", "Lit. 'Sin riqueza'", "Lujkeg"),
("Lujkegafon", "Lit. 'Sin riqueza grande'", "Lujkeg"),
("Lujkajon", "Lit. 'Dinero grande'", "Lujkaj"),
("Lujkĵgug", "De 'Lujkaj' y 'Kjgug', lit. 'edificio de dinero'", "Lujk"),
("Lujkaurkĵgug", "De 'Lujkaj', 'Aurug' y 'Kjgug', lit. 'edificio de reunión de dinero'", "Lujk"),
("Lujkèfjeg", "De 'Lujkaj' y 'Kefjeg', lit. 'Persona con dinero'", "Lujk"),
("Wajer", "Palabra originante tradicional", "Waj"),
("Wajeg", "Palabra originante tradicional", "Waj"),
("Wajug", "Palabra originante tradicional", "Waj"),
("Wajuget", "Lit. 'Bebé pequeño'", "Wajug"),
("Wajugon", "Lit. 'Bebé grande'", "Wajug"),
("Lajteg", "Palabra originante tradicional", "Lajt"),
("Lajtegaf", "Lit. 'Sin luz'", "Lajteg"),
("Lajtegafer", "Lit. 'Hacer sin luz'", "Lajteg"),
("Kojwgrjnlàjteg", "De 'Kojweg', 'Grjneg' y 'Lajteg', lit. 'Luz verde del cielo'", "Kojw"),
("Kojwlajtsònteg", "De 'Kojweg', 'Lajteg' y 'Sonteg', lit. 'Punto de luz del cielo'", "Kojw"),
("Lajter", "Palabra originante tradicional", "Lajt"),
("Löwj", "Palabra originante tradicional", "Löwj"),
("Löwjeg", "Palabra originante tradicional", "Löwj"),
("Löwjer", "Palabra originante tradicional", "Löwj"),
("Löwjrènder", "De 'Löwjeg' y 'Rënder', lit. 'Resolver con rapidez'", "Löwj"),
("Dünej", "Palabra originante tradicional", "Dünej"),
("Dünejeg", "Palabra originante tradicional", "Dünej"),
("Dünejar", "Palabra originante tradicional", "Dünej"),
("Kälaeg", "Palabra originante tradicional", "Käla"),
("Kälaer", "Palabra originante tradicional", "Käla"),
("Kälaegaf", "Lit. 'Sin movimiento'", "Kälaeg"),
("Kälaegafer", "Lit. 'Hacer sin movimiento'", "Kälaeg"),
("Kälarĵgëlug", "De 'Kälaeg' y 'Rjgëlug', lit. 'Dibujo con movimiento'", "Käla"),
("Kälarjgëlànördnug", "De 'Kälaeg', 'Rjgëlug' y 'Anördnug', lit. 'Máquina de dibujos con movimiento'", "Käla"),
("Kälarjgëlkĵgug", "De 'Kälaeg', 'Rjgëlug' y 'Kjgug', lit. 'edificio de dibujos con movimiento'", "Käla"),
("Kälarjgëlfèjregur", "De 'Kälaeg', 'Rjgëlug' y 'Fëjregur', lit. 'Colectivo de conocimientos de dibujos con movimiento'", "Käla"),
("Frojkàlaer", "De 'Froj' y 'Kälaer', lit. 'Mover aquí'", "Froj"),
("Sjoner", "Palabra originante tradicional", "Sjon"),
("Wajsjòner", "De 'Wajug' y 'Sjoner', lit. 'Solear (un) nacimiento'", "Waj"),
("Wajsjònug", "De 'Wajug' y 'Sjonug', lit. 'Nacimiento soleado'", "Waj"),
("Sjonug", "Palabra originante tradicional", "Sjon"),
("Sjonuget", "Lit. 'Sol pequeño'", "Sjonug"),
("Sjonugon", "Lit. 'Sol grande'", "Sjonug"),
("Awalar", "Palabra originante tradicional", "Awal"),
("Awalaj", "Palabra originante tradicional", "Awal"),
("Awàlajet", "Lit. 'Luna pequeña'", "Awalaj"),
("Awàlajon", "Lit. 'Luna grande'", "Awalaj"),
("Kojweg", "Palabra originante tradicional", "Kojw"),
("Kojwlàedejug", "De 'Kojweg' y 'Laedejug', lit. 'Tierra del cielo'", "Kojw"),
("Tajklàedejug", "De 'Tajkleg' y 'Laedejug', lit. 'Tierra de fuego'", "Tajkl"),
("Kojwjàgar", "De 'Kojweg' y 'Jagar', lit. 'Mojar del cielo'", "Kojw"),
("Kojwjàgaj", "De 'Kojweg' y 'Jagaj', lit. 'Agua del cielo'", "Kojw"),
("Kojwjàgajet", "De 'Kojweg' y 'Jagaj', lit. 'Agua del cielo pequeña'", "Kojwjàgaj"),
("Kojwjàgajon", "De 'Kojweg' y 'Jagaj', lit. 'Agua del cielo grande'", "Kojwjàgaj"),
("Kojwkaenjàgaj", "De 'Kojweg', 'Kaenar' y 'Jagaj', lit. 'Agua enfriada del cielo'", "Kojw"),
("Kojwkaenjàgar", "De 'Kojweg', 'Kaenar' y 'Jagar', lit. 'Mojar enfriado del cielo'", "Kojw"),
("Türajug", "Palabra originante tradicional", "Türaj"),
("Türajuget", "Lit. 'Planeta pequeño'", "Türajug"),
("Türajer", "Palabra originante tradicional", "Türaj"),
("Krjt", "Palabra originante tradicional", "Krjt"),
("Krjtur", "Lit. 'Colectivo de reglas'", "Krjt"),
("Krjton", "Lit. 'Regla grande'", "Krjt"),
("Krjtonur", "Lit. 'Colectivo de reglas grandes'", "Krjt"),
("Krjtar", "Palabra originante tradicional", "Krjt"),
("Ljoner", "Palabra originante tradicional", "Ljon"),
("Ljonaj", "Palabra originante tradicional", "Ljon"),
("Ljoneg", "Palabra originante tradicional", "Ljon"),
("Ljonkèfjeg", "De 'Ljoner' y 'Kefjeg', lit. 'Persona que viaja'", "Ljon"),
("Kojwljonkèfjeg", "De 'Kojweg', 'Ljoner' y 'Kefjeg', lit. 'Persona que viaja en el cielo'", "Kojw"),
("Sjonkòjweg", "De 'Sjonug' y 'Kojweg', lit. 'Cielo con sol'", "Sjon"),
("Sjonknòjar", "De 'Sjonug' y 'Knöjar', lit. 'Subir el sol'", "Sjon"),
("Knöjsjònug", "De 'Knöj' y 'Sjonug', lit. 'Sol arriba'", "Knöj"),
("Awalkòjweg", "De 'Awalaj' y 'Kojweg', lit. 'Cielo con luna'", "Awal"),
("Awalknòjar", "De 'Awalaj' y 'Knöjar', lit. 'Subir la luna'", "Awal"),
("Knöjàwalaj", "De 'Knöj' y 'Awalaj', lit. 'Luna arriba'", "Knöj"),
("Kaenar", "Palabra originante tradicional", "Kaen"),
("Kaeneg", "Palabra originante tradicional", "Kaen"),
("Kaenegaf", "Lit. 'Sin frío'", "Kaeneg"),
("Kaenegafar", "Lit. 'Hacer sin frío'", "Kaeneg"),
("Kaenjàgaj", "De 'Kaeneg' y 'Jagaj', lit. 'Agua con frío'", "Kaen"),
("Kaenjàgar", "De 'Kaeneg' y 'Jagar', lit. 'Hacer agua con frío'", "Kaen"),
("Kaenjàgajon", "De 'Kaenar' y 'Jagaj', lit. 'Agua enfriada grande'", "Kaenjàgaj"),
("Kaenaj", "Palabra originante tradicional", "Kaen"),
("Kaenajet", "Lit. 'Nieve pequeña'", "Kaenaj"),
("Kaenajon", "Lit. 'Nieve grande'", "Kaenaj"),
("Balaner", "Palabra originante tradicional", "Balan"),
("Balanug", "Palabra de patrimonio nacional", "Balan"),
("Wajsjonlàedenug", "De 'Wajug', 'Sjonug' y 'Laedenug', lit. 'País del sol naciente'", "Waj"),
("Frjwgorjölàedenug", "De 'Frjweg', 'Gorjö' y 'Laedenug', lit. 'País de Goryeo del sur'", "Frjw"),
("Føjlgorjölàedenug", "De 'Føjleg', 'Gorjö' y 'Laedenug', lit. 'País de Goryeo del norte'", "Føjl"),
("Sølwlàedenug", "De 'Sølweg' y 'Laedenug', lit. 'País plateado'", "Sølw"),
("Dawegegaflàedenugen", "De 'Dawegegaf' y 'Laedenugen', lit. 'Países sin altura'", "Daweg"),
("Swjarlàedenug", "De 'Swjarön' y 'Laedenug', lit. 'País de los suiones'", "Swjar"),
("Saanjlàedenug", "De 'Saanj' y 'Laedenug', lit. 'País de los lapones'", "Saanj"),
("Føjljonlàedenug", "De 'Føjleg', 'Ljonaj' y 'Laedenug', lit. 'País del camino al norte'", "Føjl"),
("Rüsslàedenug", "De 'Rüss' y 'Laedenug', lit. 'País de los rus' (o rusy)'", "Rüss"),
("Frjwslawjlàedenug", "De 'Frjweg', 'Slawjö' y 'Laedenug', lit. 'País de eslavos del sur'", "Frjw"),
("Balanlàedenug", "Palabra de patrimonio nacional, de 'Balanug' y 'Laedenug', lit. 'País del equilibrio'", "Balan"),
("Tënter", "Palabra originante tradicional", "Tënt"),
("Tënteg", "Palabra originante tradicional", "Tënt"),
("Knuwergùwler", "De 'Knuwereg' y 'Güwler', lit. 'Combinar números'", "Knuwer"),
("Knuwergùwlug", "De 'Knuwereg' y 'Güwlug', lit. 'Combinación de números'", "Knuwer"),
("Knuwertènter", "De 'Knuwereg' y 'Tënter', lit. 'Incrementar números'", "Knuwer"),
("Knuwertènteg", "De 'Knuwereg' y 'Tënteg', lit. 'Incremento de números'", "Knuwer"),
("Knuwereg", "Palabra originante tradicional", "Knuwer"),
("Knuwerer", "Palabra originante tradicional", "Knuwer"),
("Knuwerfèjregur", "De 'Knuwereg' y 'Fëjregur', lit. 'Colectivo de conocimientos de números'", "Knuwer"),
("Knuwerfùtaj", "De 'Knuwer' y 'Futaj', lit. 'Herramienta de números'", "Knuwer"),
("Laekfùtaj", "De 'Laeker' y 'Futaj', lit. 'Herramienta para comer'", "Laek"),
("Laekfèjregur", "De 'Laekug' y 'Fëjregur', lit. 'Colectivo de conocimientos de comida'", "Laek"),
("Knuwerànördnug", "De 'Knuwer' y 'Anördnug', lit. 'Máquina de números'", "Knuwer"),
("Berätfèjregur", "De 'Beräteg' y 'Fëjregur', lit. 'Colectivo de conocimientos de historias'", "Berät"),
("Ljngfèjregur", "De 'Ljngeg' y 'Fëjregur', lit. 'Colectivo de conocimientos de idioma'", "Ljng"),
("Kajfutfèjregur", "De 'Kaj', 'Futeg' y 'Fëjreg', lit. 'Colectivo de conocimientos de cosas que viven'", "Kajfutfèjreg"),
("Wänkèfjeg", "De 'Wän' y 'Kefjeg', lit. 'Una persona'", "Wän"),
("Wän", "Palabra originante tradicional", "Wän"),
("Tö", "Palabra originante tradicional", "Tö"),
("Tökan", "Palabra originante tradicional", "Tö"),
("Trj", "Palabra originante tradicional", "Trj"),
("Fjr", "Palabra originante tradicional", "Fjr"),
("Fajw", "Palabra originante tradicional", "Fajw"),
("Seks", "Palabra originante tradicional", "Seks"),
("Sjwe", "Palabra originante tradicional", "Sjwe"),
("Ëjwt", "Palabra originante tradicional", "Ëjwt"),
("Knjw", "Palabra originante tradicional", "Knjw"),
("Tjö", "Palabra originante tradicional", "Tjö"),
("Anküj", "Palabra originante tradicional", "Anküj"),
("Tondräj", "Palabra originante tradicional", "Tondräj"),
("Frasäj", "Palabra originante tradicional", "Frasäj"),
("Ä", "Palabra originante tradicional", "Ä"),
("Äej", "De 'Ä' y 'Waej'", "Ä"),
("Ägj", "Palabra originante tradicional", "Ägj"),
("Bulöw", "Palabra originante tradicional", "Bulöw"),
("Tör", "Palabra originante tradicional", "Tör"),
("Grej", "Palabra originante tradicional", "Grej"),
("Tjl", "Palabra originante tradicional", "Tjl"),
("Tjlaej", "De 'Tjl' y 'Waej'", "Tjl"),
("Sjng", "Palabra originante tradicional", "Sjng"),
("Trësjaw", "Palabra originante tradicional", "Trësjaw"),
("Wjl", "Palabra originante tradicional", "Wjl"),
("Wjlaej", "De 'Wjl' y 'Waej'", "Wjl"),
("Bjtbjn", "Palabra originante tradicional", "Bjtbjn"),
("Töwar", "Palabra originante tradicional", "Töwar"),
("Ätej", "Palabra originante tradicional", "Ätej"),
("Tröuw", "Palabra originante tradicional", "Tröuw"),
("Faer", "Palabra originante tradicional", "Faer"),
("För", "Palabra originante tradicional", "För"),
("Föraej", "De 'För' y 'Waej'", "För"),
("Bäsel", "Palabra originante tradicional", "Bäsel"),
("Ütan", "Palabra originante tradicional", "Ütan"),
("Kjøne", "Palabra originante tradicional", "Kjøne"),
("Bëjand", "Palabra originante tradicional", "Bëjand"),
("Öl", "Palabra originante tradicional", "Öl"),
("Kon", "Palabra originante tradicional", "Kon"),
("Kjae", "Palabra originante tradicional", "Kjae"),
("Ölugen", "Palabra originante tradicional", "Öl"),
("Ölajn", "Palabra originante tradicional", "Öl"),
("Ölegen", "Palabra originante tradicional", "Öl"),
("Konugen", "Palabra originante tradicional", "Kon"),
("Konajn", "Palabra originante tradicional", "Kon"),
("Konegen", "Palabra originante tradicional", "Kon"),
("Kjaeugen", "Palabra originante tradicional", "Kjae"),
("Kjaejn", "Palabra originante tradicional", "Kjae"),
("Kjaegen", "Palabra originante tradicional", "Kjae"),
("Waej", "Palabra originante tradicional", "Waej"),
("Knaej", "Palabra originante tradicional", "Knaej"),
("Knaejuj", "Palabra originante tradicional", "Knaej"),
("Knaejteg", "De 'Knaej' y 'Futeg'", "Knaej"),
("Knaejteged", "De 'Knaej' y 'Futeged'", "Knaej"),
("Knaejfjeg", "De 'Knaej' y 'Kefjeg'", "Knaej"),
("Knaejfjeged", "De 'Knaej' y 'Kefjeged'", "Knaej"),
("Klaej", "Palabra originante tradicional", "Klaej"),
("Traej", "Palabra originante tradicional", "Traej"),
("Ëgwej", "De 'Ëgael' y 'Käswej'", "Ëgael"),
("Tänksakon", "De 'Tänkser', 'Ä' y 'Kon'", "Tänks"),
("Jäk", "Sonido con significado verbal", "Jäk"),
("Tajseg", "Palabra originante tradicional", "Tajs"),
("Fändjleges", "Lit. 'Relativo a final'", "Fändjleg"),
("Tajser", "Palabra originante tradicional", "Tajs"),
("Tajseges", "Lit. 'Relativo a esperanza'", "Tajseg"),
("Tajsegaf", "Lit. 'Sin esperanza'", "Tajseg"),
("Fajlaj", "Palabra originante tradicional", "Fajl"),
("Glajsug", "Palabra originante tradicional", "Glajs"),
("Fajlajes", "Lit. 'Relativo a vulva'", "Fajlaj"),
("Glajsuges", "Lit. 'Relativo a pene'", "Glajsug"),
("Wenkegetar", "Lit. 'Hacer igualdad pequeña'", "Wenkeg"),
("Knjfajeges", "Lit. 'Relativo a naturaleza'", "Knjfajeg"),
("Ëselar", "Palabra originante tradicional", "Ësel"),
("Ëseleg", "Palabra originante tradicional", "Ësel"),
("Ëseleget", "Lit. 'Toque pequeño'", "Ëseleg"),
("Ëselegetar", "Lit. 'Hacer toque pequeño'", "Ëseleg"),
("Dönjleges", "Lit. 'Relativo a salud'", "Dönjleg"),
("Dönjlajes", "Lit. 'Relativo a cura'", "Dönjlaj"),
("Wenkegetes", "Lit. 'Relativo a igualdad pequeña'", "Wenkeg"),
("Wenkegetaf", "Lit. 'Sin igualdad pequeña'", "Wenkeg"),
("Wenkegetafes", "Lit. 'Relativo a sin igualdad pequeño'", "Wenkeg"),
("Wenkegafes", "Lit. 'Relativo a sin igualdad'", "Wenkeg"),
("Wöjleges", "Lit. 'Relativo a placer'", "Wöjleg"),
("Wöjlegafes", "Lit. 'Relativo a sin placer'", "Wöjleg"),
("Dönjlajafes", "Lit. 'Relativo a sin cura'", "Dönjlaj"),
("Fresteg", "Palabra originante tradicional", "Frest"),
("Frester", "Palabra originante tradicional", "Frest"),
("Kjaeug", "Palabra originante tradicional", "Kjae"),
("Kjaej", "Palabra originante tradicional", "Kjae"),
("Tägkèfjeg", "De 'Tägeg' y 'Kefjeg', lit. 'Persona con posesión'", "Täg"),
("Krendaj", "Palabra originante tradicional", "Krend"),
("Krendug", "Palabra originante tradicional", "Krend"),
("Knaweges", "Lit. 'Relativo a muerte'", "Knaweg"),
("Fosteges", "Lit. 'Relativo a delgadez'", "Fosteg"),
("Fostegones", "Lit. 'Relativo a delgadez grande'", "Fosteg"),
("Luwug", "Palabra originante tradicional", "Luw"),
("Lajteges", "Lit. 'Relativo a luz'", "Lajteg"),
("Lajtegafes", "Lit. 'Relativo a sin luz'", "Lajteg"),
("Kälaeges", "Lit. 'Relativo a movimiento'", "Kälaeg"),
("Kälaegafes", "Lit. 'Relativo a sin movimiento'", "Kälaeg"),
("Luwer", "Palabra originante tradicional", "Luw"),
("Kaeneges", "Lit. 'Relativo a frío'", "Kaeneg"),
("Kaenegafes", "Lit. 'Relativo a sin frío'", "Kaeneg"),
("Kefjsèjnteg", "De 'Kefjeg' y 'Sëjnteg', lit. 'Unicidad de persona'", "Kefj"),
("Lujkeges", "Lit. 'Relativo a riqueza'", "Lujkeg"),
("Lujkegon", "Lit. 'Riqueza grande'", "Lujkeg"),
("Lujkegones", "Lit. 'Relativo a riqueza grande'", "Lujkeg"),
("Lujkegafes", "Lit. 'Relativo a sin riqueza'", "Lujkeg"),
("Lujkegafones", "Lit. 'Relativo a sin riqueza grande'", "Lujkeg"),
("Lajtegafet", "Lit. 'Sin luz pequeña'", "Lajteg"),
("Luwuges", "Lit. 'Relativo a huevo'", "Luwug"),
("Kefjeges", "Lit. 'Relativo a persona'", "Kefjeg"),
("Öndugurkèfjeg", "De 'Öndugur' y 'Kefjeg', lit. 'Persona de barrio'", "Önd"),
("Enäjeges", "Lit. 'Relativo a bondad'", "Enäjeg"),
("Färaleges", "Lit. 'Relativo a maldad'", "Färaleg"),
("Kefjeguron", "Lit. 'Colectivo de personas grande'", "Kefjeg"),
("Fönleges", "Lit. 'Relativo a símbolo'", "Fönleg"),
("Wjndleges", "Lit. 'Relativo a viento'", "Wjndleg"),
("Kefjeguret", "Lit. 'Colectivo de personas pequeño'", "Kefjeg"),
("Daljajes", "Lit. 'Relativo a verdad'", "Daljaj"),
("Daljajafes", "Lit. 'Relativo a sin verdad'", "Daljaj"),
("Dünejeges", "Lit. 'Relativo a lentitud'", "Dünejeg"),
("Awalajes", "Lit. 'Relativo a luna'", "Awalaj"),
("Balanuges", "Lit. 'Relativo a equilibrio'", "Balanug"),
("Balanugaf", "Lit. 'Sin equilibrio'", "Balanug"),
("Balanugafes", "Lit. 'Relativo a sin equilibrio'", "Balanug"),
("Bejnajes", "Lit. 'Relativo a limpieza'", "Bejnaj"),
("Bejnajafes", "Lit. 'Relativo a sin limpieza'", "Bejnaj"),
("Bjseleges", "Lit. 'Relativo a aire'", "Bjseleg"),
("Bljuneges", "Lit. 'Relativo a belleza'", "Bljuneg"),
("Bljunegafes", "Lit. 'Relativo a sin belleza'", "Bljuneg"),
("Blöduges", "Lit. 'Relativo a sangre'", "Blödug"),
("Bëndjleges", "Lit. 'Relativo a inicio'", "Bëndjleg"),
("Dësljkèfjeg", "De 'Dësljar' y 'Kefjeg', lit. 'Persona que compra'", "Dëslj"),
("Enljeges", "Lit. 'Relativo a juventud'", "Enljeg"),
("Enljegafes", "Lit. 'Relativo a sin juventud'", "Enljeg"),
("Ertjer", "Palabra originante tradicional'", "Ertj"),
("Ertjegafer", "Lit. 'Hacer sin paciencia'", "Ertjeg"),
("Blödùrnuges", "De 'Blödug' y 'Ürnug', lit. 'Relativo a órgano de sangre'", "Blödùrnug"),
("Rjntèfjaj", "De 'Rjnlug' y 'Tëfjaj', lit. 'Capa de cuerpo'", "Rjnl"),
("Fajwes", "Lit. 'Relativo a cinco'", "Fajw"),
("Ëjwtes", "Lit. 'Relativo a ocho'", "Ëjwt"),
("Denokrätĵaes", "Lit. 'Relativo a democracia'", "Denokrätĵa"),
("Wleteg", "Palabra originante tradicional", "Wlet"),
("Wleter", "Palabra originante tradicional", "Wlet"),
("Wletegaf", "Lit. 'Sin respeto'", "Wleteg"),
("Wletegafer", "Lit. 'Hacer sin respeto'", "Wleteg"),
("Wleteges", "Lit. 'Relativo a respeto'", "Wleteg"),
("Wletegafes", "Lit. 'Relativo a sin respeto'", "Wleteg"),
("Luwùlejtug", "De 'Luwer' y 'Wülejtug', lit. 'Animal que ova'", "Luw"),
("Ënskjegaf", "Lit. 'Sin uso'", "Ënskjeg"),
("Fjalajes", "Lit. 'Relativo a bebida'", "Fjalaj"),
("Fjres", "Lit. 'Relativo a cuatro'", "Fjr"),
("Gërtug", "Palabra originante tradicional", "Gërt"),
("Fenseges", "Lit. 'Relativo a aprendizaje'", "Fenseg"),
("Fatjgeges", "Lit. 'Relativo a destino'", "Fatjgeg"),
("Frejar", "Palabra originante tradicional", "Frej"),
("Frejegafar", "Lit. 'Hacer sin facilidad'", "Frejeg"),
("Fresteges", "Lit. 'Relativo a entusiasmo'", "Fresteg"),
("Frëteges", "Lit. 'Relativo a intento'", "Frëteg"),
("Fëjreges", "Lit. 'Relativo a conocimiento'", "Fëjreg"),
("Fändjlegafes", "Lit. 'Relativo a sin final'", "Fändjlegaf"),
("Fejfuges", "Lit. 'Relativo a texto'", "Fejfug"),
("Rogkèfjeg", "De 'Rogler' y 'Kefjeg', lit. 'Persona que regala'", "Rogl"),
("Golunùrnuges", "De 'Golunar' y 'Ürnug', lit. 'Relativo a órgano para degustar'", "Golunùrnug"),
("Jagajes", "Lit. 'Relativo a agua'", "Jagaj"),
("Jagajures", "Lit. 'Relativo a colectivo de agua'", "Jagaj"),
("Jageges", "Lit. 'Relativo a hidratación'", "Jageg"),
("Jagegafes", "Lit. 'Relativo a sin hidratación'", "Jageg"),
("Jagegaflàedejuges", "De 'Jagegaf' y 'Laedejug', lit. 'Relativo a tierra sin hidratación'", "Jagegaflàedejug"),
("Jagneges", "Lit. 'Relativo a vivo'", "Jagneg"),
("Jagàjurones", "Lit. 'Relativo a colectivo grande de agua'", "Jagaj"),
("Jagajones", "Lit. 'Relativo a agua grande'", "Jagaj"),
("Jaglĵneges", "De 'Jagaj' y 'Ljneg', lit. 'Relativo a línea de agua'", "Jaglĵneg"),
("Jaglàedejuges", "De 'Jagaj' y 'Laedejug', lit. 'Relativo a tierra con agua'", "Jaglàedejug"),
("Jagbĵseleges", "De 'Jagaj' y 'Bjseleg', lit. 'Relativo a aire con agua'", "Jagbĵseleg"),
("Jagwĵkolaj", "De 'Jagar' y 'Wjkolaj', lit. 'Acción de la boca para mojar'", "Jag"),
("Jgjaegetes", "Lit. 'Relativo a año pequeño'", "Jgjaeg"),
("Kjltajes", "Lit. 'Relativo a leche'", "Kjltaj"),
("Klënuges", "Lit. 'Relativo a entendimiento'", "Klënug"),
("Knjfajegaf", "Lit. 'Sin naturaleza'", "Knjfajeg"),
("Knjfajegafes", "Lit. 'Relativo a sin naturaleza'", "Knjfajeg"),
("Flajkeg", "Palabra originante tradicional", "Flajk"),
("Flajkeges", "Lit. 'Relativo a anterioridad'", "Flajkeg"),
("Awalblòdug", "De 'Awalaj' y 'Blödug', lit. 'Sangre de luna'", "Awal"),
("Awalblòder", "De 'Awalaj' y 'Blöder', lit. 'Sangrar de la luna'", "Awal"),
("Frjwlàedenug", "De 'Frjweg' y 'Laedenug', lit. 'País del sur'", "Frjw"),
("Tujkneg", "Palabra originante tradicional", "Tujkn"),
("Tujkneges", "Lit. 'Relativo a posterioridad'", "Tujkneg"),
("Türajuges", "Lit. 'Relativo a mundo'", "Türajug"),
("Klëk", "Palabra originante tradicional", "Klëk"),
("Klausdàj", "De 'Klaus (nombre)' y 'Daj', lit. 'Día de Klaus'", "Klaus"),
("Kjgkojwàsteg", "De 'Kjgug', 'Kojweg' y 'Wasteg', lit. 'Vista de cielo de edificio'", "Kjg"),
("Wonajeg", "Palabra originante tradicional", "Wonaj"),
("Wonajer", "Palabra originante tradicional", "Wonaj"),
("Wonajegon", "Lit 'Enojo grande'", "Wonajeg"),
("Wonajegoner", "Lit 'Hacer enojo grande'", "Wonajeg"),
("Wonajeges", "Lit. 'Relativo a enojo'", "Wonajeg"),
("Wonajegones", "Lit. 'Relativo a enojo grande'", "Wonajeg"),
("Balandàj", "De 'Balanug' y 'Daj', lit. 'Día de equilibrio'", "Balan"),
("Kunstaj", "Palabra originante tradicional", "Kunst"),
("Kunstar", "Palabra originante tradicional", "Kunst"),
("Kunsteg", "Palabra originante tradicional", "Kunst"),
("Kunstajes", "Lit. 'Relativo a madera'", "Kunstaj"),
("Franklàedenug", "De 'Frank' y 'Laedenug', lit. 'País de los francos'", "Frank"),
("Kürkaj", "Palabra originante tradicional", "Kürk"),
("Erjulàedenug", "De 'Erju' y 'Laedenug', lit. 'País de los ériu (fértiles)'", "Erju"),
("Wjtrüsslàedenug", "De 'Wjteg', 'Rüss' y 'Laedenug', lit. 'País de los rus blancos'", "Wjt"),
("Alämanlàedenug", "De 'Alämanni' y 'Laedenug', lit. 'País de los alemanes (los hombres, el pueblo)'", "Aläman"),
("Ljuwar", "Palabra originante tradicional", "Ljuw"),
("Ljuweg", "Palabra originante tradicional", "Ljuw"),
("Ljuweges", "Lit. 'Relativo a unión'", "Ljuweg"),
("Ljngeget", "Lit. 'Idioma pequeño'", "Ljngeg"),
("Kürkajet", "Lit. 'Isla pequeña'", "Kürkaj"),
("Gërtkrĵton", "De 'Gërtaj' y 'Krjton', lit. 'Ley de Gran Duquesa'", "Gërt"),
("Kerjter", "Palabra originante tradicional", "Kerjt"),
("Kerjtug", "Palabra originante tradicional", "Kerjt"),
("Kerjtkèfjeg", "De 'Kerjter' y 'Kefjeg', lit. 'Persona que escapa'", "Kerjt"),
("Gaelwajes", "Lit. 'Relativo a vuelo'", "Gaelwaj"),
("Gaelwùlejtuges", "Lit. 'Relativo a animal que vuela'", "Gaelwùlejtug"),
("Gjldtòwlajuges", "Lit. 'Relativo a metal dorado'", "Gjldtòwlajug"),
("Grüfuges", "Lit. 'Relativo a café'", "Grüfug"),
("Göwelfèjfeg", "De 'Göwelaj' y 'Fejfeg', lit. 'Palabra de memoria'", "Göwel"),
("Göwelsfàejugafes", "Lit. 'Relativo a sin capacidad de recordar'", "Göwelsfàejug"),
("Jönuges", "Lit. 'Relativo a continuación'", "Jönug"),
("Jönugafes", "Lit. 'Relativo a sin continuación'", "Jönug"),
("Kajeges", "Lit. 'Relativo a existencia'", "Kajeg"),
("Kajegaf", "Lit. 'Sin existencia'", "Kajeg"),
("Kajegafes", "Lit. 'Relativo a sin existencia'", "Kajeg"),
("Kefjegetes", "Lit. 'Relativo a persona pequeña'", "Kefjeg"),
("Kefjànördnuges", "Lit. 'Relativo a máquina de persona'", "Kefjànördnug"),
("Kerjtwejkrjnkèfjeg", "De 'Kerjtug', 'Wejkrjneg' y 'Kefjeg', lit. 'Persona con delito de escape'", "Kerjt"),
("Kjaes", "Lit. 'Relativo a él/ella'", "Kjae"),
("Kjaegenes", "Lit. 'Relativo a ellos/ellas'", "Kjaegen"),
("Kjaejes", "Lit. 'Relativo a ella'", "Kjaej"),
("Kjaejnes", "Lit. 'Relativo a ellas'", "Kjaejn"),
("Kjaeuges", "Lit. 'Relativo a él'", "Kjaeug"),
("Kjaeugenes", "Lit. 'Relativo a ellos'", "Kjaeugen"),
("Knawsfàejuges", "Lit. 'Relativo a capacidad de morir'", "Knawsfàejug"),
("Knawsfàejugafes", "Lit. 'Relativo a sin capacidad de morir'", "Knawsfàejug"),
("Tökèfjeg", "De 'Tö' y 'Kefjeg', lit. 'Persona de dos'", "Tö"),
("Tänskĵgug", "De 'Tänsteg' y 'Kjgug', lit. 'edificio de trabajo'", "Tänst"),
("Knotuges", "Lit. 'Relativo a canto'", "Knotug"),
("Knjfajkèfjeg", "De 'Knjfajeg' y 'Kefjeg', lit. 'Persona con naturaleza'", "Knjfaj"),
("Knjfajkèfjeges", "Lit. 'Relativo a persona con naturaleza'", "Knjfajkèfjeg"),
("Töesknotkèfjeg", "De 'Töes', 'Knotug' y 'Kefjeg', lit. 'Persona con canto relativo a dos'", "Tö"),
("Kaenjagöndkĵgug", "De 'Kaeneg', 'Jagaj', 'Öndug' y 'Kjgug', lit. 'edificio de vivienda de agua con frío'", "Kaen"),
("Knuwereges", "Lit. 'Relativo a número'", "Knuwereg"),
("Knöjajes", "Lit. 'Relativo a subida'", "Knöjaj"),
("Kojweges", "Lit. 'Relativo a cielo'", "Kojweg"),
("Kojwjàgajes", "Lit. 'Relativo a agua del cielo'", "Kojwjàgaj"),
("Kojwkèfjeges", "Lit. 'Relativo a persona del cielo'", "Kojwkèfjeg"),
("Knüskugen", "De 'Knaej' y 'Üskug' (en plural)", "Knaej"),
("Kojwlajtsònteges", "Lit. 'Relativo a punto de luz del cielo'", "Kojwlajtsònteg"),
("Kojwlàedejuges", "Lit. 'Relativo a tierra del cielo'", "Kojwlàedejug"),
("Kokolàtes", "Lit. 'Relativo a chocolate'", "Kokolàt"),
("Kones", "Lit. 'Relativo a tú/vos'", "Kon"),
("Konajnes", "Lit. 'Relativo a ustedes (todas mujeres)'", "Konajn"),
("Konegenes", "Lit. 'Relativo a ustedes (géneros mixtos)'", "Konegen"),
("Konugenes", "Lit. 'Relativo a ustedes (todos hombres)'", "Konugen"),
("Krjtes", "Lit. 'Relativo a regla'", "Krjt"),
("Krjtonkèfjeg", "De 'Krjton' y 'Kefjeg', lit. 'Persona de regla grande'", "Krjt"),
("Krjtkèfjeg", "De 'Krjt' y 'Kefjeg', lit. 'Persona de regla'", "Krjt"),
("Käjkuges", "Lit. 'Relativo a corte'", "Käjkug"),
("Kördajes", "Lit. 'Relativo a cordura'", "Kördaj"),
("Kördajafes", "Lit. 'Relativo a sin cordura'", "Kördaj"),
("Kürkajes", "Lit. 'Relativo a isla'", "Kürkaj"),
("Laedejuges", "Lit. 'Relativo a tierra'", "Laedejug"),
("Dönjlkĵgug", "De 'Dönjlaj' y 'Kjgug', lit. 'edificio de cura'", "Dönjl"),
("Futegur", "Lit. 'Colectivo de cosas'", "Futeg"),
("Laedenuges", "Lit. 'Relativo a país/Estado'", "Laedenug"),
("Laedenkèfjegures", "Lit. 'Relativo a colectivo de personas de país'", "Laedenkèfjeg"),
("Üntjeg", "Palabra originante tradicional", "Üntj"),
("Üntjar", "Palabra originante tradicional", "Üntj"),
("Üntjeges", "Lit. 'Relativo a liviandad'", "Üntjeg"),
("Üntjegaf", "Lit. 'Sin liviandad'", "Üntjeg"),
("Üntjegafes", "Lit. 'Relativo a sin liviandad'", "Üntjeg"),
("Kröndwaj", "Palabra de patrimonio nacional", "Kröndw"),
("Sljntaj", "Palabra originante tradicional", "Sljnt"),
("Sljntar", "Palabra originante tradicional", "Sljnt"),
("Gërflegetlàedenug", "De 'Gërfleget' y 'Laedenug', lit. 'País pequeño'", "Gërfl"),
("Gërflegetlàedenuges", "Lit. 'Relativo a país pequeño'", "Gërflegetlàedenug"),
("Sljnteg", "Palabra originante tradicional", "Sljnt"),
("Jagsljntkèfjeg", "De 'Jagaj', 'Sljntar' y 'Kefjeg', lit. 'Persona que salva en el agua'", "Jag"),
("Sljnteges", "Lit. 'Relativo a salvación'", "Sljnteg"),
("Trëk", "Palabra originante tradicional", "Trëk"),
("Trëkeg", "Palabra originante tradicional", "Trëk"),
("Trëkeges", "Lit. 'Relativo a evitación'", "Trëkeg"),
("Kronaj", "Palabra originante tradicional", "Kron"),
("Gërtkrònaj", "Palabra de patrimonio nacional", "Gërt"),
("Drëleg", "Palabra originante tradicional", "Drël"),
("Drël", "Palabra originante tradicional", "Drël"),
("Drëleges", "Lit. 'Relativo a espera'", "Drëleg"),
("Fjsljwenkèfjeg", "De 'Fjsljeg', 'Wenkeg' y 'Kefjeg', lit. 'Persona con igualdad con cercanía'", "Fjslj"),
("Wasteges", "Lit. 'Relativo a mirada'", "Wasteg"),
("Wastùrnuges", "De 'Wasteg' y 'Ürnug', lit. 'Relativo a órgano de vista'", "Wast"),
("Jrtjseg", "Palabra originante tradicional", "Jrtjs"),
("Jrtjsar", "Palabra originante tradicional", "Jrtjs"),
("Jrtjseges", "Lit. 'Relativo a comodidad'", "Jrtjseg"),
("Jrtjsegaf", "Lit. 'Sin comodidad'", "Jrtjseg"),
("Jrtjsegafar", "Lit. 'Hacer sin comodidad'", "Jrtjseg"),
("Jrtjsegafes", "Lit. 'Relativo a sin comodidad'", "Jrtjseg"),
("Rägteg", "Palabra originante tradicional", "Rägt"),
("Rägter", "Palabra originante tradicional", "Rägt"),
("Rägteges", "Lit. 'Relativo a longitud'", "Rägteg"),
("Rägteget", "Lit. 'Longitud pequeña'", "Rägteg"),
("Rägtegeter", "Lit. 'Hacer longitud pequeña'", "Rägteg"),
("Rägtegetes", "Lit. 'Relativo a longitud pequeña'", "Rägteg"),
("Rägtegon", "Lit. 'Longitud grande'", "Rägteg"),
("Rägtegones", "Lit. 'Relativo a longitud grande'", "Rägteg"),
("Rägtegoner", "Lit. 'Hacer longitud grande'", "Rägteg"),
("Fejfeget", "Lit. 'Palabra pequeña'", "Fejfeg"),
("Fejfegetar", "Lit. 'Hacer palabra pequeña'", "Fejfeg"),
("Dejtugur", "Lit. 'Colectivo de letras'", "Dejtug"),
("Flajkar", "Palabra originante tradicional", "Flajk"),
("Fljnug", "Palabra originante tradicional", "Fljn"),
("Fljnuges", "Lit. 'Relativo a mano'", "Fljnug"),
("Fljner", "Palabra originante tradicional", "Fljn"),
("Fljnfèjfar", "De 'Fljnug' y 'Fejfar', lit. 'Escribir con mano'", "Fljn"),
("Fejfaj", "Palabra originante tradicional", "Fejf"),
("Fljnfèjfaj", "De 'Fljnug' y 'Fejfaj', lit. 'Escritura con mano'", "Fljn"),
("Kästar", "Palabra originante tradicional", "Käst"),
("Kästaj", "Palabra originante tradicional", "Käst"),
("Kästakon", "De 'Kästar', 'Ä' y 'Kon'", "Käst"),
("Kästajes", "Lit. 'Relativo a saludo'", "Kästaj"),
("Brjndeg", "Palabra originante tradicional", "Brjnd"),
("Brjndar", "Palabra originante tradicional", "Brjnd"),
("Brjndeges", "Lit. 'Relativo a importancia'", "Brjndeg"),
("Brjndegaf", "Lit. 'Sin importancia'", "Brjndeg"),
("Brjndegafar", "Lit. 'Hacer sin importancia'", "Brjndeg"),
("Brjndegafes", "Lit. 'Relativo a sin importancia'", "Brjndeg"),
("Oktrjeg", "Palabra originante tradicional", "Oktrj"),
("Oktrjer", "Palabra originante tradicional", "Oktrj"),
("Oktrjeges", "Lit. 'Relativo a cantidad'", "Oktrjeg"),
("Oktrjeget", "Lit. 'Cantidad pequeña'", "Oktrjeg"),
("Oktrjegetes", "Lit. 'Relativo a cantidad pequeña'", "Oktrjeg"),
("Oktrjegeter", "Lit. 'Hacer cantidad pequeña'", "Oktrjeg"),
("Oktrjegon", "Lit. 'Cantidad grande'", "Oktrjeg"),
("Oktrjegones", "Lit. 'Relativo a cantidad grande'", "Oktrjeg"),
("Oktrjegoner", "Lit. 'Hacer cantidad grande'", "Oktrjeg"),
("Läjrkĵguges", "De 'Läjreg' y 'Kjgug', lit. 'Relativo a edificio de educación'", "Läjrkĵgug"),
("Sjfjeges", "Lit. 'Relativo a tiempo'", "Sjfjeg"),
("Tërfòr", "Palabra originante tradicional", "Tërfòr"),
("Kjgug", "Palabra originante tradicional", "Kjg"),
("Kjguges", "Lit. 'Relativo a edificio'", "Kjgug"),
("Grentug", "Palabra originante tradicional", "Grent"),
("Grenter", "Palabra originante tradicional", "Grent"),
("Grenteg", "Palabra originante tradicional", "Grent"),
("Grentànördnug", "De 'Grenter' y 'Anördnug', lit. 'Dispositivo para ubicar'", "Grent"),
("Tenkar", "Palabra originante tradicional", "Tenk"),
("Tenkeg", "Palabra originante tradicional", "Tenk"),
("Tenkegaf", "Lit. 'Sin colocación'", "Tenkeg"),
("Tenkegafar", "Lit. 'Hacer sin colocación'", "Tenkeg"),
("Glöntug", "Palabra originante tradicional", "Glönt"),
("Wjkoglòntug", "De 'Wjkolaj' y 'Glöntug', lit. 'Hueso de boca'", "Wjkol"),
("Wjkoglöntkèfjeg", "De 'Wjkolaj', 'Glöntug' y 'Kefjeg', lit. 'Persona de hueso de boca'", "Wjkol"),
("Wjkoglöntfèjregur", "De 'Wjkolaj', 'Glöntug' y 'Fëjreg', lit. 'Colectivo de conocimientos de hueso de boca'", "Wjkoglöntfèjreg"),
("Wjkoglòntugur", "De 'Wjkolaj' y 'Glöntug', lit. 'Colectivo de huesos de boca'", "Wjkoglòntug"),
("Wjkoglòntuges", "De 'Wjkolaj' y 'Glöntug', lit. 'Relativo a hueso de boca'", "Wjkoglòntug"),
("Glöntuges", "Lit. 'Relativo a hueso'", "Glöntug"),
("Glöntugur", "Lit. 'Colectivo de huesos'", "Glöntug"),
("Glöntugures", "Lit. 'Relativo a colectivo de huesos'", "Glöntug"),
("Awalblòduges", "Lit. 'Relativo a sangre de luna'", "Awalblòdug"),
("Awalkòjweges", "Lit. 'Relativo a cielo de luna'", "Awalkòjweg"),
("Këngwùnelar", "De 'Këngtan' y 'Wünelar', lit. 'Respirar afuera'", "Këngt"),
("Këngwùnelaj", "De 'Këngtan' y 'Wünelaj', lit. 'Respiración afuera'", "Këngt"),
("Räntug", "Palabra originante tradicional", "Ränt"),
("Ränt", "Palabra originante tradicional", "Ränt"),
("Räntuges", "Lit. 'Relativo a búsqueda'", "Räntug"),
("Räntkèfjeg", "De 'Ränt' y 'Kefjeg', lit. 'Persona que busca/investiga'", "Ränt"),
("Jujeg", "Palabra originante tradicional", "Juj"),
("Wenkegafar", "Lit. 'Hacer sin igualdad'", "Wenkeg"),
("Tajkòjweg", "De 'Tajkleg' y 'Kojweg', lit. 'Cielo con fuego'", "Tajkl"),
("Türajugur", "Lit. 'Colectivo de planetas'", "Türajug"),
("Kälkojwlajtsònteg", "De 'Kälaeg', 'Kojweg', 'Lajteg' y 'Sonteg', lit. 'Punto de luz del cielo con movimiento'", "Käla"),
("Lënkug", "Palabra originante tradicional", "Lënk"),
("Jagegaflènkug", "De 'Jagegaf' y 'Lënkug', lit. 'Fruto sin agua'", "Jag"),
("Lënkuges", "Lit. 'Relativo a fruta'", "Lënkug"),
("Kälakonpjùter", "De 'Kälaeg' y 'Konpjùter', lit. 'Computadora con movimiento'", "Käla"),
("Wjwjtajes", "Lit. 'Relativo a sal'", "Wjwjtaj"),
("Drjn", "Palabra originante tradicional", "Drjn"),
("Drjnug", "Palabra originante tradicional", "Drjn"),
("Drjnuges", "Lit. 'Relativo a acierto'", "Drjnug"),
("Drjnugaf", "Lit. 'Sin acierto'", "Drjnug"),
("Drjnugafer", "Lit. 'Hacer sin acierto'", "Drjnug"),
("Drjnugafes", "Lit. 'Relativo a sin acierto'", "Drjnug"),
("Käkerlass", "Palabra adoptada artificialmente del sueco 'Kackerlacka'", "Käkerlass"),
("Oj", "Sonido con significado verbal", "Oj"),
("Traewflĵner", "De 'Traewer' y 'Fljner', lit. 'Accionar la mano para atacar'", "Traew"),
("Traewflĵnug", "De 'Traewer' y 'Fljnug', lit. 'Acción de la mano para atacar'", "Traew"),
("Fljnòktrjeg", "De 'Fljnug' y 'Oktrjeg', lit. 'Cantidad de mano'", "Fljn"),
("Wjtblùtbeg", "De 'Wjteg' y 'Blutbeg', lit. 'Azul con blanco'", "Wjt"),
("Wjtròdeg", "De 'Wjteg' y 'Rödeg', lit. 'Rojo con blanco'", "Wjt"),
("Wjtwàrteg", "De 'Wjteg' y 'Wärteg', lit. 'Negro con blanco'", "Wjt"),
("Wälojeteg", "Palabra originante tradicional", "Wälojet"),
("Egtaeg", "Palabra originante tradicional", "Egta"),
("Egtaer", "Palabra originante tradicional", "Egta"),
("Egtaeges", "Lit. 'Relativo a duración'", "Egtaeg"),
("Egtaeget", "Lit. 'Duración pequeña'", "Egtaeg"),
("Egtaegetes", "Lit. 'Relativo a duración pequeña'", "Egtaeg"),
("Egtaegeter", "Lit. 'Hacer duración pequeña'", "Egtaeg"),
("Egtaegon", "Lit. 'Duración grande'", "Egtaeg"),
("Egtaegones", "Lit. 'Relativo a duración grande'", "Egtaeg"),
("Egtaegoner", "Lit. 'Hacer duración grande'", "Egtaeg"),
("Öterwjss", "Palabra originante tradicional", "Öterwjss"),
("Rëngleg", "Palabra originante tradicional", "Rëngl"),
("Rënglaj", "Palabra originante tradicional", "Rëngl"),
("Rënglar", "Palabra originante tradicional", "Rëngl"),
("Rënglegaf", "Lit. 'Sin diversión'", "Rëngleg"),
("Rëngleges", "Lit. 'Relativo a diversión'", "Rëngleg"),
("Rënglegafes", "Lit. 'Relativo a sin diversión'", "Rëngleg"),
("Rënglegafar", "Lit. 'Hacer sin diversión'", "Rëngleg");
-- interés =/= desinterés
-- aparición =/= desaparición 
-- relajar y tensionar
-- Käswej (adelante)

SELECT * FROM heroku_bf7cb810553a372.`word`;