-- Criterios: inicio con abreviatura en mayúscula. Leyenda de etiquetas: coloq (coloquial), obs (obsoleto), tamb (también), equiv a (equivalente a), relig (religión), despect (despectivo), cult (cultural), neo (neologismo), tec (tecnicismo), vulg (vulgar), ling (lingüística)

CREATE TABLE IF NOT EXISTS `dictionary`.`definition` (
id INT PRIMARY KEY AUTO_INCREMENT,
word_definition1 VARCHAR(500),
word_definition2 VARCHAR(500),
word_definition3 VARCHAR(500),
word_definition4 VARCHAR(500),
word_definition5 VARCHAR(500),
FOREIGN KEY (`id`) REFERENCES `dictionary`.`word` (`id`)
);

TRUNCATE TABLE `dictionary`.`definition`;

INSERT INTO `dictionary`.`definition` (`word_definition1`, `word_definition2`, `word_definition3`, `word_definition4`, `word_definition5`) 
VALUES
("Haber.","","","",""),
("Palabra, vocablo, modismo.","coloq. Testimonio, atestación.","","",""),
("Verbal (perteneciente a la comunicación con palabras).","","","",""),
("Escribir, redactar.","","","",""),
("Renglón, línea (de texto).","","","",""),
("Letra, carácter, grafema.","","","",""),
("Oración, frase (escrita o hablada).","Locución, enunciado.","","",""),
("Oracional, locutivo, enunciativo.","","","",""),
("Párrafo.","Recorte o pasaje de un texto.","","",""),
("Texto, escrito, obra literaria.","","","",""),
("Biblioteca.","","","",""),
("Bibliotecario (perteneciente a la biblioteca).","","","",""),
("Librería, tienda de libros.","","","",""),
("Máquina de escribir.","","","",""),
("Dibujar, retratar.","Graficar, esquematizar.","","",""),
("Dibujo, retrato, obra artística.","Gráfico, esquema.","","",""),
("Dibujante, ilustrador.","","","",""),
("Fotografiar, capturar (con cámara fotográfica).","","","",""),
("tec. Fotografía, foto, daguerrotipo (imagen obtenida por luz).","","","",""),
("Fotográfico (emparentado con la fotografía).","","","",""),
("Cámara fotográfica, cámara de fotos (digital o analógica).","","","",""),
("Fotógrafo o fotógrafa (profesional de la fotografía).","","","",""),
("tec. Fotografía (estudio de dicha técnica de captura).","","","",""),
("Hablar o poner en práctica un idioma.","","","",""),
("Idioma, lengua o lenguaje.","","","",""),
("Idiomático, lingüístico.","","","",""),
("Tinta (sustancia para dibujo o escritura).","","","",""),
("Entintar, manchar o ensuciar (con tinta).","","","",""),
("Marcador, plumón.","Resaltador, rotulador.","","",""),
("Lapicera, birome, bolígrafo, pluma.","","","",""),
("Sabor, gusto, paladar.","","","",""),
("Sabroso, gustoso, delicioso.","","","",""),
("Saborear, degustar, probar, catar.","","","",""),
("coloq. Saboreo, degustación, cata.","","","",""),
("Dulzura, dulzor.","coloq. Suavidad, placidez o ternura en la forma de actuar.","","",""),
("Dulce, dulzón.","coloq. Tierno, amable.","","",""),
("Tener o practicar sexo, fornicar.","Copular (en animales).","","",""),
("Sexo (condición orgánica biológica que diferencia a muchos animales).","Genitales, caracter u órgano sexual externo.","","",""),
("Sexual, genital (alusión a los carácteres sexuales).","","","",""),
("Sexo (acto o relación sexual), fornicación.","Coito o cópula (de animales).","","",""),
("Sexual (relativo al acto sexual).","","","",""),
("Sal (sustancia de sodio).","","","",""),
("Salar (aplicar sal a algo), sazonar.","","","",""),
("Sabor a sal.","","","",""),
("Salado, salino, salobre.","","","",""),
("Azúcar.","","","",""),
("Azucarado, acaramelado.","","","",""),
("Azucarar, endulzar, dulcificar.","","","",""),
("Helado, mantecado, granizado (postre frío y dulce).","","","",""),
("Oler, olfatear, oliscar.","Presencia de un olor en algo o algún lugar.","coloq. Primera impresión o sospecha de algo.","",""),
("Olor (emanación apreciable con el olfato).","","","",""),
("Oloroso (que carga olor).","","","",""),
("Aroma, perfume, fragancia.","","","",""),
("Aromático, perfumado, fragante, odorífero.","","","",""),
("Hedor o hediondez, fetidez, peste o pestilencia.","","","",""),
("Hediondo, fétido, pestilente.","","","",""),
("Decir, comunicar, expresar.","","","",""),
("Manifestación, declaración, expresión.","","","",""),
("Usar, utilizar, emplear, disponer.","coloq. Manipular a alguien con una finalidad latente.","","",""),
("Uso, utilización, empleo, disposición.","coloq. Manipulación (de alguien).","","",""),
("Utilizable, empleable, disponible (que se puede usar).","","","",""),
("Agarrar, sujetar, asir.","","","",""),
("Agarre, sujeción.","","","",""),
("Hablar, dialogar, conversar, charlar.","coloq. Palabrear.","","",""),
("Diálogo, conversación, charla.","","","",""),
("Dialogal, dialogístico.","","","",""),
("Callamiento, mutismo o reserva que genera que una persona no hable.","","","",""),
("Callar, enmudecer, silenciar.","","","",""),
("Trabajar, obrar, laborar.","coloq. Ocuparse de algo para solucionarlo o mejorarlo.","","",""),
("Trabajo, labor, tarea.","Puesto o posición laboral, ocupación.","","",""),
("Trabajoso, laborioso (que conlleva trabajo o tiene dedicación para trabajar).","","","",""),
("Desocupación, desempleo.","","","",""),
("Sueldo, salario, jornal.","Honorario o remuneración por un servicio.","","",""),
("Trabajador, empleado.","Peón, obrero.","","",""),
("Colega, compañero de trabajo con similar rango.","","","",""),
("Boca.","Hocico, pico, trompa o cualquier órgano animal de ingestión.","Acción o mueca indefinida con la boca.","coloq. Entrada o acceso de algo.",""),
("Bucal, oral (alusivo a cualquier parte de la boca).","","","",""),
("Accionar o usar la boca de forma indefinida en pos de algo.","coloq. Tener un espasmo o temblor en la boca.","","",""),
("Aliento, hálito (aire que expulsa la boca).","","","",""),
("Escupir, esputar, expectorar.","Salivar, ensalivar, babear.","","",""),
("Masticar, mascar.","","","",""),
("Mordisco, mordedura.","Mordida, bocado.","","",""),
("Morder, mordisquear, atarazar.","coloq. Dar un bocado.","","",""),
("Besar.","Besuquear, mimar cariñosamente.","","",""),
("Beso, mimo cariñoso que se entrega con la boca.","","","",""),
("Silbar, pitar, chiflar.","","","",""),
("Silbido, pitido, chiflido.","","","",""),
("Obsequio, regalo, presente, dádiva.","Agasajo, mimo (material).","","",""),
("Obsequiar, regalar, agasajar.","","","",""),
("Intentar, probar, procurar.","","","",""),
("Intento, prueba.","","","",""),
("Pero, empero, mas (contraponer concepto con otro).","","","",""),
("Preguntar, interrogar.","","","",""),
("Pregunta, interrogación.","","","",""),
("Interrogante (que interroga).","","","",""),
("Amistar, amigar, apegar.","","","",""),
("Amistad, compañerismo, camaradería.","","","",""),
("Amistoso, amigable, afable.","","","",""),
("Fraternidad, hermandad (sentimiento muy fuerte de amistad).","","","",""),
("Fraternal, fraterno.","","","",""),
("Enemistad, rivalidad, antagonismo.","","","",""),
("Enemistar, rivalizar.","","","",""),
("Amigo, compañero o camarada cercano (relación de amistad y confianza).","","","",""),
("Ocurrir, suceder, pasar, acontecer.","","","",""),
("Suceso, acontecimiento, evento.","Vez, ocasión, turno, lance (momento repetido en tiempos diferentes).","","",""),
("Si (apertura de una situación condicional).","","","",""),
("Pedir, solicitar, requerir.","","","",""),
("Pedido, petición, solicitud.","","","",""),
("Petitorio (alusivo a o que contiene pedido).","","","",""),
("Súplica, ruego, imploración.","","","",""),
("Suplicante, rogatorio, implorante.","","","",""),
("Suplicar, rogar, implorar.","","","",""),
("Disculpar, perdonar, excusar, exculpar.","","","",""),
("Disculpa, perdón, exculpación.","","","",""),
("Que carga relación con la disculpa.","","","",""),
("Acusación, inculpación.","","","",""),
("Acusatorio (que implica acusación).","","","",""),
("Echar la culpa, inculpar, acusar, achacar.","","","",""),
("Aceptar, aprobar, acceder.","Permitir, asentir, consentir, autorizar.","","",""),
("Aceptación, aprobación.","Permiso, asentimiento, consentimiento, autorización.","","",""),
("Aprobatorio (que implica aprobación).","Permisivo, condescendiente (permite o consiente sin resistencia).","","",""),
("Desaprobación, reprobación, rechazo.","Prohibición, denegación.","","",""),
("Reprobatorio (que implica reprobación).","Prohibitivo, denegatorio.","","",""),
("Desaprobar, reprobar, rechazar.","Prohibir, denegar.","","",""),
("Silenciar, callar, enmudecer.","Tranquilizar, calmar, sosegar, serenar.","","",""),
("Silencio (ausencia de sonido).","Tranquilidad, calma, sosiego, serenidad.","","",""),
("Silencioso, callado (principalmente seres vivos).","Tranquilo, calmo, sereno, sosegado.","","",""),
("Ruido, bullicio, griterío.","Intranquilidad, inquietud, desasosiego.","","",""),
("Ruidoso, fragoroso, bullicioso.","Intranquilo, inquieto, desasosegado.","","",""),
("Hacer ruido, alborotar.","Intranquilizar, inquietar, estremecer, alterar.","","",""),
("Tamaño, volumen, dimensión, grandor.","","","",""),
("Voluminoso, grande.","","","",""),
("Grandeza (propiedad o cualidad de algo de mucho tamaño).","Grandiosidad, magnificencia.","","",""),
("Enorme, gigante, inmenso, descomunal.","Grandioso, magnífico, magnificente.","","",""),
("Agrandar, engrandecer, agigantar, ampliar.","","","",""),
("Pequeñez (propiedad o cualidad de algo de poco tamaño).","coloq. Insignificancia, futilidad.","","",""),
("Pequeño, chico, diminuto, ínfimo.","despect. Insignificante, minúsculo, fútil.","","",""),
("Achicar, encoger, reducir, contraer.","","","",""),
("Dimensionar, medir o mensurar el tamaño de algo.","","","",""),
("Suavidad, tersura, lisura.","coloq. Delicadeza y cariño, principalmente en el trato.","","",""),
("Suave, terso, liso, fino.","coloq. Delicado, cariñoso (en el trato personal).","","",""),
("Aspereza, rugosidad.","coloq. Rudeza y severidad, principalmente en el trato.","","",""),
("Áspero, rugoso, rasposo.","coloq. Rudo, severo, hosco (en el trato personal).","","",""),
("Suavizar, lenificar, alisar (hacer que algo sea más suave).","","","",""),
("Blandura, flacidez, molicie.","coloq. Lenidad, flexibilidad, tolerancia.","","",""),
("Blando, flácido, tierno, mullido.","coloq. Flexible, tolerante, indulgente.","","",""),
("Dureza, solidez, rigidez.","coloq. Severidad, rigurosidad.","","",""),
("Duro, sólido, rígido, tieso.","coloq. Severo, riguroso.","","",""),
("Endurecer, indurar, robustecer.","","","",""),
("Ablandar, emblandecer, aflojar.","","","",""),
("Cualquier, cualquiera o cualesquiera.","","","",""),
("Cada (apunta a una serie de partes individuales de un total).","Cada uno.","","",""),
("Todo, todos, toda o todas.","","","",""),
("Parte, elemento, ingrediente.","Pedazo, porción, fracción, trozo.","","",""),
("Parcial, fraccionario, elemental (que implica parte de un todo).","","","",""),
("Totalidad, completitud, integridad.","Conjunto, grupo entero.","","",""),
("Total, completo, íntegro, absoluto.","","","",""),
("Partir, dividir, fraccionar.","","","",""),
("Paz (específicamente en términos bélicos).","","","",""),
("Pacífico, sereno (que no hace la guerra).","","","",""),
("Pacificar, reconciliar, hacer las paces.","","","",""),
("Batalla, combate, contienda.","","","",""),
("Batallador, combativo, belicoso.","","","",""),
("Guerra, conflicto armado de gran escala.","","","",""),
("Bélico, marcial, guerrero (perteneciente a la guerra).","","","",""),
("Pelea, lucha, escaramuza.","","","",""),
("Guerrear, combatir o luchar en armas.","Invadir, conquistar, asaltar.","","",""),
("obs. Emisario que enviaba mensaje de tregua.","Diplomático.","","",""),
("Guerrero.","neo. Soldado, militar.","","",""),
("Capa, estrato.","coloq. Rebanada, tajada.","","",""),
("Que se compone de capas, estratos o niveles.","","","",""),
("Laminar, rebanar (cortar una capa).","","","",""),
("Hoja, lámina fina, película.","","","",""),
("Revestimiento, cobertura o cubierta, envoltura.","","","",""),
("Envolvente, que cubre o reviste.","","","",""),
("Piel, cutis, epidermis.","Cáscara, corteza, caparazón, cápsula.","","",""),
("Cutáneo, dérmico, epidérmico.","","","",""),
("Cuchilla, hoja afilada.","","","",""),
("Ataque, agresión, arremetida.","","","",""),
("Agresivo, atacante.","","","",""),
("Atacar, agredir, arremeter.","","","",""),
("Defensa, protección, cuidado.","Custodia, amparo, salvaguarda.","","",""),
("Defensivo, defensor, protector.","","","",""),
("Desprotección, desamparo, abandono.","","","",""),
("Desproteger, desamparar, abandonar.","","","",""),
("Defender, proteger, cuidar.","Custodiar, amparar, salvaguardar.","","",""),
("Alteza (tratativo formal y obligatorio para la Gran Duquesa).","","","",""),
("Altura, altitud, elevación.","Estatura, talla (en personas o seres).","","",""),
("Alto, elevado, prominente.","","","",""),
("Elevar, alzar, levantar.","","","",""),
("Bajura, falta de elevación.","","","",""),
("Bajo, chico, petiso (corta altura o estatura).","","","",""),
("Hundir, deprimir (causar que algo tenga altura negativa).","","","",""),
("Línea (geométrica), trazo, raya.","coloq. Divisor de dos cosas.","","",""),
("Lineal, recto (con forma o comportamiento de la línea).","","","",""),
("Puntear, dibujar o escribir puntos.","","","",""),
("Punto (geométrico).","coloq. Marca, hito.","coloq. Momento, instante.","",""),
("Pensar, imaginar (representar en la mente).","Razonar, reflexionar, meditar.","","",""),
("Pensamiento, imaginación (representación en la mente).","Razonamiento, reflexión, meditación.","","",""),
("Pensado, imaginario, ficticio.","","","",""),
("Idea, pensamiento o reflexión ingeniosos.","","","",""),
("Idear, ingeniar, planear.","","","",""),
("Polígono, figura o cuerpo geométrico y plano.","","","",""),
("Círculo, circunferencia, redondel.","","","",""),
("Triángulo.","","","",""),
("Cuadrado.","Rectángulo.","","",""),
("Pentágono.","","","",""),
("Hexágono.","","","",""),
("Liberar, emancipar, independizar.","Otorgar voluntad o libre albedrío.","","",""),
("Libertad, emancipación, independencia.","Voluntad, albedrío.","","",""),
("Libre, independiente.","","","",""),
("Esclavitud, dependencia, sometimiento.","Servidumbre, sujeción.","","",""),
("Dependiente, esclavo, servidor, sujeto.","","","",""),
("Esclavizar, someter, subyugar.","","","",""),
("Esclavo (persona carente de libertad y derechos propios).","Siervo, súbdito, servidor.","","",""),
("Fuerza, vigor, fortaleza.","","","",""),
("Fuerte, vigoroso, enérgico.","Robusto, fornido, forzudo, hercúleo.","","",""),
("Fortalecer, reforzar, robustecer.","","","",""),
("Debilidad, fragilidad.","","","",""),
("Débil, frágil, endeble, vulnerable.","despect. Debilucho, enclenque, alfeñique.","","",""),
("Debilitar, enflaquecer.","","","",""),
("Recordar, rememorar, evocar.","Acordarse de algo reciente y desatendido.","","",""),
("Recuerdo, memoria, remembranza (imagen puntual de la mente).","","","",""),
("Memoria, retentiva (capacidad para evocar recuerdos).","","","",""),
("Memorioso, memorión, retentivo.","","","",""),
("Desmemoria (falta de memoria).","tec. Amnesia.","","",""),
("Desmemoriado, olvidadizo, descuidado.","","","",""),
("Olvido (pérdida o cese de un recuerdo).","","","",""),
("Olvidar, descuidar.","","","",""),
("Nombre (completo para una persona).","Denominación, designación.","","",""),
("Nominal (relacionado al nombre).","","","",""),
("Nombrar, bautizar.","Denominar, designar.","coloq. Llamar, convocar, mencionar, citar.","",""),
("Facilidad, sencillez, simplicidad.","","","",""),
("Fácil, sencillo, simple.","","","",""),
("Dificultad, complicación.","","","",""),
("Difícil, complicado, intrincado.","","","",""),
("Favor, ayuda, asistencia.","","","",""),
("Hacer un favor, ayudar, asistir.","coloq. Acompañar.","","",""),
("Valeria, nombre de la Gran Duquesa.","","","",""),
("Valeriano (alusivo a la Gran Duquesa Valeria I).","","","",""),
("Gran Duquesa (título nobiliario de la soberana de Libraterra).","","","",""),
("Ducal (de la Gran Duquesa o relacionado con ella).","","","",""),
("Gran Ducado.","","","",""),
("Investir, proclamar o ungir a alguien como duque o duquesa.","","","",""),
("Automóvil, auto, coche.","","","",""),
("Automovilístico (afín a dicho medio de transporte).","","","",""),
("neo. Computadora, ordenador.","","","",""),
("neo. Computacional (de la tecnología informática o relacionado).","","","",""),
("Teléfono (aparato de comunicación a distancia).","","","",""),
("Telefónico (relacionado con ese dispositivo).","","","",""),
("Llamar (por teléfono), telefonear.","","","",""),
("neo. Teléfono móvil, teléfono celular.","","","",""),
("Chocolate (pasta sólida a base de cacao).","","","",""),
("Sí (expresión de afirmación).","","","",""),
("También (incluye un sintagma a una afirmación).","","","",""),
("No (expresión de negación).","","","",""),
("Tampoco (incluye un sintagma a una negación).","","","",""),
("Muy.","Mucho, muchos, mucha o muchas.","","",""),
("Demasiado, demasiados, demasiada o demasiadas.","","","",""),
("Poco, pocos, poca o pocas.","","","",""),
("Tan.","Tanto, tantos, tanta o tantas.","","",""),
("Solo, apenas.","","","",""),
("Modo, manera, forma, estilo.","","","",""),
("Más (mayor cantidad o superioridad).","","","",""),
("Menos (menor cantidad o inferioridad).","","","",""),
("Mejor (superior a algo).","","","",""),
("Mejorar, progresar, prosperar.","","","",""),
("Mejoría, mejora, adelanto.","","","",""),
("Peor (inferior a algo).","","","",""),
("Empeorar, desmejorar, deteriorar.","","","",""),
("Empeoramiento, deterioro, desmejora.","","","",""),
("Decidir, determinar, deliberar.","","","",""),
("Decisión, determinación, deliberación.","","","",""),
("Deber, tener que, comprometerse a (hacer algo).","Adeudar o estar bajo obligación de cumplir algo.","","",""),
("Deber, obligación, compromiso, responsabilidad.","","","",""),
("Obligatorio, forzoso, debido.","","","",""),
("Deuda, adeudo (dinero en deber de pagar a otra persona).","","","",""),
("Impuesto, tributo, arancel o gravamen estatales o públicos.","","","",""),
("Impositivo, tributario, arancelario.","","","",""),
("Necesitar, precisar, requerir.","","","",""),
("Necesidad, precisión, requisito.","","","",""),
("Necesario, preciso, imprescindible.","","","",""),
("Unidad, tipo, muestra, modelo.","tec. Ejemplar, espécimen.","","",""),
("Unicidad, exclusividad.","","","",""),
("Único, exclusivo, singular.","","","",""),
("Unificar, uniformar, aunar (logrando un todo nuevo).","","","",""),
("Multiplicidad, pluralidad.","","","",""),
("Reproducir, repetir, copiar, multiplicar.","","","",""),
("Dar, entregar, otorgar.","Proporcionar, suministrar, conceder.","","",""),
("Entrega, otorgamiento, concesión.","","","",""),
("Recibir, tomar (aceptar algo que se da).","Admitir, acoger.","Dar la bienvenida.","",""),
("Recepción, recibo.","Admisión, acogida.","Bienvenida (acción de recibir a alguien).","",""),
("Acogedor, hospitalario, receptivo.","","","",""),
("Elegir, escoger, seleccionar, optar.","","","",""),
("Elección, selección, opción.","","","",""),
("Electivo, selectivo, optativo u opcional.","","","",""),
("Resolver, solucionar, solventar (generalmente algo inmaterial).","","","",""),
("Resolución, solución, solventación (generalmente algo inmaterial).","","","",""),
("Resolutorio, concluyente, decisivo (que provee solución definitiva).","","","",""),
("Problema, cuestión, inconveniente.","","","",""),
("Problemático (que causa o supone un problema).","","","",""),
("Junto a (algo en compañía o cercanía con otra cosa).","","","",""),
("ling. Expresión adjetiva sirviente de adverbio y equivalente a juntos o juntas.","","","",""),
("Juntar, combinar, mezclar, fusionar.","","","",""),
("Mezcla, fusión, combinación.","","","",""),
("Causar, provocar, ocasionar, desencadenar.","","","",""),
("Causa, motivo (razón por la que sucede algo).","","","",""),
("Causante, motivante, responsable.","","","",""),
("Aquí, acá.","","","",""),
("Allí, allá, ahí.","","","",""),
("Llevar, portar, cargar.","","","",""),
("Norte, septentrión (punto cardinal).","","","",""),
("Norteño, septentrional, boreal.","","","",""),
("coloq. Encontrar el norte, orientarse, ubicarse.","","","",""),
("Sur, sud, meridión (punto cardinal).","","","",""),
("Sureño, meridional, austral.","","","",""),
("Oeste, poniente, occidente (punto cardinal).","","","",""),
("Occidental (situado al oeste).","","","",""),
("Este, naciente, oriente (punto cardinal).","","","",""),
("Oriental (situado al este).","","","",""),
("Aún, todavía (persistencia de algo hasta este momento).","","","",""),
("Tarde (tardíamente, con retraso).","","","",""),
("Tardanza, demora, retraso.","","","",""),
("Tardío, retardado.","","","",""),
("Retardar, demorar, retrasar.","","","",""),
("Temprano, pronto (tempranamente, con antelación).","","","",""),
("Tempranez, antelación, anticipación.","","","",""),
("Anticipado, adelantado, prematuro, precoz.","","","",""),
("Anticipar, adelantar, darle más tempranez a algo.","","","",""),
("Quizás, tal vez, posiblemente.","","","",""),
("Ya (sucedido antes), previamente.","","","",""),
("Mientras (simultaneidad de acciones).","","","",""),
("Que.","Qué (en tono interrogatorio).","","",""),
("Como, igual que.","Cómo (en tono interrogatorio).","","",""),
("Quien, quienes.","Quién, quiénes (en tono interrogatorio).","","",""),
("Porque.","Por qué (en tono interrogatorio).","","",""),
("Cuando.","Cuándo (en tono interrogatorio).","","",""),
("Donde.","Dónde (en tono interrogatorio).","","",""),
("Cuanto, cuantos, cuanta o cuantas.","Cuánto, cuántos, cuánta o cuántas (en tono interrogatorio).","Cuán (énfasis sobre adjetivo o adverbio).","",""),
("Cual, cuales.","Cuál, cuáles (en tono interrogatorio).","","",""),
("Izquierda (dirección).","Corriente política de izquierda.","","",""),
("Izquierdo, zurdo, siniestro (del lado de la izquierda o relacionado con tal).","","","",""),
("Derecha (dirección).","Corriente política de derecha.","","",""),
("Derecho, diestro (del lado de la derecha o relacionado con tal).","","","",""),
("Y (unión o enumeración de dos cosas).","","","",""),
("O (alternativa entre una cosa y otra).","","","",""),
("Día, jornada, fecha.","","","",""),
("Diario, periódico, cotidiano (de cada día).","","","",""),
("Fecha de nacimiento.","Cumpleaños, aniversario de nacimiento.","","",""),
("Cumpleañero (persona que celebra cumpleaños).","","","",""),
("Día de fin de semana.","Día feriado o no laborable.","","",""),
("Semana.","","","",""),
("Semanal, hebdomadario (de cada semana).","","","",""),
("Mes.","","","",""),
("Mensual (de cada mes).","","","",""),
("Favoritismo, preferencia, predilección.","","","",""),
("Favorito, preferido, predilecto.","","","",""),
("Preferir, tener predilección por algo.","","","",""),
("Año, temporada.","","","",""),
("Anual, añal (de cada año).","","","",""),
("Estación (período del año entre un equinoccio y un solsticio, o viceversa).","","","",""),
("Lustro, quinquenio (período de cinco años).","","","",""),
("Década, decenio (período de diez años).","","","",""),
("Siglo, centuria.","","","",""),
("Invierno.","","","",""),
("Invernal, hibernal.","","","",""),
("Verano.","","","",""),
("Veraniego, estival.","","","",""),
("Primavera.","","","",""),
("Primaveral, vernal.","","","",""),
("Otoño.","","","",""),
("Otoñal, autumnal.","","","",""),
("Ya (de inmediato), enseguida, a continuación.","","","",""),
("Ahora, actualmente (en este momento).","","","",""),
("Hoy, este día.","","","",""),
("Presente, actualidad, modernidad.","","","",""),
("Actual, presente, moderno.","","","",""),
("Pasado, pretérito (momento temporal).","","","",""),
("Pasado, pretérito (perteneciente a ese momento).","","","",""),
("Antes, hace un rato.","","","",""),
("Ayer, el día anterior.","","","",""),
("Después, luego, pronto.","","","",""),
("Mañana, día siguiente, día después.","","","",""),
("Futuro, porvenir, posteridad.","","","",""),
("Futuro, venidero, posterior.","","","",""),
("Arriba, en lo alto (dirección).","","","",""),
("Encima, sobre (en la parte superior de algo).","","","",""),
("Subir, ascender.","coloq. Mejorar, desarrollar.","","",""),
("Subida, ascenso.","","","",""),
("Abajo, en lo bajo (dirección).","","","",""),
("Debajo (en la parte inferior de algo).","","","",""),
("Bajar, descender, caer.","","","",""),
("Bajada, descenso, caída.","","","",""),
("Dentro, en el interior.","","","",""),
("Adentro (hacia el interior).","","","",""),
("Entrar, ingresar, acceder.","","","",""),
("Entrada, ingreso, acceso.","","","",""),
("Entrante, ingresante.","","","",""),
("Interior (sector por dentro de algo).","Intimidad (aspecto profundo de una persona).","","",""),
("Interior, interno (situado en el interior).","Íntimo, personal, recóndito.","","",""),
("Abrir, descubrir, destapar (despejar cualquier abertura o comunicación hacia el exterior).","coloq. Iniciar, inaugurar, estrenar.","","",""),
("Abertura, apertura (acción de abrir algo).","coloq. Inauguración, estreno.","","",""),
("Abierto (comunicado con el exterior).","coloq. Inaugural, preliminar.","coloq. Comprensivo y respetuoso.","",""),
("Cerrar, tapar, sellar (bloquear cualquier abertura o comunicación hacia el exterior).","coloq. Clausurar, finalizar.","","",""),
("Cierre, cerramiento (acción de cerrar algo).","coloq. Clausura, finalización.","","",""),
("Cerrado (incomunicado con el exterior).","coloq. Que denota clausura o finalización.","coloq. Cabezadura e intransigente.","",""),
("Puerta (abertura de un edificio).","coloq. Punto de partida hacia algo.","","",""),
("Piso, pavimento, solado (superficie de material sobre el suelo).","","","",""),
("Techo, techado, cielorraso (material que recubre un edificio).","","","",""),
("Fuera, en el exterior.","","","",""),
("Afuera (hacia el exterior).","","","",""),
("Salir, partir, abandonar.","","","",""),
("Salida, partida, abandono.","","","",""),
("Saliente (que sale de algo).","coloq. Destacado, sobresaliente, resaltante.","","",""),
("Exterior (sector por fuera de algo).","coloq. Territorio extranjero o por fuera del país en cuestión.","","",""),
("Exterior, externo (situado en el exterior).","","","",""),
("Residir, morar, vivir.","Habitar, poblar, asentarse.","","",""),
("Hogar, vivienda, morada, domicilio.","Inmueble, propiedad.","","",""),
("Hogareño, doméstico, casero.","","","",""),
("Casa, residencia.","","","",""),
("neo. Apartamento, departamento, piso.","","","",""),
("neo. Edificio residencial, complejo habitacional, monobloque de departamentos.","","","",""),
("Mansión, caserón, palacete.","","","",""),
("Morador, ocupante, residente (de una vivienda).","Habitante, poblador, lugareño (de un área geográfica).","","",""),
("Inquilino, arrendatario (persona que alquila una vivienda temporalmente).","Huésped, hospedado, pensionista (persona invitada o que paga una vivienda).","","",""),
("Barrio, vecindario, distrito.","","","",""),
("Barrial (afín a un barrio).","","","",""),
("Dispositivo, artilugio.","neo. Máquina, aparato.","coloq. Objeto que soluciona algo muy complicado.","",""),
("neo. Electrodoméstico, aparato hogareño.","","","",""),
("Heladera, refrigerador, nevera.","","","",""),
("Horno, cocina (aparato).","","","",""),
("Reloj, cronómetro.","","","",""),
("Respirador artificial (máquina para proveer respiración a un paciente).","","","",""),
("neo. Robot, autómata (máquina que realiza labores humanas).","neo. Androide (robot con fisonomía símil a la humana).","","",""),
("Ventilador, turbo o cualquier máquina cuya función sea generar viento.","","","",""),
("Abanico, pericón, ventalle.","Soplillo, aventador.","","",""),
("Música, melodía (arte de combinar sonidos).","","","",""),
("Musical, melódico, melodioso.","","","",""),
("Musicar, musicalizar.","coloq. Dotar a algo de una dinámica atrapante y profunda.","","",""),
("Canción, tema, pieza musical.","","","",""),
("Instrumento musical.","","","",""),
("Músico o música (persona que ejecuta o interpreta música a través de un instrumento).","","","",""),
("Compositor, autor, musicólogo.","","","",""),
("Himno nacional.","","","",""),
("Amar, querer profundamente a alguien.","","","",""),
("Amor (profundo sentimiento de estima hacia alguien).","Pasión, deseo romántico.","","",""),
("Apasionado, ardiente, amoroso.","Enamorado (que experimenta amor hacia alguien).","","",""),
("Odio, rencor.","coloq. Maldad, vileza.","","",""),
("Rencoroso, resentido, con odio.","","","",""),
("Odiar, detestar.","coloq. Despreciar, menospreciar.","","",""),
("Cariño, afecto.","coloq. Antojo, capricho.","","",""),
("Cariñoso, afectuoso, tierno.","","","",""),
("Querer (sentir afecto), estimar a alguien.","coloq. Antojar.","","",""),
("cult. Amor conyugal que se tiene bajo promesa en un matrimonio libraterrense.","","","",""),
("Novio o novia (persona con vínculo amoroso con otra).","Prometido o prometida, pretendiente.","","",""),
("Noviazgo, relación amorosa o afectiva.","","","",""),
("Familiar, pariente, ser querido.","","","",""),
("Familia, parentela (grupo de personas emparentadas).","","","",""),
("Prometer, jurar.","","","",""),
("Promesa, juramento, voto.","","","",""),
("Casar, matrimoniar, desposar.","","","",""),
("Esposo o esposa, cónyuge, consorte.","","","",""),
("Esposo, marido.","","","",""),
("Esposa, mujer (bajo matrimonio).","","","",""),
("Matrimonio, unión conyugal.","","","",""),
("Felicidad, alegría, dicha.","","","",""),
("Feliz, alegre, contento, dichoso.","","","",""),
("Alegrar, contentar, animar.","","","",""),
("Tristeza, congoja, angustia.","Aflicción, zozobra, consternación.","","",""),
("Triste, acongojado, angustiado.","Afligido, consternado, afectado.","","",""),
("Entristecer, angustiar, acongojar.","","","",""),
("Cerca (evento o lugar inminentes).","","","",""),
("Acercar, aproximar, arrimar.","","","",""),
("Cercanía, proximidad, inmediación (espacial o temporal).","coloq. Relación o trato social con una persona.","","",""),
("Cercano, próximo, inmediato (espacial, temporal o relacional).","","","",""),
("Lejos (evento o lugar distantes).","","","",""),
("Lejanía, distancia, alejamiento (de espacio o temporal).","","","",""),
("Lejano, alejado, distante, remoto.","","","",""),
("Alejar, distanciar, apartar.","coloq. Perder un vínculo personal.","","",""),
("Tener, poseer.","Conservar, mantener.","","",""),
("Posesión, pertenencia, propiedad.","","","",""),
("Creer, suponer.","tec. Conjeturar, inferir, presumir.","","",""),
("Creencia, suposición.","tec. Conjetura, presunción, hipótesis.","","",""),
("Supuesto, presunto, hipotético.","","","",""),
("Entender, comprender, asimilar.","","","",""),
("Entendimiento, comprensión, asimilación.","","","",""),
("Envalentonar, infundir valentía o ánimo.","","","",""),
("Valentía, valor, coraje.","coloq. Agallas, redaños.","","",""),
("Valiente, valeroso, corajudo.","","","",""),
("Intrepidez, audacia, arrojo.","","","",""),
("Intrépido, audaz, resuelto.","","","",""),
("Cobardía, miedo (como identidad).","Temor, susto (como efecto coyuntural).","","",""),
("Cobarde, miedoso, pusilánime, temeroso (como identidad).","Asustado (como efecto coyuntural).","","",""),
("Pánico, espanto, pavor, terror.","","","",""),
("Asustar, atemorizar, aterrorizar, espantar.","","","",""),
("Saber, conocer.","","","",""),
("Conocimiento (saber adquirido).","","","",""),
("tec. Ciencia (rama del saber obtenido metodológicamente).","Disciplina, asignatura, estudio.","","",""),
("tec. Científico (que se relaciona con la ciencia).","","","",""),
("Ignorancia, desconocimiento.","","","",""),
("Desconocido, ignoto, incógnito.","","","",""),
("Ignorar, desconocer.","","","",""),
("Sabiduría, inteligencia, erudición, conocimiento.","","","",""),
("Inteligente, sabio, erudito.","","","",""),
("Gustar, agradar, atraer.","","","",""),
("Gusto, agrado, atracción, inclinación.","","","",""),
("Gustoso, agradable, grato.","","","",""),
("Disgusto, desagrado, rechazo.","","","",""),
("Desagradable, molesto, que causa disgusto.","","","",""),
("Disgustar, desagradar.","","","",""),
("Fascinación, deslumbramiento, embeleso.","","","",""),
("Fascinante, deslumbrante, embelesante.","","","",""),
("Fascinar, deslumbrar, embelesar, maravillar.","","","",""),
("Paciencia, perseverancia, tolerancia.","Conformidad, resignación.","coloq. Calma, tranquilidad.","",""),
("Paciente, perseverante, tolerante.","Conformista, acomodadizo, que tiene resignación.","","",""),
("Impaciencia, nerviosismo, intranquilidad.","","","",""),
("Impaciente, nervioso, intranquilo.","","","",""),
("Querer, desear.","","","",""),
("Deseo, aspiración.","","","",""),
("Deseoso, ganoso.","","","",""),
("Anhelo, afán o avidez entusiasmados.","","","",""),
("Anheloso, anhelante, afanoso, ávido.","","","",""),
("Anhelar, pretender o ansiar con gran entusiasmo.","","","",""),
("Colorear, teñir, entintar.","","","",""),
("Color, tinte, tono.","","","",""),
("Colorido (dotado de colores brillantes, vivos o variados).","","","",""),
("Ausencia de coloración o pigmentación (asociado al negro por falta de luz).","","","",""),
("Incoloro, acrómico.","","","",""),
("Negro.","","","",""),
("Persona de etnia negra o africana.","","","",""),
("Ennegrecer, oscurecer.","","","",""),
("Blanco.","","","",""),
("Blanquear, aclarar.","","","",""),
("Persona de etnia blanca o caucásica.","","","",""),
("Verde.","","","",""),
("Rojo.","","","",""),
("Amarillo.","","","",""),
("Azul.","","","",""),
("Naranja (color).","","","",""),
("Plateado (color).","","","",""),
("Dorado (color).","","","",""),
("Beber, tomar, sorber.","","","",""),
("Bebida, refresco, líquido bebible.","","","",""),
("Obtener, conseguir, lograr.","","","",""),
("Obtención, logro, consecución.","","","",""),
("Poder (hacer o lograr algo), tener capacidad o facultad.","","","",""),
("Capacidad, aptitud, idoneidad.","","","",""),
("Capaz, apto, idóneo.","","","",""),
("Incapacidad, ineptitud, incompetencia.","despect. Torpeza.","","",""),
("Incapaz, inepto, incompetente.","","","",""),
("Incapacitar, inhabilitar, invalidar.","","","",""),
("Ver, mirar, observar.","","","",""),
("Mirada, vista (hacer uso del sentido de la vista).","","","",""),
("Ojeada, vistazo rápido.","Mirada de reojo.","","",""),
("Ojear, echar un vistazo.","coloq. Ver con cautela y disimulo a alguien para apreciar su belleza.","","",""),
("Visión (capacidad de percepción de la realidad con la vista).","coloq. Interpretación personal de algo.","","",""),
("Caminar, andar, marchar.","Pasear, deambular.","","",""),
("Caminata, paseo, marcha.","","","",""),
("Pisada, paso, zancada.","","","",""),
("form. Dar un paso.","","","",""),
("Procesión o desfile (no necesariamente religiosos).","","","",""),
("Cantar, entonar.","Recitar melódicamente o con estilo musical.","Corear.","",""),
("Canto, entonación.","Coro.","","",""),
("Canturreo, tarareo.","","","",""),
("Canturrear, tararear.","","","",""),
("Ser, estar.","","","",""),
("Existencia, presencia.","tec. Conciencia del ser.","","",""),
("Ser (vivo), criatura.","despect. Alimaña, bicho.","tec. Ente orgánico.","",""),
("Cosa, objeto, entidad.","","","",""),
("Herramienta, instrumento, utensilio.","","","",""),
("Naturaleza.","","","",""),
("Metal.","Material duro y resistente.","","",""),
("Plata (metal noble).","","","",""),
("Oro (metal noble).","","","",""),
("Hacer, realizar, efectuar, obrar.","","","",""),
("Hecho, acción, obra, actividad.","","","",""),
("Agradecimiento, gratitud, reconocimiento.","","","",""),
("Desagradecimiento, ingratitud.","","","",""),
("Desagradecer, desconocer o no corresponder un favor o beneficio recibido.","","","",""),
("Agradecer, gratificar, reconocer.","","","",""),
("Dios, diosa.","Persona celestial o sobrenatural.","","",""),
("Panteón de dioses y diosas.","","","",""),
("Escritor, escritora.","Guionista, argumentista.","coloq. Persona que fabula e inventa cosas.","",""),
("Cantante, cantor, cantora.","Corista.","","",""),
("Dúo, pareja o tándem de personas.","coloq. Pareja o relación (amorosa).","","",""),
("Trío, terna de personas.","tec. Triunvirato (forma de gobierno con tres gobernantes).","","",""),
("Vivir, existir.","","","",""),
("Vida (transcurso de tal).","coloq. Ciclo o proceso.","","",""),
("Sentir, experimentar.","","","",""),
("Sentimiento, emoción (estado de ánimo o disposición emocional).","","","",""),
("Sensibilidad, emotividad.","","","",""),
("Nunca, jamás (en ninguna ocasión).","","","",""),
("Siempre, continuamente (en cualquier momento del tiempo y sin interrupción, o en todas las ocasiones posibles).","","","",""),
("Llegar, arribar, alcanzar un destino.","","","",""),
("Llegada, arribo, aparición.","Meta, destino, culminación.","","",""),
("Cuerpo, figura, físico, humanidad.","Masa, materia.","","",""),
("Transpirar, sudar, exudar.","","","",""),
("Transpiración, sudor, exudación.","","","",""),
("Formar (generalmente algo material), conformar, moldear.","","","",""),
("Morir, fallecer, perecer.","","","",""),
("Muerte, fallecimiento, deceso.","coloq. Fin trágico o doloroso de algo.","","",""),
("Mortalidad.","","","",""),
("Inmortalidad, eternidad.","","","",""),
("Inmortalizar, perpetuar, eternizar.","","","",""),
("Cadáver, muerto, difunto.","","","",""),
("neo. Zombi.","","","",""),
("Captar mentalmente una imagen.","","","",""),
("Imagen (representación captada a través de los rayos de luz).","","","",""),
("Simbolizar, representar, encarnar.","","","",""),
("Símbolo, representación (elemento representativo de algo).","","","",""),
("Bandera (enseña de nación o institución).","","","",""),
("Sincerar, confesar.","","","",""),
("Verdad, veracidad, certeza.","Sinceridad, honestidad, franqueza.","","",""),
("Falsedad, contenido falto de verdad.","Mentira, engaño, falacia.","","",""),
("Mentir, engañar, faltar a la verdad.","","","",""),
("Escuchar, oír, atender.","","","",""),
("Escucha (evento en que algo fue escuchado).","","","",""),
("Audición.","","","",""),
("tec. Sordera, hipoacusia.","","","",""),
("Oyente de radio u otro medio de comunicación que involucra sonido.","","","",""),
("Audiencia (espectadores de un medio comunicativo que incluye sonido).","","","",""),
("Delinquir, perpetrar.","Infringir o incurrir en una infracción grave.","","",""),
("Delito, crimen.","Falta o infracción de gravedad.","","",""),
("Matar, asesinar, ejecutar.","","","",""),
("Asesinato, homicidio, ejecución.","","","",""),
("Robar, afanar, desvalijar, hurtar.","Malversar, desfalcar, defraudar.","","",""),
("Robo, hurto, estafa.","Malversación, desfalco, defraudación.","","",""),
("Delito de agresión, delito de lesiones.","","","",""),
("Cometer delito de agresión o de lesiones.","","","",""),
("Tortura, suplicio, tormento.","","","",""),
("Torturar, martirizar.","","","",""),
("Delincuente, maleante.","Malviviente, malhechor.","","",""),
("Fibra, filamento de materia prima textil.","","","",""),
("Hilo, hebra.","","","",""),
("Tela, tejido.","","","",""),
("Ropa, vestido (pieza genérica de vestir).","Vestimenta, indumentaria, traje, ropaje (ropa general).","","",""),
("Sangrar, desangrar, padecer una hemorragia.","","","",""),
("Sangre.","Savia de las plantas.","","",""),
("Vampiro.","coloq. despec. Explotador, usurero.","","",""),
("Corazón.","coloq. Sensibilidad, empatía.","","",""),
("tec. Vena o arteria.","","","",""),
("tec. Vasos, capilares y conductos sanguíneos menores.","","","",""),
("Concebir, procrear (una persona).","coloq. Crear algo lindo o positivo (generalmente relacionado a la humanidad).","coloq. Proyectar, planificar.","",""),
("Persona, ser humano.","coloq. Creación noble o bondadosa.","coloq. Proyecto, idea a futuro.","",""),
("Sociedad, comunidad, colectividad.","Grupo o asociación de individuos unidos para determinado fin.","","",""),
("Niño o niña, crío o cría.","Persona en edad prejuvenil.","","",""),
("Bromear o jugar de forma aniñada.","coloq. Comportarse de manera tonta y desubicada.","","",""),
("Grupo de niños y niñas.","Clase escolar.","despect. Pandilla o caterva juvenil.","",""),
("Guardería, kinder, jardín de infantes.","","","",""),
("Persona anciana, en etapa de vejez.","coloq. Persona sabia, experimentada.","","",""),
("neo. Geriátrico, asilo de ancianos.","","","",""),
("Envejecer o avejentar (una persona).","coloq. Deteriorar, estropear.","","",""),
("obs. cult. Cónclave de los sabios de la aldea.","","","",""),
("Rejuvenecer, remozar, renovar.","","","",""),
("Juventud, lozanía, mocedad.","","","",""),
("Vejez, longevidad, ancianidad, senilidad.","","","",""),
("Envejecer, avejentar, ajar.","","","",""),
("Embellecer, hermosear (generalmente una persona a sí misma).","Encantar o fascinar a alguien con la belleza física o la personalidad.","","",""),
("Hermosura, lindura, preciosidad.","Atractivo o encanto seductores.","","",""),
("Fealdad, horribilidad.","","","",""),
("Afear (hacer feo o más feo algo o alguien).","","","",""),
("coloq. Grosería, mala palabra, palabrota.","","","",""),
("Educar, enseñar, instruir.","cult. Preparar o formar con los valores de la sociedad libraterrense.","","",""),
("Lección, clase (sesión o exposición de enseñanza).","","","",""),
("Educación, enseñanza, instrucción.","Cortesía, cordialidad.","","",""),
("Escuela, colegio y cualquier institución educativa.","","","",""),
("Aula, cátedra, clase.","","","",""),
("Docente, profesor, educador, maestro.","","","",""),
("Aprender, estudiar.","Memorizar.","","",""),
("Aprendizaje (proceso de adquisición de conocimientos).","","","",""),
("Estudiante, alumno o alumna.","Aprendiz, discípulo.","","",""),
("Ganar, triunfar, vencer.","","","",""),
("Triunfo, victoria, éxito.","","","",""),
("Derrota, fracaso, vencimiento.","","","",""),
("Perder, fracasar, verse derrotado.","","","",""),
("Hombre (varón).","Muchacho joven, chico.","","",""),
("Niño (varón), nene, chico.","","","",""),
("Mujer.","coloq. Muchacha joven, chica.","","",""),
("Niña, nena, chica.","","","",""),
("Destino, hado (fuerza predeterminada que rige el mundo).","coloq. Suerte, fortuna.","","",""),
("coloq. cult. Seguir o ejecutar el destino, tal como éste rige en el universo según la idiosincrasia libraterrense.","","","",""),
("Animal.","Bestia, fiera.","","",""),
("Mamífero (familia de animales que maman).","","","",""),
("Pájaro, ave.","","","",""),
("Volar, planear, surcar.","","","",""),
("Vuelo, planeo (desplazamiento por el aire).","","","",""),
("Mascota (animal domesticado que habita con los humanos).","","","",""),
("Cachorro, cría.","","","",""),
("Plantar, trasplantar.","","","",""),
("Planta o vegetal genéricos.","","","",""),
("Semilla, simiente, germen.","Pimpollo, tallo o tronco vegetal de muy poco desarrollo.","","",""),
("Sembrar, esparcir o diseminar semillas.","","","",""),
("Árbol, arbusto de gran tamaño.","","","",""),
("Bosque, arboleda.","Selva, jungla.","","",""),
("Florecer, brotar (una flor).","","","",""),
("Flor (parte de la planta con los órganos reproductores).","coloq. Elogio o halago hacia alguien.","","",""),
("Cala, lirio de agua, flor de jarro.","","","",""),
("Alga, sargazo.","Camalote, jacinto de agua.","","",""),
("Césped, pasto.","Hierba silvestre ordinaria.","","",""),
("Matorral, pastizal.","Pradera, prado, estepa.","","",""),
("Hoja, fronda (órgano verde y plano de las plantas).","Pétalo, bráctea (hoja afín a las flores).","","",""),
("Corola (grupo de pétalos que protegen los órganos reproductivos de la flor).","","","",""),
("Montaña, monte, sierra.","","","",""),
("Volcán.","","","",""),
("Meseta, altiplano.","","","",""),
("Cordillera, cadena de montañas.","","","",""),
("Tundra o estepa.","","","",""),
("Disfrutar, gozar, deleitar.","","","",""),
("Placer, satisfacción, deleite, disfrute.","","","",""),
("Dolor, sufrimiento, padecimiento, aflicción.","","","",""),
("Doler, sufrir, padecer, lamentar.","","","",""),
("Cura, remedio, sanación.","Medicamento, medicina, fármaco.","","",""),
("Sanar, curar, tratar, aliviar.","","","",""),
("Herida, lesión, lastimadura.","","","",""),
("Herir, dañar, lastimar, lesionar.","","","",""),
("Salud, sanidad, salubridad.","coloq. Vitalidad, vigor.","","",""),
("Enfermedad, afección, dolencia.","","","",""),
("tec. Medicina (ciencia de las enfermedades).","","","",""),
("Médico, galeno, doctor.","","","",""),
("tec. Virus (agente infeccioso microscópico).","","","",""),
("tec. Democracia (representación política de la sociedad por medio del voto).","","","",""),
("Tierra, suelo.","tec. Tierra (planeta del Sistema Solar).","coloq. Basamento o fundamento de algo.","",""),
("Hacer trabajos de agricultura sobre la tierra.","coloq. Encargarse de un trabajo difícil.","","",""),
("Barro, lodo, fango.","Arcilla, caolín, plastilina.","","",""),
("Niebla, neblina, bruma.","","","",""),
("Fundar un pueblo (nación), hacer soberana una tierra.","coloq. Sentar las bases o fundamentos de un gran proyecto.","","",""),
("País, Estado.","Tierra, parcela, terreno o lote que le pertenece a alguien.","","",""),
("Provincia, departamento, estado o cualquier jurisdicción subnacional (generalmente gozante de autonomía o identidad propias).","Porción de un terreno o propiedad privados.","","",""),
("Continente.","Región importante o grande.","","",""),
("Ciudadano (persona gozante de derechos políticos).","Patriota, persona con orgullo nacionalista.","","",""),
("Nación, patria o matria (sociedad unida bajo la misma identidad cultural e histórica).","","","",""),
("Apátrida (persona carente de nacionalidad).","","","",""),
("Compatriota, conciudadano, coterráneo, paisano.","","","",""),
("Ciudad, urbe, metrópolis.","coloq. Centro o eje de una actividad o característica.","","",""),
("Pueblo, poblado, villa, aldea o cualquier localidad urbana de reducida población.","","","",""),
("Capital (ciudad de residencia del gobierno estatal).","tec. Megalópolis, conurbación (aglomerado urbano).","","",""),
("Urbanita, citadino (persona que vive o creció en la ciudad).","","","",""),
("Igualar, nivelar, equiparar.","","","",""),
("Igualdad, paridad, equivalencia.","","","",""),
("Semejanza, parecido, similitud.","","","",""),
("Diferencia, desigualdad, disparidad.","","","",""),
("Par, semejante (persona con condición igual a otra).","relig. Prójimo.","","",""),
("Sinónimo (palabra con mismo significado que otra).","","","",""),
("Lugar, sitio, emplazamiento.","Edificio, edificación, establecimiento o construcción artificial genérico.","","",""),
("Ubicar, situar, localizar.","","","",""),
("Obtener o recuperar la cordura o sanidad mental.","Mesurar, moderar el juicio.","","",""),
("tec. Cordura (sanidad mental).","Sensatez, prudencia, juicio.","","",""),
("tec. Locura, demencia, insania.","Insensatez, imprudencia, indiscreción.","","",""),
("Enloquecer, delirar, desvariar.","Descuidar la prudencia o sensatez.","","",""),
("Tiempo (dimensión temporal).","coloq. Presente o momento actual.","","",""),
("Contemporaneidad (concepto de existencia al mismo tiempo).","","","",""),
("Contemporáneo (existente al mismo tiempo).","","","",""),
("Adelgazar, enflaquecer (perder peso).","","","",""),
("Delgadez, flacura, esbeltez.","","","",""),
("despect. Escualidez, demacración, cualidad de macilento.","coloq. despect. Escasez o deficiencia de algo.","","",""),
("Gordura, adiposidad (acumulación de grasa y peso).","","","",""),
("Engordar (ganar peso).","","","",""),
("tec. Obesidad (patología de adiposis excesiva).","coloq. despect. Exceso o demasía de algo.","","",""),
("Vengar, vindicar, desquitarse.","","","",""),
("Venganza, represalia, desquite.","Revancha (segunda oportunidad en juegos y deportes).","","",""),
("Encontrar, hallar, recuperar (algo o alguien perdido o sin paradero conocido).","Ubicar, localizar.","","",""),
("Encuentro, hallazgo de algo o alguien perdido.","","","",""),
("Extravío, pérdida, descuido.","","","",""),
("Extraviar, perder, descuidar.","","","",""),
("Cultivar tierra sembrada.","coloq. Aquirir un conocimiento.","coloq. Sacar provecho de algo.","coloq. Trabajar forzosamente.",""),
("Granja, tierra de cultivo.","despect. Puesto de trabajo no deseado.","","",""),
("Mojar, empapar.","Aguar (aplicar agua a un alimento)","","",""),
("Agua (sustancia natural).","coloq. Elemento considerado vital o enriquecedor.","","",""),
("Hidratar o saciar la sed.","Humedecer, humectar.","","",""),
("Hidratación o saciedad de la sed.","Humedad, humectación (impregnación de agua).","","",""),
("Sed, deshidratación.","Sequedad, aridez.","","",""),
("Deshidratar","Secar, deshumedecer, desaguar.","","",""),
("Desierto, yermo, arenal.","","","",""),
("Charco, formación de agua pequeña.","","","",""),
("Lago o laguna.","coloq. Estado de confusión profunda.","","",""),
("Mar, ponto.","","","",""),
("Océano.","","","",""),
("Río, arroyo, torrente.","coloq. Flujo o curso de un acontecimiento.","","",""),
("Afluente, ramificación secundaria de un río.","","","",""),
("Extrañar, echar de menos.","","","",""),
("Sentimiento algo pesadumbroso o nostálgico por extrañar a alguien o algo.","","","",""),
("Ordeñar (obtener leche de un animal hembra).","","","",""),
("Ordeño (acción de ordeñar).","","","",""),
("Leche (sustancia nutritiva de los mamíferos).","","","",""),
("Dulce de leche, cajeta (dulce a base de azúcar y leche).","","","",""),
("Infusionar o preparar café para consumo.","","","",""),
("Café (infusión bebible).","","","",""),
("Grano de café.","","","",""),
("cult. Típica bebida libraterrense servida en tazón y consistente de una parte de café, otra de leche y condimentada con algo de azúcar.","","","",""),
("Miel (sustancia dulce producida por las abejas).","","","",""),
("Reparar, arreglar, enmendar (generalmente algo material).","Recomponer, reformar, restaurar (generalmente algo material).","","",""),
("Reparación, arreglo, enmienda (generalmente algo material).","Recomposición, reformación, restauración (generalmente algo material).","","",""),
("Rotura, avería, estropicio.","","","",""),
("Romper, averiar, estropear, arruinar.","Inutilizar, incapacitar.","","",""),
("Relatar, contar, narrar.","","","",""),
("Historia, relato, crónica.","Cuento o narración (literarios).","","",""),
("Anécdota, relato breve curioso o divertido.","Chiste, broma.","coloq. Chisme, murmuración.","",""),
("Sueño (imaginación que se percibe como real mientras se duerme).","","","",""),
("Pesadilla (sueño desagradable).","coloq. Situación lamentada y evitable.","","",""),
("Soñar.","","","",""),
("Órgano (unidad funcional de un organismo vivo).","coloq. Parte fundamental que cumple una función en una institución.","","",""),
("Ojo.","","","",""),
("Oído (órgano interno de la audición).","Oreja (cartílago que recubre el oído).","","",""),
("Lengua (del interior de la boca).","","","",""),
("Pelo, cabello (uno).","coloq. Algo de poca cuantía o dimensión.","","",""),
("Pelo, cabellera, melena.","","","",""),
("Pelada, calvicie, calva.","","","",""),
("Cabellera rubia o bastante clara.","","","",""),
("Cabellera negra o bastante oscura.","","","",""),
("Cana (cabello blanco o gris, falto de melanina).","","","",""),
("Quemar, chamuscar, incendiar.","coloq. Enfadar a alguien.","coloq. Excitar, despertar apetito sexual.","",""),
("Fuego, llama, flama.","coloq. Enfado, ira.","coloq. Pasión, lujuria.","",""),
("Aire (composición gaseosa prevalente en la Tierra).","","","",""),
("Airear, ventilar, refrescar.","","","",""),
("Respirar (función biológica automatizada).","","","",""),
("Respiración.","Jadeo, resuello.","","",""),
("Inhalar, aspirar, inspirar.","","","",""),
("Inhalación, aspiración, inspiración.","","","",""),
("Pulmón.","","","",""),
("Limpiar, higienizar, asear.","","","",""),
("Limpieza, higiene, aseo.","","","",""),
("Suciedad, inmundicia, desaseo.","","","",""),
("Ensuciar, manchar, enmugrecer.","","","",""),
("Ordenar, mandar, decretar.","","","",""),
("Orden, mandato, mandamiento, decreto.","","","",""),
("Obedecer, acatar, cumplir.","","","",""),
("Obediencia, acatamiento, cumplimiento.","","","",""),
("Obediente, cumplidor, bienmandado.","","","",""),
("Siervo, súbdito, servidor.","","","",""),
("Inicio, comienzo, principio.","relig. Génesis, origen.","","",""),
("Iniciar, comenzar, empezar.","","","",""),
("Fin, final, término, conclusión.","","","",""),
("Infinito (concepto de no tener fin ni límite).","tec. Valor mayor que cualquier cantidad asignable, representado con '∞'.","","",""),
("Finalizar, terminar, concluir, acabar.","coloq. Alcanzar el orgasmo o clímax sexual, principalmente el hombre en la eyaculación.","","",""),
("Epílogo (parte final de un libro o texto).","","","",""),
("Prólogo (introducción de un libro o texto).","","","",""),
("Lectura, leída.","","","",""),
("Leer (ver texto para interpretarlo mentalmente).","","","",""),
("Orar, pronunciar un discurso, leer en voz alta.","","","",""),
("Discurso, oración (orar vocalmente), pronunciamiento.","","","",""),
("Continuar, seguir, proseguir, reanudar.","","","",""),
("Continuación, seguimiento, reanudación.","","","",""),
("Detención, interrupción, suspensión.","","","",""),
("Detener, parar, interrumpir, suspender.","","","",""),
("Bien (de modo correcto según normas implícitas).","","","",""),
("Bondad, benevolencia, benignidad.","coloq. Característica de buena calidad, condición o modo.","","",""),
("Hacer el bien (lo correcto según normas implícitas).","","","",""),
("Mal (de modo incorrecto según normas implícitas).","","","",""),
("Maldad, malicia, malignidad.","coloq. Característica de mala calidad, condición o modo.","","",""),
("Hacer el mal (lo incorrecto según normas implícitas).","","","",""),
("Derrochar, despilfarrar, dilapidar.","","","",""),
("Viento, correntada.","","","",""),
("Brisa, corriente, viento suave.","","","",""),
("Reunir, congregar, encontrarse.","Clasificar, ordenar, catalogar.","","",""),
("Encuentro, reunión, congregación (de dos o más individuos).","Clasificación, ordenación o agrupamiento de elementos afines.","","",""),
("Salón, sala.","Ambiente o sector de un edificio techado.","","",""),
("Comedor del hogar.","","","",""),
("Dormitorio, habitación, cuarto, aposento.","","","",""),
("Baño, tocador, toilet.","","","",""),
("Ir, encaminar.","","","",""),
("Venida, llegada.","","","",""),
("Venir (ir adonde el interlocutor).","","","",""),
("Alcohol (compuesto químico).","coloq. Cosa nociva o que causa estragos.","","",""),
("Bebida alcohólica, bebida espirituosa.","","","",""),
("Alcoholizar, añadir alcohol a un líquido u obtenerlo por destilación.","Emborrachar, embriagar, intoxicar.","","",""),
("Comer, tragar, ingerir.","coloq. Hacer desaparecer algo.","","",""),
("Cocinar, cocer, preparar comida con fuego.","","","",""),
("Cocción, cocedura (procedimiento para cocinar).","","","",""),
("Comida, alimento.","Plato (alimento preparado para comer).","coloq. Fuente de energía y positividad.","",""),
("Tentempié, aperitivo, refrigerio.","","","",""),
("Hambre, apetito, gana (de comida).","","","",""),
("obs. Punto de la aldea donde se reunía a comer en familia.","Restaurante, cantina.","","",""),
("Desayuno (comida de la mañana temprano).","","","",""),
("Desayunar (comer el desayuno).","","","",""),
("Almuerzo (comida del mediodía).","","","",""),
("Almorzar (comer el almuerzo).","","","",""),
("Merienda (comida de la tarde).","","","",""),
("Merendar (comer la merienda).","","","",""),
("Cena (comida de la noche).","","","",""),
("Cenar (comer la cena).","","","",""),
("Cortar, tajar, seccionar (con instrumento afilado).","","","",""),
("Corte, tajo, incisión.","","","",""),
("Raspón, rasguño, arañazo.","","","",""),
("Cuchillo (cubierto de mesa).","","","",""),
("Comprar, adquirir, mercar (operación comercial).","","","",""),
("Compra, adquisición.","","","",""),
("Tienda, comercio, negocio (sitio de venta de productos de consumo).","","","",""),
("Vender, expender (operación comercial).","","","",""),
("Venta (transacción de cesión de algo por dinero).","","","",""),
("Pagar, abonar, costear.","coloq. Gastar o desembolsar dinero.","","",""),
("Dinero, plata, efectivo.","Medio de intercambio.","","",""),
("Moneda, unidad monetaria, divisa.","","","",""),
("Riqueza, fortuna, abundancia.","coloq. Prosperidad, auge.","","",""),
("Pobreza, escasez (económica).","","","",""),
("Miseria, penuria, indigencia.","","","",""),
("Tesoro, gran capital.","","","",""),
("neo. Banco, institución financiera.","","","",""),
("neo. Bóveda bancaria donde se guarda el dinero.","","","",""),
("Empresario, emprendedor.","Inversor, inversionista.","coloq. Dueño, patrón, jefe, mandamás.","",""),
("Nacer (un ser).","coloq. Originar, iniciar.","coloq. Crear o dar forma a algo generalmente abstracto.","",""),
("Nacimiento.","","","",""),
("Bebé, neonato, recién nacido.","coloq. Hijo, hija, descendencia.","despect. coloq. Novato, inexperto.","",""),
("Feto, embrión (en desarrollo dentro del útero).","","","",""),
("Infante, párvulo.","","","",""),
("Luz, luminosidad, brillo.","coloq. Conocimiento, sapiencia.","coloq. Salvador, salvadora.","",""),
("Oscuridad, tiniebla (ausencia de luz para percibir las cosas).","","","",""),
("Oscurecer, ensombrecer (quitar la luz).","coloq. Arrebatar la esperanza o el aliento.","","",""),
("Aurora boreal.","","","",""),
("Estrella, lucero, astro.","","","",""),
("Iluminar, alumbrar.","Encender, prender (activar algo que genera luz).","coloq. Brillar, resplandecer.","coloq. Enseñar, instruir.",""),
("Rápido, deprisa, aprisa.","","","",""),
("Rapidez, celeridad.","Prisa, apresuramiento, prontitud (para hacer algo).","","",""),
("Apurar, acelerar, apresurar.","","","",""),
("Expeditar, solucionar algo con diligencia y agilidad.","","","",""),
("Despacio, lentamente.","","","",""),
("Lentitud, falta de rapidez.","","","",""),
("Desacelerar, ralentizar, lentificar.","","","",""),
("Movimiento, desplazamiento, traslación.","","","",""),
("Mover, desplazar, trasladar.","","","",""),
("Inmovilidad, quietud, reposo.","","","",""),
("Inmovilizar, aquietar, reposar.","","","",""),
("Película, filme o cinta cinematográfica.","","","",""),
("tec. Cinematógrafo, proyector (aparato que proyecta imágenes).","","","",""),
("Cine, cinema (establecimiento donde proyectan películas).","","","",""),
("Cinematografía (arte y técnica de proyección de imágenes).","","","",""),
("Traer (llevar algo o alguien al lugar del interlocutor).","coloq. Generar, originar.","","",""),
("Insolar (exponer algo al sol).","Entibiar o darle calidez a algo.","coloq. cult. Acariciar o tratar con cariño un hombre a una mujer.","",""),
("Embarazar un hombre a una mujer.","Preñar o fecundar un animal macho a la hembra.","","",""),
("Embarazo, gestación.","","","",""),
("Sol.","coloq. Ente masculino poderoso y magnífico.","coloq. Problema significativo y crítico.","",""),
("Cobardía, temor.","Decepción, disgusto.","","",""),
("Masculinidad, hombría.","Seducción, persuasión.","coloq. Galán, donjuán.","",""),
("Dormir, descansar.","coloq. Embelesar o cautivar con su belleza una mujer a un hombre.","","",""),
("Luna (satélite de la Tierra).","coloq. Ente femenino poderoso y magnífico.","coloq. Desventura o trance sinuoso e intrincado.","",""),
("cult. coloq. Tratativo informal, afectuoso y tierno que recibe una mujer.","","","",""),
("Feminidad.","Belleza, beldad o atractivo femeninos.","","",""),
("Cielo, firmamento.","neo. tec. Cosmos, universo, espacio exterior más allá de la estratósfera.","","",""),
("relig. Cielo, paraíso, edén.","","","",""),
("relig. Infierno, averno.","","","",""),
("Llover, chaparrear, precipitar.","","","",""),
("Lluvia, chaparrón, precipitación.","","","",""),
("Llovizna, garúa, goteo.","","","",""),
("Diluvio, tormenta, aguacero.","","","",""),
("Granizo, granizada, pedrisco.","","","",""),
("Granizar, apedrear.","","","",""),
("Mundo (conjunto de las cosas que existen).","tec. Planeta (cuerpo celeste que comprende un mundo).","","",""),
("tec. Satélite (cuerpo celeste que gira alrededor de un planeta).","coloq. Persona o cosa que depende, o es dominada, totalmente de otra.","","",""),
("cult. Fundar o crear, conceptual y metafóricamente, un mundo a partir de algo.","","","",""),
("Regla, norma, pauta, orden.","","","",""),
("Reglamento, normativa, ordenanza.","","","",""),
("tec. Ley, precepto, mandato (norma dictada por una institución superior en poder).","","","",""),
("tec. Legislación, estatuto, código.","","","",""),
("Reglamentar, regular, preceptuar.","tec. Legalizar (implementar e imponer una ley en una sociedad o institución).","","",""),
("Viajar, recorrer, explorar.","Emprender una travesía o un desafío.","","",""),
("Camino, ruta, trayecto.","Carretera, pista, senda.","","",""),
("Viaje, recorrido, excursión.","Travesía, expedición, periplo.","coloq. Desafío o implicancia movilizante.","",""),
("Viajero, excursionista.","Explorador, aventurero.","coloq. Emprendedor, incursionista.","",""),
("neo. Astronauta, cosmonauta.","","","",""),
("Día (etapa solar de la jornada).","Mañana, madrugada.","coloq. Instancias iniciales de un acontecimiento.","",""),
("Amanecer, alborear (salir el sol).","coloq. Iluminar o ilustrar algo o alguien.","","",""),
("Amanecer, alba, albor.","coloq. Esclarecimiento y esperanza, generalmente luego de condiciones adversas.","","",""),
("Noche.","Madrugada sin sol.","coloq. Epílogo de un acontecimiento.","",""),
("Atardecer, anochecer.","coloq. Corromper u ofuscar algo o alguien.","","",""),
("Ocaso, crepúsculo.","coloq. Corrompimiento, desazón o desesperación.","","",""),
("Enfriar, refrescar.","Nevar (caer nieve).","coloq. Llevar algo a la heladera.","",""),
("Frío, baja temperatura.","","","",""),
("Calor, ardor, temperatura alta.","","","",""),
("Calentar, caldear, entibiar.","","","",""),
("Hielo.","neo. tec. Permafrost.","","",""),
("Congelar, helar, refrigerar.","","","",""),
("Glaciar, helero.","coloq. Témpano de hielo, masa de hielo considerable.","","",""),
("Nieve.","Escarcha pesada, aguanieve.","","",""),
("Copo de nieve.","","","",""),
("Nevasca, tormenta de nieve.","","","",""),
("Equilibrar, balancear.","coloq. Ordenar u organizar una situación.","","",""),
("Equilibrio, orden.","coloq. Piedra angular, precepto sobre el que se basa el éxito sostenido de algo.","","",""),
("Japón.","","","",""),
("Corea del Sur.","","","",""),
("Corea del Norte.","","","",""),
("Argentina.","","","",""),
("Países Bajos.","","","",""),
("Suecia.","","","",""),
("Finlandia.","","","",""),
("Noruega.","","","",""),
("Rusia.","","","",""),
("Yugoslavia.","","","",""),
("Libraterra.","","","",""),
("Aumentar, incrementar, acrecentar.","","","",""),
("Aumento, incremento, crecimiento.","","","",""),
("tec. Sumar, adicionar (realizar operación aritmética).","","","",""),
("tec. Suma, adición, total (operación aritmética).","","","",""),
("tec. Multiplicar (realizar operación aritmética).","","","",""),
("tec. Multiplicación, producto (operación aritmética).","","","",""),
("Número, cifra, cantidad.","","","",""),
("Contar, computar.","Enumerar, listar.","","",""),
("tec. Matemática.","","","",""),
("Ábaco.","neo. Contador (objeto).","","",""),
("Cubierto (utensilio genérico para manipular la comida).","","","",""),
("Gastronomía, culinaria (saberes del arte de cocinar).","","","",""),
("neo. Calculadora, sumadora (dispositivo).","obs. Computadora (máquina que procesaba tarjetas perforadas).","","",""),
("tec. Historia (disciplina).","","","",""),
("tec. Lingüística.","","","",""),
("tec. Biología.","","","",""),
("Individuo, ente personal (independiente).","","","",""),
("Uno (número).","","","",""),
("Dos.","","","",""),
("Ambos (tanto el uno como el otro).","","","",""),
("Tres.","","","",""),
("Cuatro.","","","",""),
("Cinco.","","","",""),
("Seis.","","","",""),
("Siete.","","","",""),
("Ocho.","","","",""),
("Nueve.","","","",""),
("Diez, decena.","","","",""),
("Cien, centena.","","","",""),
("Mil.","","","",""),
("Millón.","","","",""),
("A.","","","",""),
("vulg. A el, a los, a la o a las.","","","",""),
("Ante (frente a).","","","",""),
("Bajo (debajo de).","","","",""),
("Con (medio, modo o instrumento para hacer algo).","","","",""),
("Contra (hacia o enfrente de).","","","",""),
("De (múltiples usos adverbiales).","","","",""),
("Del, de los, de la, de las.","","","",""),
("Desde (después de, punto de origen).","","","",""),
("Durante (simultaneidad temporal con).","","","",""),
("En (lugar, tiempo o modo de).","","","",""),
("En el, en los, en la, en las.","","","",""),
("Entre (dentro de o en medio de).","","","",""),
("Hacia (orientación de algo).","","","",""),
("Hasta (límite final).","","","",""),
("Mediante (por medio de).","","","",""),
("Para (objetivo o término de).","","","",""),
("Por (múltiples usos adverbiales).","","","",""),
("Por el, por los, por la o por las.","","","",""),
("Según (con arreglo a, en conformidad con).","","","",""),
("Sin (carencia o falta de).","","","",""),
("Sobre, acerca de (con respecto a algo).","","","",""),
("Tras (después de, detrás de).","","","",""),
("Yo.","Mí.","","",""),
("Tú, vos.","Ti.","","",""),
("Él, ella o cualquier sujeto carente de género.","","","",""),
("Nosotros (todos hombres).","","","",""),
("Nosotras.","","","",""),
("Nosotros (géneros mixtos).","","","",""),
("Ustedes (todos hombres).","","","",""),
("Ustedes (todas mujeres).","","","",""),
("Ustedes (géneros mixtos).","","","",""),
("Ellos (todos hombres).","","","",""),
("Ellas.","","","",""),
("Ellos (géneros mixtos).","","","",""),
("El, los, la o las.","","","",""),
("Un, unos, una o unas.","Algún, alguno, algunos, alguna o algunas.","Ningún, ninguno, ningunos, ninguna o ningunas.","",""),
("Otro, otros, otra u otras.","","","",""),
("Alguna cosa, algo (realidad indeterminada y no especificada).","","","",""),
("Ninguna cosa, nada (inexistencia de algo).","","","",""),
("Alguna persona, alguien (una o más personas indefinidas).","","","",""),
("Ninguna persona, nadie (inexistencia de alguien).","","","",""),
("Este, esto, estos, esta o estas.","ling. Se emplea para crear un sujeto simulado cuando sea conveniente semánticamente.","","",""),
("Ese, eso, esos, esa o esas.","Aquel, aquello, aquellos, aquella o aquellas.","","",""),
("Vamos, bien, dale (aprobación o aliento).","","","",""),
("Gracias (muestra de agradecimiento).","","","",""),
("ling. Denota disgusto o asco.","","","",""),
("Esperanza, ilusión.","","","",""),
("Último, postrero, final.","","","",""),
("Esperanzar, ilusionar, infundir confianza.","","","",""),
("Esperanzador, prometedor, halagüeño.","","","",""),
("Desesperanza, desesperación, desaliento.","","","",""),
("Vulva, tamb. vagina (genital externo femenino).","","","",""),
("Pene (genital externo masculino).","","","",""),
("Vulvar, vaginal.","","","",""),
("Peneano.","","","",""),
("Parecer, aparentar, semejar.","","","",""),
("Natural (de la naturaleza y sin intervención humana).","Salvaje, silvestre, agreste.","coloq. Espontáneo, maquinal, instintivo.","",""),
("Tocar, palpar.","","","",""),
("Toque, contacto con la mano.","","","",""),
("Roce (contacto superficial ligero).","coloq. Caricia sigilosa.","","",""),
("Rozar (tocar ligeramente).","coloq. Acariciar sigilosamente.","","",""),
("Saludable, sano, salubre, salutífero.","","","",""),
("Curador, sanador.","","","",""),
("Parecido, semejante, similar, símil.","","","",""),
("Diferencia, desemejanza, disimilitud.","","","",""),
("Diferente, distinto, desemejante.","","","",""),
("Diferente, desigual, dispar.","","","",""),
("Placentero, satisfactorio, deleitoso, grato.","","","",""),
("Doloroso, lastimoso, penoso.","","","",""),
("Dañino, nocivo, hiriente.","","","",""),
("Entusiasmo, fervor, pasión.","","","",""),
("Entusiasmar, apasionar, enardecer.","","","",""),
("Él (sujeto masculino).","","","",""),
("Ella (sujeto femenino).","","","",""),
("Propietario, dueño.","obs. Amo, señor.","","",""),
("Señora, tamb. equiv. a señorita (vocativo tratativo antepuesto al nombre).","","","",""),
("Señor (vocativo tratativo antepuesto al nombre).","","","",""),
("Tétrico, lúgubre, fúnebre.","","","",""),
("Flaco, delgado, enjuto.","","","",""),
("Escuálido, demacrado, macilento.","","","",""),
("Huevo (cuerpo embrionario de los ovíparos).","","","",""),
("Luminoso, brillante, radiante.","coloq. Iluminado, ilustrado.","","",""),
("Oscuro, apagado (carente de luz).","coloq. Malvado o peligroso.","","",""),
("Móvil, movedizo.","coloq. Inquieto, alterado, turbado.","","",""),
("Inmóvil, quieto, estático.","","","",""),
("Ovar, aovar, poner huevos.","","","",""),
("Helado, congelado, gélido.","coloq. Ordenado, equilibrado.","","",""),
("Caliente, caluroso.","coloq. despect. Alborotado, atolondrado, irreflexivo.","","",""),
("Personalidad (identidad de forma de ser).","","","",""),
("Rico, acomodado, acaudalado.","","","",""),
("Opulencia, lujo.","","","",""),
("Opulento, pudiente, lujoso.","","","",""),
("Pobre, humilde, modesto.","","","",""),
("Indigente, miserable, menesteroso.","","","",""),
("Penumbra (cantidad moderada de luz que deja entrever).","","","",""),
("Ovado, ovoide (con forma o características de huevo).","","","",""),
("Humano, personal (propio de la naturaleza de este ser).","","","",""),
("Vecino (que vive o está empadronado en un barrio).","","","",""),
("Bueno, benévolo, benigno.","coloq. De buena calidad, condición o modo.","","",""),
("Malo, malicioso, maligno.","coloq. De mala calidad, condición o modo.","","",""),
("Humanidad, especie humana (conjunto de todos los seres humanos).","","","","");

SELECT * FROM `dictionary`.`definition`;