-- Criterios: no insertar múltiples líneas.

CREATE TABLE IF NOT EXISTS `dictionary`.`example` (
id INT PRIMARY KEY AUTO_INCREMENT,
word_example1 VARCHAR(500),
word_example2 VARCHAR(500),
word_example3 VARCHAR(500),
word_example4 VARCHAR(500),
word_example5 VARCHAR(500),
FOREIGN KEY (`id`) REFERENCES `dictionary`.`word` (`id`)
);

TRUNCATE TABLE `dictionary`.`example`;

INSERT INTO `dictionary`.`example` (`word_example1`, `word_example2`, `word_example3`, `word_example4`, `word_example5`) 
VALUES
("Froj göljàw tö kefjegen.","","","",""),
("Klaej fejfegen göljkàj üke knöjsjònuges.","Kjaes fejfeg göljtàjklar öl.","","",""),
("Fülwuj waej kefjegen tröljlàewün kjaes fejfeges mensaje.","","","",""),
("","","","",""),
("Klaej ljneg göljtàg tjö fejflĵnegen.","","","",""),
("Waej fejfeget 'c' jkë göljkàj wjlaej balanlàedenuges ljngeg.","","","",""),
("Traej fejfegon göljkàj frejegafes faer fejfar.","","","",""),
("Kon kläsj'al-fejfar knaejteg fejfegures.","","","",""),
("","","","",""),
("Öl gägulfèjfar öles fejfug.","","","",""),
("Ölugen göljklàsj-kaj kulkeges wjlaej fejfaurkĵgeg.","","","",""),
("Öl göljglàs waej fejfaurkĵgeges ärgugen.","","","",""),
("Wjlaej fejfkĵgeg öl tröljlùjkar kones fejfug.","","","",""),
("Klaej fejfànördnug göljkàj tjl 1930.","","","",""),
("","","","",""),
("","","","",""),
("Kjae göljkàj knaej rjgëlkèfjeg.","","","",""),
("Öl jkë göljglàs-kaj-lajtrĵgëlares.","","","",""),
("Kon göljsfàej-alar ölegen wän lajtrĵgëlug?","","","",""),
("Kjae göljtàg knaej gërflegones lajtrĵgëluges archivo.","","","",""),
("Öl göljwùjk-dësljar wän lajtrjgëlànördnug.","","","",""),
("Kon göljkàj lajtrjgëlkèfjeg?","","","",""),
("Öl jkë följknàler lajtrjgëlfèjregur.","","","",""),
("Kjaegen gägulĵngar føjljonlàedenuges.","","","",""),
("Öl jkë göljfèjr-söjw klaej ljngeg.","","","",""),
("Öl göljtàg fjke ljngeges fëjregen.","","","",""),
("Öl tröljàlar klaej rjgëlug tör blaekaj.","","","",""),
("","","","",""),
("","","","",""),
("Öl tröljfèjfar öles fejfug tör blaekfejfùtaj.","","","",""),
("Waej jagaj jkë göljtàg golunaj.","","","",""),
("Kon tröljlàeker pizza? Klaej göljkàj knaej golunajes laekug.","","","",""),
("Öl jkë följgòlunar traej!","","","",""),
("Udaj, öl följègael ä waej laekĵgeg tör Mjkèl faer knaej golunwĵkolaj.","","","",""),
("","","","",""),
("Klaej kokolàt jkë göljkàj üke süjkgòlunajes, fälòj klaej göljkàj enäj.","Krjstjan göljkàj knaej süjkgòlunajes kefjeg.","","",""),
("Öl göljwùjkugoner-swejaer tör kon...","Üke wülejtugen göljswèjaer trësjaw waej sjonkòjweg.","","",""),
("Öl jkë göljfèjr waej swejaeg tjl kjaes wajuget.","Konegen jkë wast'al öles swejaeg!","","",""),
("Waej swejaeges urnugen jkë göljkàj jagneges, jä?","","","",""),
("Ölegenes swejaeg göljkàj bljuneges.","Ölajn göljsfàej-laewün waej wülejtugen alar swejaug. Jäk!","","",""),
("Öl tröljtàg swejauges awalbèrätegen kjøne kon...","","","",""),
("Kon jkë laeker'al üke wjwjtaj.","","","",""),
("Öl göljglàs-wjwjtar öles laekug.","","","",""),
("Öl göljglàs waej wjwjtgòlunaj tjl klaej laekug.","","","",""),
("Waej jagajuren göljtàg wjwjtgòlunajes jagaj.","","","",""),
("Öles laekug jkë göljwùlasj ësjl süjkaj.","","","",""),
("Klaej göljkàj knaej süjkajes laekug.","","","",""),
("Öl göljwùjk-süjkar öles fjalaj.","","","",""),
("Klaej süjkaenjàgaj göljkàj üke golunajes!","","","",""),
("Kon göljsfàej-ärger klaej bljunwùljgaj?","Öles awalaurkĵgeg göljàrger ä grüfug laswäld udaj öl tröljfjàlar klaej froj.","Klaej göljàrger ä daljajaf...","",""),
("—Wäld göljkàj traej ärgug? —Göljklàsj-kaj öles laekug.","","","",""),
("Kones öndwùlejtug göljkàj üke ärguges!","","","",""),
("Öl göljglàsugon waej enäjàrgug tjl kones rjntèfjajon.","","","",""),
("Kjae frät göljwùjk enäjàrguges bljunwùljgajen.","","","",""),
("Knaej wülejtugen göljtàg üke färalàrgug.","","","",""),
("Waej bjseleg göljkàj färalàrguges wjl klaej awalaurkĵgeg.","","","",""),
("Kon tröljùwlaed öl wäld öl trudajàlar traej...","","","",""),
("Öl jkë tröljlàewün kjaes üwlaedug.","","","",""),
("Kon jkë följènskj traej lujkaj?","Kjae tröljènskj Karmen faer wän awalkòjweg.","","",""),
("Klaejes ënskjeg göljkàj frejegafes tjl fenser.","Waej ënskjeg tjl kefjegen göljkàj färaleges knaejteg.","","",""),
("Klaej blaekfejfùtaj göljkàj ënskjeges.","","","",""),
("Kon tekler'al öles rjnlug j kon glaewĵkolar'al öl.","","","",""),
("Waej teklug tjlaej futaj göljklàsj-kaj üke gräjuges.","","","",""),
("Katerĵna j öl tröljsòjw ätej waej knöjsjònug.","Kjae tröljsòjw öl tör üke sjonugon.","","",""),
("Kjaejn jkë fjügulsfàej-täg knaej söjwaj.","","","",""),
("Kjaegen tröljòwader knaej söjwajes rëndeg.","","","",""),
("—Kon göljkàj enäj? Kon göljkàj söjwajafes. —Öl jkë göljwùlasj-söjw faer kaj enäj.","","","",""),
("Kon jkë söjwajafer'al öl!","","","",""),
("Öl göljklàsj-tänstar fülwuj waej dajen faer wäld ölegen udajsfàej-laeker.","Kon göljsfàej-tänstar wjl öles ökjlugafes konpjùter?","","",""),
("Elkjer knaej kefjeget göljwùlasj üke tänsteg.","Wjl öles tänsteg öl göljèwlän fjke lujkaj.","","",""),
("Djana göljkàj knaej tänsteges awalkèfjeg, kjae göljtànstar fülwuj waej daj.","","","",""),
("Göljàw üke kefjegen tör tänstegaf wjlaej swolug.","","","",""),
("","","","",""),
("Öl göljkàj tänskèfjeg tjl Pepsico.","Wjlaej laedejug ölegen göljtàg tjöwän tänskèfjegen.","","",""),
("Tatjàna j öl göljkàj tänswenkèfjegen, laswäld tökan gägultànstar wjl klaej fejfkĵgeg.","","","",""),
("Kones wjkolaj göljkàj üke bljuneges.","Knaej wülejtugen göljtàg waej gräjuges wjkolaj.","Kon jkë alar'al öl traej wjkolaj!","Waej daweglàedejug göljkàj knaej wjkolaj äej kojwlàedejug.",""),
("Jonatan göljtàg knaej wjkolajes wöjlegaf.","","","",""),
("","","","",""),
("Öl göljglàs kones bjselwĵkolaj.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Ölegen tröljglaewĵkolar bulöw waej awalaj...","Kjae fjügulglaewĵkolar öles rjnlug.","","",""),
("Öl göljsfàej-ewjd kon knaej glaewĵkolaj?","","","",""),
("","","","",""),
("","","","",""),
("Öl göljtàg wän roglug faer kon!","","","",""),
("Öl jkë göljfèjr wäld rogler kjae...","","","",""),
("Kon följfrèt-kaj wëroj?","","","",""),
("Öl alëred tröljfrèteg, fälòj öl jkë göljsfàej.","","","",""),
("Öl alëred tröljfrèteg, fälòj öl jkë göljsfàej.","","","",""),
("Kon följtàkenar knaejteg ësjl?","","","",""),
("Kon alar'al öl knaej täkenaj!","","","",""),
("Kjaes täkenajes wastùrnugen tröljsòjw ütan fejfegen.","","","",""),
("Kjaeugen tröljwàlejer följ tjlaej grägajafet.","","","",""),
("Klaus göljkàj knaej wälejeges sjonkèfjeg.","","","",""),
("Kon göljfèjr kjae? Göljkàj üke wälejeges.","","","",""),
("Jkë göljàw daljajafen wjlaej wälejegon.","","","",""),
("Kjaejn glaeg fjügulkàj wälejegones.","","","",""),
("Waej wälejegaf göljkàj daentajafes faer fräjg kefjeg.","","","",""),
("Kjaejn tröljwàlejegafer för lujkaj, bäjgun wöjlegafes!","","","",""),
("Öl jkë göljtàg üke wälejkèfjegen, fälòj fülwuj göljkàj enäjeges.","","","",""),
("Traej jkë göljsfàej-üsker.","","","",""),
("Göljkàj knaej ljwkegafes üskug faer fülwuj waej kefjegen.","Klaej üskug, kjae tröljùwlaed öl knaejteged.","","",""),
("Kjn kon göljòkjlugafer öles sjfjànördnug, öl jkë följfèjr waej sjfjeg.","","","",""),
("Öl göljknàjkar kones änslaj, tjsälk wlaejaj.","","","",""),
("Öl göljtàg knaej knajkeg faer kon.","","","",""),
("Kon jkë frogael'al tör kones knajkeges fejfegen.","","","",""),
("Konajn jkë üwlaed'al knajkegonen, öl jkë följknàler traej köloreg!","","","",""),
("Öles knajkegones wasteg tröljsènsar wäld öl fjügulwùjk.","","","",""),
("Kjae gägulknàjkegonar öl wäld öl udajègael ä kjaes öndkĵgeget.","","","",""),
("Kon göljsfàej-änslar öl?","","","",""),
("Öl göljknàjar kones änslaj, tjsälk wlaejaj.","","","",""),
("Kjae tröljwàst öl tör knaej änslajes sälk.","","","",""),
("Kon gägulùwlaed änslajafen fülwuj waej daj.","","","",""),
("Wäld göljkàj klaej änslajafes fejfug?!","","","",""),
("Kjae tröljànslajafar öl för kjaes rëndegaf.","","","",""),
("Waej laedenug göljklàsj-alentar klaej trölj wäld kon udajsfàej-alar klaej.","Kon göljàlentar öl glaewĵkolar kon?","","",""),
("Wänes, öl göljwùlasj alentaj tjl öles fjsljkèfjegur.","Kon jkë göljtàg alentaj faer alar traej.","","",""),
("Waej alegen jkë göljkàj alentajes.","Kjae göljkàj üke alentajes, kjae jkë göljèlkjer.","","",""),
("Kjaejnes alentajaf tröljàlar öl ljwkegafes.","Kon göljtàg waej alentajaf tjl ëgael ä kjaes öndkĵgeg.","","",""),
("Kjae tröljùwlaed öl, wjl alentajafes sälk: 'Kon jkë alar'al klaej'.","Klaej laedenug göljtàg ükon alentajafes krjtonen.","","",""),
("Ölugen tröljàlentajafar öles roglug.","Kon kläsj'al-alentajafar kjaes fejfegen!","","",""),
("Kon jkë kulkar'al öl, öl göljwùjk-söjw!","Göljkàj sonteg faer kulkar ölegen.","","",""),
("För wlaejaj, kon göljàlar kulkeg...","Ölegen fjüguljàgnar tör kulkeg.","","",""),
("Josef göljkàj knaej kulkeges kefjegon.","Udaj, ölegen göljtàg knaej kulkeges awalkòjweg.","","",""),
("Göljàw üke kulkegaf, öl jkë göljsfàej-laewün!","Öl göljkàj kulkegafes, wändaj följbèndjlar knaejuj tänsteg.","","",""),
("Kon göljkàj üke kulkegafes wjlaej swejaug.","Öl göljkàj kulkegafes laswäld öl stjlaw jkë göljtàg öles lujkaj.","","",""),
("Guljàn träsjl göljkùlkegafar trësjaw waej awalkòjweg.","Kon jkë üwlaed'al kjae traej, kjae följkùlkegafar!","","",""),
("Waej gërfleg tjlaej kolweg göljkàj fändjlegafes.","","","",""),
("Kon göljtàg knaej gërfleges öndkĵgeg!","","","",""),
("Kon wast'al waej gërflegon tjl traej daweglàedejug!","Traej göljkàj waej gërflegon tjl ölegenes Gërtaj.","","",""),
("Klaej jagajon göljkàj gërflegones, ölugen jkë göljsfàej-ljoner klaej fülwuj!","Balanlàedenug göljkàj knaej gërflegones kjgeg faer jagnar.","","",""),
("Tör sjfjeg, öles rjnlug tröljgèrflegoner.","","","",""),
("","","","",""),
("Klaej wülejtug göljkàj gërflegetes.","Öl göljwùjk-tag gërflegetes rëndegafen!","","",""),
("Öl göljwùjk-gërflegeter klaej kefjdĵlugetur.","","","",""),
("Waej gërfleg tjlaej kolweg göljkàj fändjlegafes.","","","",""),
("Kones rjntèfjajon göljkàj üke awendeges.","Kon göljkàj loke awendeges dëjwel kon göljùwlaed traej futegen!","","",""),
("Göljàw knaejteged loke awendeges tjsälk kones rjnlug.","Kjae fjügulkàj knaej awendeges sjonkèfjeg.","","",""),
("Klaej roca göljtàg üke awendegaf.","Waej kefjeg träsjl fjügulsòjw tör awendegaf.","","",""),
("Froj waej laedejug göljkàj awendegafes.","Laswäld kon göljkàj awendegafes tör öl?","","",""),
("Öl kanskëklàsj-awendar klaej djlugetur.","","","",""),
("Klaej djlugetur göljkàj daentajes.","Kon göljkàj üke daentajes tör kones wajugen.","","",""),
("Sästan towlajug göljkàj waej ësjl daentajes?","Kjae fjügulkàj knaej daentajes kefjeg, knaej dogönuged fjügulsènsar rëndegaf.","","",""),
("Waej towlajugen göljkàj daentajafes.","Klaej laedenug göljkàj üke daentajafes töraej laedenlujklàsjug.","","",""),
("Klaej wuljgajon älered göljkàj daentajafes.","Öles fjsljkèfjeg göljkàj üke daentajafes tör öl.","","",""),
("Kon jkë daentajafar'al waej laekug, ö ölegen jkë följsfàej-laeker klaej!","","","",""),
("Öl göljwùlasj-daentar klaej laekug.","","","",""),
("Öl göljwùlasj knaej fräjg fejfug.","","","",""),
("Fülw kefjeg följklàsj-lujkar öl.","Bäjgun öl göljklàsj-lujkar för fülw?","","",""),
("Fülwuj waej kefjegen göljkàj wenkegafes.","","","",""),
("Waej oksjgen göljkàj frät knaej fülweg tjlaej jagaj.","Öl göljwùjk knaej fülweg tjl traej laekug, tjsälk wlaejaj.","","",""),
("Traej göljkàj frät knaej fülweges rëndeg.","","","",""),
("Traej göljkàj waej fülwegur tjl lujkaj wäld ölugen göljtàg?","Waej fülwegur tjl kefjegeten tröljfjàlar jagaj.","","",""),
("Ölegen göljklàsj-alar knaej fülwegures traewug grej waej swolug.","","","",""),
("Kjaejn fülwer'al öles tägegen.","","","",""),
("Balanlàedenug j Wajsjonlàedenug göljkàj bulöw grägaj.","","","",""),
("Knaej laedenugen göljkàj ükon grägajes, jkë tjsälk Balanlàedenug.","","","",""),
("Öl göljkàj troj faer grägar konugen.","","","",""),
("","","","",""),
("Kon göljkàj ükon grägajafes, kon träsjl göljrènder fülwuj tör knaej grägajafet.","","","",""),
("Klaej tö laedenugen göljkàj wjl grägajafon.","","","",""),
("Ölugen jkë göljwùjk-knäler knaej grägajafones rëndeg.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Knöjan waej jagaj göljàw knaej tëfjaj tör jagbĵseleg.","Kon göljèwjd knaej tëfjaj tör traej?","","",""),
("Laedejug göljtàg knaej tëfjajes sëgteg, tör tëfjajen üke wenkegafes bjtbjn klaej.","","","",""),
("Öl jkë göljkàj-tëfjar klaej towlajug!","","","",""),
("Kon göljsfàej-ewjd öl knaej tëfjajet tör papel?","","","",""),
("Öles öndkĵgeg jkë göljtàg tëfjajon faer waej kojwjàgaj.","","","",""),
("Klaej göljkàj knaej tëfjajones djlugetur faer elkjer waej autonòwajl.","","","",""),
("Kones rjntèfjajon göljkàj üke awendeges.","Waej huevo göljtàg knaej daentajafes rjntèfjajon.","","",""),
("Kon göljwùlasj knaejteg faer kones rjntèfjajones dönjlegaf?","","","",""),
("","","","",""),
("Kjae tröljàgnar knaej traewug tjl traej sjonkèfjeg.","","","",""),
("Klaej göljkàj knaej traewuges wülejtug.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Waej elkjugaf tröljsènsar öl knaej dönjlajaf.","","","",""),
("Kon ündjl elkjugafer'al kones fjsljkèfjegur!","","","",""),
("","","","",""),
("Kones Dawegaj Walèrja I, Gërtaj tjl Balanlàedenug.","","","",""),
("","","","",""),
("Sjntja göljkàj knaej dawegeges awalkèfjeg, kjae göljgèrfler ësjl wäld 1.70 mjtern.","","","",""),
("","","","",""),
("","","","",""),
("Kon göljfèlder wäld öl göljkàj knaej dawegegafes kefjeg?","","","",""),
("","","","",""),
("Knaej trjlĵneg göljtàg trj ljnegen.","Waej ljneg bjtbjn glaeg j glaegaf göljkàj üke gräjugafes.","","",""),
("Klaej göljkàj knaej ljneges fejfug, sjng bëndjleg ätej fändjleg.","","","",""),
("Knaej trjlĵneg göljtàg trj ljnegen.","","","",""),
("För wlaejaj, kon rjgelär'al trj sontegen froj.","","","",""),
("Öl gägulfèlder wäld klaej kanskë jkë göljkàj waej tösal.","Kon üke felder'al kones fejfegen.","","",""),
("Kon göljàgnar wjl öles feldugen.","Kon göljwùlasj ësjl feldug trölj tjl kon udajsfàej-knäler knaejteg.","","",""),
("Klaej göljkàj knaejuj tjl kones felduges berätegen?","","","",""),
("Öl göljtàg wän rëndfèldug faer klaej rëndegaf!","","","",""),
("Öl gölwùlasj-rëndfèlder knaejteg faer öles awalaurkĵgeg.","","","",""),
("Waej trjlĵneg göljkàj knaej ljnrĵnlug.","","","",""),
("Knaej wänlĵneg göljtàg wän ljneg.","","","",""),
("Knaej trjlĵneg göljtàg trj ljnegen.","","","",""),
("Knaej fjrlĵneg göljtàg fjr ljnegen.","","","",""),
("Knaej fajwlĵneg göljtàg fajw ljnegen.","","","",""),
("Knaej sekslĵneg göljtàg seks ljnegen.","","","",""),
("","","","",""),
("","","","",""),
("Ölajn göljkàj wjljnajes kefjegen, jkë göljdogönàlentar kon.","","","",""),
("","","","",""),
("Fülwuj waej kefjegen göljkàj wjljnajafes tjl knaej krjtonur.","","","",""),
("","","","",""),
("Wjlaej fjügul, waej wjljnajafkèfjegen fjügultàg üke wöjlegaf.","Fülwuj göljkàj wjljnajafkèfjegen tjl Kones Dawegaj.","","",""),
("Waej glaeg göljtàg üke gräjug.","","","",""),
("Kjae göljsènsar gräjuges glaegaf för künk göljdesobedecer traej krjton.","Martjn göljkàj knaej gräjuges sjonkèfjeg.","","",""),
("Kon göljklàsj-gräjer waej elkjug tjl klaej laedenug.","","","",""),
("Waej glaegaf göljkàj jkë gräjugafes.","","","",""),
("Waej towlajug jkë göljkàj gräjugafes.","Kjae göljkàj loke gräjugafes wäld tör wän golpe kjae kanskëknàwar!","","",""),
("Waej kojwjàgaj gägulgràjugafer waej laedenaj.","","","",""),
("Öl jkë göljsfàej-göwelar kjaes talwug...","Öl tröljgòwelar wäld öl göljklàsj-lujkar ä Mjgàel för waej ljoneg wjl kjaes autonòwajl.","","",""),
("Öl göljtàg üke göwelajn tjl öles wajugonjàgneg.","","","",""),
("Tör kones göwelsfàejug, kon göljòwadegafer knaej aleged.","","","",""),
("Faer kaj fejfkèfjeg, kon göljklàsj-kaj göwelsfàejuges.","","","",""),
("Knaejkugen, göljkàj tösal tag göwelsfàejugaf...","Rikàrd göljkàj knaej kefjegon j kjae göljtàg göwelsfàejugaf.","","",""),
("—Öl frät tröljknàjkar kon wän futeg! —Fälòj öl göljkàj ükon göwelsfàejugafes, änslaj.","","","",""),
("Waej ölegenes stjlaw jkë göljkàj wjlaej göwelajaf.","","","",""),
("","","","",""),
("Öl jkë göljsfàej-göwelar kjaes talwug...","","","",""),
("Kon jkë göljòwader kjae? Kanskë göljkàj knaej talwuges rëndegaf.","","","",""),
("Ölegen göljklàsj-talwer ölegenes wajug...","","","",""),
("Klaej jkë göljtàg frejeg!","","","",""),
("Följkàj frejeges rawolar kon.","","","",""),
("Traej göljkàj üke frejegafes.","","","",""),
("Konugen göljblĵst wäld göljkàj frejegafes alar traej?","","","",""),
("Kon göljkàj öl knaej wlaejaj?","","","",""),
("Kon göljkàj-wlaejar öl?","Kon wlaejar'al öl wjl klaej.","","",""),
("Kones Dawegaj Walèrja I, Gërtaj tjl Balanlàedenug.","","","",""),
("Fülwuj ölegen göljklàsj-fenser waej Walèrjaes krjtonen.","","","",""),
("Kones Dawegaj Walèrja I, Gërtaj tjl Balanlàedenug.","","","",""),
("Traej göljkàj waej gërtajes öndkĵgegon, jlaek göljàgnar Walèrja I.","","","",""),
("Gërteg tjl Balanlàedenug.","","","",""),
("Ölegen göljwùjk-gërtar kefjeged! Walèrja I göljkàj ölegenes Gërtaj!","","","",""),
("Öl tröljègael ä Stokòlm tröuw öles autonòwajl.","","","",""),
("Öl kanskëwùjk-tag knaej autonòwajles tänsteg!","","","",""),
("Öl göljtàg tö konpjùtern.","","","",""),
("Öl fjügultàg üke konpjùteres fëjregen, fälòj öl tröljgòwelajafar fülwuj.","","","",""),
("Kon göljwùjk-söjw tör öl wjlaej telefön?","","","",""),
("Sästan göljkàj kones telefönes knuwereg?","","","",""),
("Öl göljsfàej-telefönar kon fölwe?","","","",""),
("Waej kälatèlefön göljkàj waej wülasjeg tjlaej anküĵgjaeg 21.","","","",""),
("Öl gägulglàegeter knaej kokolàt!","","","",""),
("","","","",""),
("Öl tröljknàler süjkaenjàgaj tjl kokolàt, j Rikàrd tejgün.","","","",""),
("","","","",""),
("—Öl ündjl trölègael wëroj. —Öl tojsün.","","","",""),
("","","","",""),
("Klaej laedenug göljtàg ükon alentajafes krjtonen.","","","",""),
("","","","",""),
("","","","",""),
("Kon tröljèwjd öl frät trj futegen!","","","",""),
("Kjae följsòjw öl tör waej glaegafes sälk.","","","",""),
("Öles laekug jkë göljwùlasj ësjl süjkaj.","","","",""),
("Öles laedenug göljkàj rädow kaenegafes wäld kones.","","","",""),
("Öles laekug göljkàj tösal wäld kones.","","","",""),
("Tör klaej tänsteg, öles kängul följtòsaler.","","","",""),
("Ölegenes lujkajur följtàg knaej tösaleg tänksakon ä klaej lödewug.","","","",""),
("Awalar tör kaenegaf göljkàj waej wünsal!","","","",""),
("Tör fülw sonteg, klaej göljwùnsaler ësjl j ësjl...","","","",""),
("Waej wünsaleg tjl kjaes dönjleg tröljsènsar kjae knawar.","","","",""),
("Ölajn göljklàsj-lödew wäld alar tör klaej kefjeget.","","","",""),
("Öl tröljàlar knaej lödewug: öl följùnklar öles öndkĵgeg.","","","",""),
("Kon göljklàsj-ökjler öles öndànördnug.","Kjaegen göljklàsj öl knaej grüfug!","","",""),
("Öl göljglàegafar-täg knaej kläsjug tör waej läjrkĵgeg!","","","",""),
("Göljkàj kläsjuges üwlaed öles talwug?","","","",""),
("Öl jkë göljtàg lujklàsjugen tör kon.","","","",""),
("Balanlàedenug göljtàg ukë laedenlujklàsjugen, j öl göljlùjkar klaej.","","","",""),
("Traej laedenug följkrĵtar ësjl laedenlujklàsjuges krjtonen.","","","",""),
("Kon göljwùlasj wlaejaj tör traej?","","","",""),
("Ljwkeg göljkàj öles sëjnteges wülasjeg.","","","",""),
("Ölajn jkë göljfèlder wäld udajkàj wülasjeges ökjler klaej awalaurkĵgeg.","","","",""),
("Kon göljtàg knaej sëjntug tjl klaej köloreg?","Öl göljwùlasj knaej tondräj sëjntugen tjl klaej wülejtug.","","",""),
("Ljwkeg göljkàj öles sëjnteges wülasjeg.","","","",""),
("Klaej anördnug göljkàj sëjnteges tjlaej türajug.","","","",""),
("Kon göljklàsj-sëjnter kones glasugen.","","","",""),
("Öl göljglàs waej sëjntegaf tjl laekugen wjlaej balanlàedenuges laekfèjregur.","","","",""),
("","","","",""),
("Kon tröljèwjd öl frät trj futegen!","","","",""),
("","","","",""),
("Öl jkë följèwlän traej.","Öl tröljèwlän kjae wjl ölugenes öndkĵgeget.","Ölugen göljèwlän konugen ä waej fjndaj tjlaej läjrkĵgeg!","",""),
("Öles ewläneg tröljkàj ljwkeges.","Trölj tjl kones ewläneg, öl göljwùlasj wäld kon udajlùjkar, tjsälk wlaejaj.","Öl tröljtàg knaej enäjeges ewläneg wjl klaej laedenug!","",""),
("Waej awalkèfjeg tröljèwjd ölegen wän awalaurkĵgeg, kjae fjügulkàj üke ewläneges.","","","",""),
("Kon knäler'al waej ësjl bljuneges.","","","",""),
("Öl göljtàg knäluged... öl göljklàsj-ëgael.","","","",""),
("Jkë göljkàj wülasjeges alar traej, göljkàj knäluges.","","","",""),
("Öl göljklàsj-rënder fülwuj kjaes rëndegafen.","","","",""),
("Klaej kefjeg göljtàg rëndeged...","","","",""),
("Öl göljtàg knaej rëndeges rëndfèldug!","","","",""),
("Öles jagneg jkë göljtàg üke rëndegafen.","","","",""),
("Sandor göljkàj knaej rëndegafes sjonkèfjeg, kjae träsjl göljkàj wjl knaejteg färaleges.","","","",""),
("Öl följkàj güwlan öles öndkĵgeg.","","","",""),
("Samànta j öl följljòner güwluj traej swoleg.","","","",""),
("Kon göljklàsj-güwler waej fülwugen faer rjwdar traej laekug.","","","",""),
("Waej güwlug tjl ulerug tör dönjlaj göljsfàej-sënsar knaweg.","","","",""),
("Waej güwlug tjl ulerug tör dönjlaj göljsfàej-sënsar knaweg.","","","",""),
("Kon göljkàj waej sënseg tjl öles rëndegafen.","","","",""),
("Sästan göljkàj waej sënseges dönjlegaf tjl klaej wöjlegaf?","","","",""),
("","","","",""),
("Faer rjwdar wëroj, kon göljklàsj-ëgael ä waej frjweg.","","","",""),
("Kon följwùlasj-wërojkàlaer laekug, ö kon följtàg laekugaf.","","","",""),
("","","","",""),
("Swjarlàedenug göljkàj knaej føjleges laedenug, fjsljeges ä waej ölegenes.","","","",""),
("","","","",""),
("Faer rjwdar wëroj, kon göljklàsj-ëgael ä waej frjweg.","","","",""),
("Antàrtjka göljkàj waej ësjl frjweges laedenugur.","","","",""),
("","","","",""),
("Ölegen göljtàg waej ruwlejneges cultura.","","","",""),
("","","","",""),
("","","","",""),
("Waej jönug tjl klaej beräteg stjlaw jkë tröljkàj-fejferes.","","","",""),
("Trudaj kon tröljfrògael sëlg.","","","",""),
("Kjae göljkàj sëlgeges, tröljklàsj-rjwdar ä waej 10:00.","","","",""),
("","","","",""),
("Tjsälk wlaejaj, kon sëlger'al waej laektàjkleg knaej fjke.","","","",""),
("Trudaj kon tröljfrògael gënw.","","","",""),
("Kjae tröljfrògael ä waej aurug tör gënwaj.","","","",""),
("Ölegen tröljtàg knaej gënwajes knöjsjònug, fjslj tjlaej 6:00.","","","",""),
("Ölegen göljsfàej-gënwar waej aurug?","","","",""),
("","","","",""),
("","","","",""),
("Kjae tröljdàljajafar öl raewenj öl fjügulwàst kjaes wastúrnugen.","","","",""),
("Öles laedenug göljkàj rädow kaenegafes wäld waej kones.","Wäld ölegen följlàeker?","","",""),
("Juljàna göljtàg tjsälk fajw tökèfjegen.","Tjsälk kon göljkàj udaj?","","",""),
("Traej göljkàj Markus, künk tröljràwolar öl.","Künk tröljfjàlaj öles grüfug?","","",""),
("Öl tröljègael ä kjaes öndkĵgeg, laswäld kjae fjügulwùlasj wlaejaj.","Laswäld kon tröljàlar traej ä öl?","","",""),
("Kon söjw'al öl dëjwel kon udajkàj wëroj.","Dëjwel göljkàj waej Krjstòf'es wàjdaj?","","",""),
("Öl följègael ä jlaek göljàw kulkeg.","—Jlaek göljkàj öles laekug? —Wëroj, döjk.","","",""),
("Öl följàwalar bäjgun awalkòjwegen öl udajwùjk!","Bäjgun fjsljkèfjegen kon göljtàg?","Bäjgun ljwkeges öl göljkàj!","",""),
("Öles fjsljkèfjegur, sästan göljkàj üke gërflegones, göljàgnar wëroj.","Sästan göljkàj kones dëwoneges wülejtugen?","","",""),
("","","","",""),
("Kones arwjles wastùrnug göljkàj-dönjlajafares.","","","",""),
("","","","",""),
("Öl göljkàj ökerjles, tjsälk üke kefjegen.","","","",""),
("Öl göljwùjk laekug j fjalaj, tjsälk wlaejaj.","","","",""),
("Kon göljwùjk blutbeg ö rödeg?","","","",""),
("","","","",""),
("Laeker göljkàj knaej dajes üskug.","","","",""),
("Tjsälk wlaejaj, kon üwlaed'al öl kones wàjdaj.","Ljwkeges wàjdaj faer kon!","","",""),
("Udaj öl gölj waej wajdajkèfjeg, göljàlar wäld öl göljùwlaed!","","","",""),
("Öl göljkàj ljwkeges, udaj göljkàj wĵljndaj!","","","",""),
("","","","",""),
("Klaej göljkàj öles sĵwedajes lujkaj.","","","",""),
("Wjl wäld trĵtjödaj ölegen göljkàj?","","","",""),
("Kon göljklàsj-alar wän trĵtjödajes visita ä waej dönjlkèfjeg.","","","",""),
("Sästan göljkàj kones dëwoneges wülejtugen?","","","",""),
("Traej göljkàj öles dëwoneges laejreget!","","","",""),
("Öl göljdèwonar-laeker klaej wäld traej.","","","",""),
("","","","",""),
("Öl göljèwlän wän jgjaeges roglug tjl öles fjsljkèfjegur.","","","",""),
("","","","",""),
("Kon följklàsj-fènser trësjaw ësjl wäld wän fajwĵgjaeg faer kaj dönjlkèfjeg.","","","",""),
("Waej laejreg tjl klaej tjöĵgjaeg göljkàj färaleges!","","","",""),
("Waej kälatèlefön göljkàj waej wülasjeg tjlaej anküĵgjaeg 21.","","","",""),
("Öl göljglàs waej kaenĵgjaeget laswäld klaej göljtàg kaenaj!","","","",""),
("Öl göljwùlasj üke kaenĵgjaegetes kefjdĵlugetur.","","","",""),
("Wjlaej sjonĵgjaeget göljàw üke kaenegaf.","","","",""),
("Waej wjndleg tröljkàlaer waej sjonĵgjaegetes enäjàrgugen för fülwuj waej öndkĵgeg.","","","",""),
("","","","",""),
("Klaej göljkàj knaej wuljgĵgjaegetes bljunwùljgaj.","","","",""),
("","","","",""),
("Waej laedejwùljgaj fjügultàg döjkĵgjaegetes wuljgtèfjajeten.","","","",""),
("—Dëjwel kon göljwùjk klaej? —Fölwe.","","","",""),
("—Dëjwel kon följègael ä waej lujkĵgeg? —Gölj!","","","",""),
("Udaj göljkàj knaej bljuneges daj!","","","",""),
("","","","",""),
("Künk göljkàj kjaes gägules glaekèfjeg?","","","",""),
("","","","",""),
("Frjwslawjlàedenug jkë göljàgnar ësjl, göljkàj knaej fjügules laedenug.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Göljùwlaed wäld kjae göljsfàej-wast waej kängul.","","","",""),
("Waej kängules kefjeguren följklàsj-rënder waej falta tjl jagaj.","","","",""),
("Kon was'al knöj, wäld knaej bljuneges gaelwùlejtug!","","","",""),
("Waej grüfug göljkàj knöjan waej laektajklànördnug.","","","",""),
("","","","",""),
("Waej knöjaj tjlaej kronug tröljàlar fülwuj waej kefjegen ljwkeges.","","","",""),
("—Jlaek göljkàj öles laekug? —Wëroj, döjk.","","","",""),
("Kones lujkaj kanskëklàsj-kaj döjkan waej öles fejfug.","","","",""),
("","","","",""),
("","","","",""),
("—Jlaek göljkàj öles kefjdĵlugetur? —Sëgt tjlaej awalaurkĵgeg.","","","",""),
("—Ölajn ëgael'al sëgtan. —Kon göljkàj kördajafes!","","","",""),
("Öl göljsfàej-sëgtar ä kones öndkĵgeg?","","","",""),
("Kjaes sëgtaj tröljtàjklar fülwuj waej rjnlugen tjlaej aurkĵgeg.","","","",""),
("Waej sëgtajes sjonug tröljlàjter öles rjntèfjajon.","","","",""),
("—Jlaek göljkàj öles lajtrjgëlànördnug? —Wjlaej sëgteg tjl kones autonòwajl.","Tjsälk wlaejaj, kon klën'al öles sëgteg.","","",""),
("Waej bjselùrnugen göljkàj sëgteges ürnugen.","Öl jkë göljwùjk-beräter kon, göljkàj knaej sëgteges rëndegaf.","","",""),
("Kon följfĵndar kones roglug?","Udaj ölajn följfĵndar knaej dësljkĵgeg!","","",""),
("Wjlaej fjndaj tjl kones wastùrnugen, öl tröljòwader waej ljwkeg.","Ölugen göljèwlän konugen ä waej fjndaj tjlaej läjrkĵgeg!","","",""),
("Kjaes fjndajes wastùrnugen tröljbuscar waej lajteg tjlaej wärteges awalkòjweg.","Göljkàj waej fjndajes fiesta, kon göljklàsj-ëgael!","Kones fjsljkèfjegur göljkàj ükon fjndajes.","",""),
("Kon göljsfàej-tensgar waej kjgsègtaj?","Klaej kefjegur gägultènsgar.","","",""),
("Waej tensgaj tjlaej kjgsègtaj göljklàsj-kaj kulkeges.","Udaj göljkàj waej tensgaj tjl öles jagneg.","","",""),
("Öles tensgajes j kaeneges manos göljwùlasj wjljnaj.","Klaej göljkàj waej tensgajes ceremonia tjlaej jgjaeg.","Kon jkë üwlaed'al kjae kjøne kones tänsteg, kjae göljkàj üke tensgajes.","",""),
("Kon göljsfàej-tensgar waej kjgsègtaj?","Waej ulerug göljsfàej-kaj waej kjgsègtaj ä üke rëndegafen.","","",""),
("Öl göljglàs klaej kjglàedejug, klaej göljkàj daentajes.","","","",""),
("Waej kjgtèfjajon göljèlkjer ölegen tjlaej sjonug j waej kojwjàgaj.","","","",""),
("Këngt tjl öles öndkĵgeg!","","","",""),
("Ölegen ëgael'al këngtan, öl göljkàj kaenegafes.","","","",""),
("Öl jkë göljsfàej-këngter tjl froj!","","","",""),
("Waej këngtug tjl klaej laedenug tröljkàj frejegafes.","","","",""),
("","","","",""),
("Konugen, kefjegeten, ëgael'al ä waej këngteg tjlaej öndkĵgeg.","Waej próximo jgjaeg, öl följljòner ä waej këngteg.","","",""),
("Ölegen jkë göljtàg knaej këngteges aurkĵgeg wjl ölegenes öndkĵgeget.","","","",""),
("","","","",""),
("","","","",""),
("Klaej awalkòjweg, öles lündawalkèfjeg j öl följtàg knaej önduges awalàekug.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Klaej öndkĵgeg göljtàg öndkèfjeged.","Öl göljkàj öndkèfjeg wjl Balanlàedenug, fälòj jkë laedenkèfjeg.","","",""),
("Märsèla kängulkàj sjfjöndkèfjeg tjl klaej öndkĵgeget ätej 2024.","Udaj, öl tröljèwlän trj sjfjöndkèfjegen.","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Wäld göljkàj traej laejreges sonido?","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Waej Balanlàedenuges laedenlàejreg göljkàj-talweres 'Knöjan Waej Kaenaj'.","","","",""),
("Öl göljglàer kon.","","","",""),
("Öl tröljwàst kjae j öl tröljfèjr wäld waej glaeg göljkàj.","Kjaegenes awalkòjwegen fjügultàg üke glaeg.","","",""),
("Öl göljwùjk wän glaeges awalkòjweg tör kon...","Öl göljkàj glaeges för kon.","","",""),
("","","","",""),
("Kjaes glaegafes blödùrnug tröljàlar wärteges.","","","",""),
("","","","",""),
("","","","",""),
("Tänksakon för waej roglug, kon göljkàj üke glaegetes!","","","",""),
("Öl frät göljglàegeter kjae.","Öl gägulglàegeter knaej kokolàt!","","",""),
("","","","",""),
("Marjèla göljkàj öles glaekéfjeg.","Öl tröljrògler kjae kjaes roglug tjl glaekèfjeg.","","",""),
("Öl göljkàj wjl knaej glaekèfjegured.","","","",""),
("Kon göljtàg üke fjsljkèfjegen!","","","",""),
("Wjl öles fjsljkèfjegur, knaejfjeged göljtàg knaej autonòwajl.","","","",""),
("Öl göljlùnder-alar traej.","","","",""),
("Kon göljtàg knaej lündug tör öl.","","","",""),
("Kon kanskëlündkèfjer öl?","","","",""),
("Sofĵa göljkàj kones lündkèfjeg?","","","",""),
("—Dëjwel kon följlündkèfjer knaejfjeg? —Öl jkë göljwùjk knaej lündsjonkèfjeg...","","","",""),
("Kjae göljkàj waej lündawalkèfjeg tjl öles awalbèrätegen.","","","",""),
("Ölegen göljklàsj-ökjler ölegenes lündkèfjegur, Marĵa.","","","",""),
("Waej ljwkeg tjl rawolar göljkàj sëjnteges.","","","",""),
("Ljwkeges wàjdaj faer kon!","","","",""),
("Wän grüfug göljsfàej-ljwkar öl üke.","","","",""),
("","","","",""),
("Traej tröljkàj knaej ljwkegafes üskug faer fülwuj ölegen.","Öl göljkàj ljwkegafes för wäld tröljàlar ä Darjus.","","",""),
("","","","",""),
("Kjaes öndkĵgeg göljkàj üke fjslj.","","","",""),
("Kon fjsljar'al ä öl...","","","",""),
("Waej wünsal göljkàj fjsljeges.","Öl göljglàs klaej fjsljeg tör kjae.","","",""),
("Kon knäler'al waej ësjl fjsljeges.","","","",""),
("Ölugen göljkàj ösjwat tjl öles öndkĵgeg.","","","",""),
("Traej ljwkegafes aleg göljkàj ösjwateges.","","","",""),
("Öl göljfèjr knaejteged tjl ösjwateges kjgegen.","","","",""),
("Kon ösjwater'al klaej laekug tjl öl, klaejes ärgug göljkàj bljunegafes!","","","",""),
("Öl följtàg knaej wajug!","","","",""),
("Kon jkë lujkwèjkrjner'al öles tägegen!","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl jkë göljsfàej-klën klaej fëjregur!","","","",""),
("Klaej rëndegaf göljwùlasj ësjl klënug tjl kon.","","","",""),
("Öl göljklàsj-dasker faer sfaej-alar klaej.","","","",""),
("Kjae fjügulkàj knaej grägajafkèfjeg üke daskeges.","—Öl jkë göljsfàej-alar klaej. —Daskeg, awalkèfjeg!","","",""),
("Fërnànd göljkàj frät knaej kefjeget, fälòj kjae göljkàj daskeges.","","","",""),
("Göljkàj daskegon faer alar knaejteg loke wöjlegafes.","","","",""),
("Waej enljeges j daskegones kefjegen tröljònar adelante.","","","",""),
("Kjae göljkàj knaej sjonkèfjeg üke daskegafes.","Göljàw lajtegaf, öl göljtàg daskegaf!","","",""),
("Kon göljkàj knaej daskegafes sjonkèfjeg, kon ëgael'al ä wast kjae!","Waej daskegafes wülejtugen jkë tröljkèngter tjl waej wuljgajon.","","",""),
("Waej daskegafon tröljkaenjàgar kjaes rjnlug.","","","",""),
("Öl tröljdàskegafer dëjwel öl tröljwàst waej blödug.","","","",""),
("","","","",""),
("Öl göljtàg fëjregen kjøne dönjlfèjregur.","","","",""),
("","","","",""),
("Udaj ölegen tröljfènser Fëjregures Feldug tör knaejuj läjrkèfjeg.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Kon lajter'al öl tör kones fëjrsfàejug.","","","",""),
("Kon följkàj üke fëjrsfàejuges kjn kon göljwènslar fülwuj traej fejfugen.","","","",""),
("Kon göljglàs öles laedenug?","","","",""),
("Öl göljtàg glasug för klaej awalkèfjeg.","","","",""),
("Sjntja göljkàj knaej glasuges awalkèfjeg, kjae träsjl göljwùjk-enäjer.","","","",""),
("Öl göljtàg glasugaf för klaej laekug.","","","",""),
("Josef göljkàj knaej glasugafes kefjegon, kjae träsjl gägulsòjw färal!","","","",""),
("Kon göljglàsugafer waej kokolàt? Kon göljkàj kördajafes?","","","",""),
("Waej kojweg göljsènsar öl üke glasugon.","","","",""),
("Klaej öndkĵgegon göljkàj glasugones!","","","",""),
("Kones wastúrnugen göljglàsugoner öl...","","","",""),
("Faer rjwdar ä waej rawolaj, göljklàsj-tag ertjeg.","Kon täg'al ertjeg, waej futegen göljkàj färaleges.","Waej wàjdaj följkàj klaej awalkòjweg, kon täg'al ertjeg!","",""),
("Kjae göljkàj knaej ertjeges kefjeg, fälòj klaej üskug kjae tröljkòrdajafar.","Kon jkë kaj'al ertjeges, kon jkë alentar'al traej!","","",""),
("Öl göljklèn wäld kon göljùwlaed, fälòj öl göljtàg üke ertjegaf.","","","",""),
("Kon göljkàj ertjegafes, kjae följfrògael fölwe.","","","",""),
("Öl göljwùjk traej fjalaj!","","","",""),
("Kones wüjkug för rawolar göljkàj gërflegones!","","","",""),
("Klaej wüjkuges kefjegeten frät göljwùjk-këngter tjlaej läjraurkĵgeg.","","","",""),
("","","","",""),
("Öles wüjkugones blödùrnug göljbuscar kones glaeg.","","","",""),
("Öl göljwùjkugoner-kaj knotkèfjeg!","","","",""),
("","","","",""),
("","","","",""),
("Klaej bljunwùljgaj göljkàj üke kolöreges!","","","",""),
("Wjlaej këngteges kojweg göljkàj knaej fülwegures kolöregaf.","","","",""),
("Waej jagaj göljkàj kolöregafes.","","","",""),
("","","","",""),
("Romelu göljkàj knaej wärtkèfjeg.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Andrej göljkàj knaej wjtkèfjeg.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Kon tröljtĵröl wäld kon fjügulwùjk.","","","",""),
("Waej tjrölug tjl klaej rawolaj göljàlar ölajn üke ljwkeges!","","","",""),
("Öl jkë göljsfàej-lujkar traej!","","","",""),
("Jkë göljkàj wüjkug, göljkàj sfaejug.","","","",""),
("Kjae göljkàj knaej sfaejuges sjonkèfjeg faer klaej tänsteg.","","","",""),
("Öl göljtàg sfaejugaf faer laektàjklar.","Kon jkë göljsfàej-kaj traej? Kon göljkàj sfaejugafes.","","",""),
("Öles rjnlug göljkàj sfaejugafes tjl tjröl traej löwjeg.","","","",""),
("Traej golpe tröljsfàejugafer öl.","","","",""),
("Kon göljsfàej-wast waej kojwgrjnlàjteg?","","","",""),
("Tröljàw knaej wasteg bjtbjn kjaegen.","","","",""),
("Göljkàj frejeges, frät kon göljkàj knaej wasteget.","","","",""),
("Kon wastegetar'al waej laekug, för wlaejaj.","Kjae tröljfrèt-wastegetar waej awalkèfjeg.","","",""),
(".","","","",""),
("Kon göljklàsj-dalënar ätej kon udajsòjw waej lajteg.","Öl göljglàs-dalënar trësjaw waej awalkòjweg.","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Wäld göljkàj klaej futeg?","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Kon jkë göljklàsj-üwlaed öl fejfegen tjl tänksaj!","","","",""),
("Öl tröljèwjd kon waej lujkaj wäld kon fjügulwùlasj, jkë kaj'al tänksajafes!","","","",""),
("Kjae tröljtànksajafar öles roglug faer kjae.","","","",""),
("Karlj, tänksar'al waej kefjegon för kjaes reglug.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Kon j öl kanskësfàej-kaj knaej tökèfjeg tjl ping-pong!","Marjus j öl göljkàj knaej tökèfjeg.","","",""),
("Klaej kefjegetes trjkèfjeg tröljòkjlugafer öles autonòwajl!","Knaej laedenuged tjl Laedejug göljtàg knaej trjkèfjeg.","","",""),
("","","","",""),
("","","","",""),
("Kon göljkàj frät knaej kefjeget, kon jkë göljsfàej-üstal traej.","","","",""),
("Öl ündjl tröljtàg traej üstaleg.","","","",""),
("Waej üstalsfàejug göljkàj enäjeges faer waej kefjegen.","","","",""),
("Öl ündjl följàlar traej.","","","",""),
("Kon träsjl göljkàj ljwkeges!","","","",""),
("Ölegen gägulrĵwdar ä ölegenes laedenug.","","","",""),
("Knaej ","","","",""),
("Kjaes rjnlug fjügulàjter tjsälk waej awalaj...","Waej rjnlug tjlaej towlajug göljkàj kaeneges.","","",""),
("Göljàw loke kaenegaf wäld ölugen gägulrjnljàgar!","","","",""),
("Traej fjügulkàj awalkòjwegen tjl üke rjnljàgaj...","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Waej kefjegen göljkàj knawsfàejuges kajfútaegen.","","","",""),
("Frät waej kojwkèfjegen göljkàj knawsfàejugafes.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl gägulĵneger klaej sjfjeg faer öles göwelaj.","","","",""),
("Kon göljglàs klaej jnegeg tjl öles rjnlug?","","","",""),
("Waej wjteg göljfònler waej grägaj.","","","",""),
("Waej wjteg göljkàj knaej fönleg tjlaej grägaj.","","","",""),
("Waej Balanlàedenug'es laedenfònleg göljtàg wärteg, rödeg j wjteg.","","","",""),
("Öl följdàljar kon öles beräteg.","","","",""),
("Traej göljkàj waej daljaj!","Öl följsòjw kon tör daljaj.","","",""),
("Göljkàj daljajafes wäld kjae tröljègael ä traej laedenug.","Kon jkë üwlaed'al öl ësjl daljajafen!","","",""),
("Kjae tröljdàljajafar öl raewenj öl fjügulwàst kjaes wastúrnugen.","","","",""),
("Kon tröljlàewün traej?","","","",""),
("Wjl traej laewüneg, kon tröljèwjd öl üke tajkleg.","","","",""),
("Waej kefjegones laewünsfàejug göljkàj löwjegafes.","","","",""),
("","","","",""),
("","","","",""),
("Wän saludo faer fülwuj waej laewünkèfjegur!","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Drakula göljkàj knaej blödfjalkèfjeg.","","","",""),
("","","","",""),
("Traej göljkàj waej Aorta blödlĵneg.","","","",""),
("Waej kefjegen göljtàg üke blödlĵneget wjl ölegenes rjnlugen.","","","",""),
("Kamĵla j kon kängulkèfjer konegenes wänes wajug?","Öl göljwùjk-kefjer knaej laekĵgeg.","Öl gägulkèfjer waej futeg.","",""),
("Öl göljkàj knaej lujkajones kefjeg.","Öl fejfug göljkàj knaej kefjeg.","Klaej kefjeg jkë följlàedejar.","",""),
("Ölegenes kefjegur göljkàj üke gräjuges.","Wjl klaej kefjegur tjl knotug, knaej kefjegen jkë göljfèjr-knoter.","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Klaej ulerfjàlaj gägulènljar öles rjnlug!","","","",""),
("Kon jkë kaj'al ljwkegafes, kon göljkàj enljeges.","","","",""),
("Öl jkë göljwùjk-kaj enljegafes!","","","",""),
("Enljegafar gölkàj waej wöjlegafwèjkrjneg tjlaej sjfjeg.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Waej blutbeges blaekaj tröljbljùnegafar kones rjgëlug!","","","",""),
("Kjae gägulùwlaed üke bljunegafèjfegen, wäld färal!","","","",""),
("Öl göljwùlasj wäld kon udajlàjrar öl knuwerfèjregur, för wlaejaj.","Ölajn kängulàjrar kjae trësjaw knaej ësjl jgjaegen.","","",""),
("Klaej tröljkàj waej ësjl frejegafes läjraj tjl waej fülwuj jgjaeg!","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl göljglàsugon-fenser berätfèjregur wjlaej läjrkĵgeg!","Öl alëred tröljfènser waej laejreget.","","",""),
("Ölegen göljwùjk wäld konegenes fenseg wjlaej läjrkĵgeg udajkàj waej tösal.","","","",""),
("Bäjgun fenskèfjegen göljtàg kones kefjegetur?","Öl göljkàj fenskèfjeg tjl lajtrjgëlfèjregur.","","",""),
("Jä! Öl tröljràwolar!","","","",""),
("Göljkàj knaej rawolaj tjl Balanlàedenug!","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl följkàj kojwljonkèfjeg, traej göljkàj-fejfares wjl öles fatjgeg.","Kon tröljtrèwjd üke lujkaj, wäld knaej fatjgeg!","","",""),
("Kon ljoner'al ä Köpenàgen, kon kläsj'al-fatjger.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl göljawalbèräter wäld öl göljsfàej-gaelwar.","","","",""),
("Kjaes gaelwaj göljkàj üke bljuneges.","","","",""),
("Bäjgun öndwùlejtugen kon göljwùjk-täg?","","","",""),
("Öles öndwùlejtug följtàg wülejwàjugen!","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Knaej wuljgajn göljkàj dönjlajes.","","","",""),
("Öl göljwùlasj-dönjlar klaej dönjlajaf.","","","",""),
("Öl göljwùlasj-dönjlar klaej dönjlajaf.","","","",""),
("Kon tröljdònjlajafar öl tör traej fejfegon.","","","",""),
("Waej kefjegon, föraej fetjgeg, göljkàj dönjleges.","Kjae göljkàj knaej sjonkèfjeg gräjuges j dönjleges.","","",""),
("Waej jagneg tröljèwjd öl klaej dönjlegaf...","","","",""),
("Öl göljtàg fëjregen kjøne dönjlfèjregur.","","","",""),
("Öl göljwùjk-kaj knaej dönjlkèfjeg!","","","",""),
("Öles dönjlkèfjeg göljùwlaed wäld öl göljtàg knaej wjrus.","","","",""),
("Waej denokrätĵa jkë göljkàj waej balanug tjlaej kefjegur.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Waej kolweg göljtàg üke jagbĵseleg.","","","",""),
("","","","",""),
("Wjl klaej laedenug, ölegen göljtàg wäld ölegen fjügulwùjk.","Klaej göljkàj waej laedenug tjl Jonatan j Marĵa.","","",""),
("Balanlàedenug göljtàg knjw laedenugeten.","Wjl klaej laedenuget öl göljtàg öles öndkĵgeg.","","",""),
("","","","",""),
("","","","",""),
("Wjl öles laedenkèfjegur, waej kefjegen göljfjàlar ukë ulerug.","","","",""),
("Göljàw üke fjke laedenugafkèfjegen.","","","",""),
("Lionel Messi göljkàj knaej öles laedenwenkèfjeg.","","","",""),
("Fërdjnand j öl följàgnar güwluj wjl traej swolug.","Kones laekaurkĵgeg göljkàj waej swolug tjlaej laekug.","","",""),
("Öl göljwùjk-jagnar wjl knaej swoluget wäld klaej udajkàj kaeneges ö udajtàg knaej jaglĵneg.","","","",""),
("Öl jkë göljfèjr waej swolugon tjl Swjarlàedenug.","Öl göljglàsugafer waej swolugonen, göljtàg üke kulkegaf!","","",""),
("Öl följkàj knaej swolkèfjeg fülwuj öles jagneg.","","","",""),
("","","","",""),
("","","","",""),
("Göljàw fjke frükeg bjtbjn Älbert j Martjn.","","","",""),
("","","","",""),
("Kjae göljkàj kones wenkèfjeg, kon göljklàsj-kaj respetuoso.","Konegen glaer'al waej wenkèfjeg.","","",""),
("'Enljkèfjeg' göljkàj wenkfèjfeges tjl 'kefjegon'.","","","",""),
("Öl jkë göljglàs klaej kjgeg...","Ölugen sëgtar'al ä traej kjgeg!","","",""),
("","","","",""),
("Klaej dönjlaj göljkòrdar öl.","Kon kördar'al dëjwel kon göljsòjw!","","",""),
("Klaej göljkàj knaej kördajes kefjegon.","Kon göljklàsj-knäler tör kördaj.","","",""),
("—Ölajn ëgael'al sëgtan. —Konajn göljtàg kördajaf!","Göljkàj kördajafes üwlaed traej.","","",""),
("Kjae gägulkòrdajafar sjng kjaes wajug tröljknàwar.","Kon tröljkòrdajafar dëjwel kon tröljàlar traej.","","",""),
("Enljegafar gölkàj waej wöjlegafwèjkrjneg tjlaej sjfjeg.","Wjl klaej sjfjeg, jkë göljkàj wöjlegaf.","","",""),
("Udaj, ölegen följfènser waej berätfèjregures wenksĵfjeg bjtbjn klaej tö alegen.","","","",""),
("Göljkàj knaej fülwegures ljwkeg kaj wenksĵfjeges tjl waej Gërtaj.","","","",""),
("Konugen jkë göljwùlasj-fostar, göljkàj enäj.","","","",""),
("Öl göljlàeker üke, fälòj öl göljkàj fosteges.","","","",""),
("Waej fostegon göljsfàej-bëndjlar tör knaejuj rëndegaf tjl dönjleg.","Kones tänslùjkaj göljkàj fostegones.","","",""),
("Öl göljkàj fostegafes, göljklàsj-kälaer ësjl.","","","",""),
("Ölegen jkë göljwùjk-fostegafar ësjl!","","","",""),
("Kjae träsjl tröljkàj fostegafones, kjae göljtàg 140 kjlo.","Waej fostegafon tjl kulkegafen tröljdònjlajafar kjae.","","",""),
("Ölajn följwĵster för wäld kon tröljàlar!","","","",""),
("Kjae tröljdònjlajafar öl, gölj kjae följèwlän öles wjsteg!","Öl tröljràwolajafar, fälòj öl göljwùjk waej wjsteg!","","",""),
("Kon tröljòwader öles kälatèlefön?","Ölegenes laedenug tröljòwader waej kjgegen tjlaej enemigo.","","",""),
("Waej öwadeg tjl öles sjfjànördnug tröljkàj waej tösal tjlaej jgjaeg.","","","",""),
("Stjlaw göljwòjlegafar öl waej öwadegaf tjl öles lujkaj.","","","",""),
("Kon jkë öwadegafer'al öles fjalaj, tjsälk wlaejaj.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Kon göljwùjk knaej fjke tjl jagaj?","","","",""),
("","","","",""),
("Göljkàj kaenegafes, fälòj öl göljkàj jageges.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Baltjk göljkàj knaej jagajur.","","","",""),
("Atlàntjk göljkàj knaej jagajuron.","","","",""),
("Klaej jaglĵneg göljkàj kaeneges.","Waej aleg fjügultàg knaej jaglĵneg tajkleges.","","",""),
("","","","",""),
("Öl göljwàelar kon, kon frogael'al froj tjsälk wlaejaj!","","","",""),
("Waej waeleg göljkàj knaej fönleg tjl glaeg.","","","",""),
("Wändaj, ölajn följklàsj-kjltar waej wülejtugen.","","","",""),
("Trësjaw waej kjlteg, knaej wülejtugen göljkùlkegafar.","","","",""),
("Öl göljfjàler üke kjltaj wjlaej knöjsjònug.","","","",""),
("Öl göljfjàler üke kjltaj wjlaej knöjsjònug.","","","",""),
("Öl gägulgrùfer, kon göljwùjk?","","","",""),
("Tör knaej grüfug, öl jkë göljsfàej-awalar!","","","",""),
("Kon göljwùlasj wän kjlo tjl grüfwùljgajet.","","","",""),
("Waej süjkjltgrùfug göljkàj öles fjalaj wjlaej sjonkòjweg.","","","",""),
("Öl göljwùjk waej tënkaj tör kjltaj.","","","",""),
("Kon tröljòkjler öles sjfjànördnug!","","","",""),
("Klaej konpjùter göljwùlasj knaej ökjlug.","","","",""),
("","","","",""),
("","","","",""),
("Alfrëd tröljbèräter ölugen knaej glaeges beräteg.","","","",""),
("Ölajn jkë göljblĵst kjaes beräteg.","'Ansel j Gretel' göljkàj knaej beräteg faer kefjegeten.","","",""),
("Öl göljtàg knaej beräteget kjøne öles ljoneg ä Saanjlàedenug.","Kon göljwùjk-laewün knaej beräteget tjl tö rüsslàedenuges kefjegen?","Konegen tröljlàewün waej beräteget kjøne Ana?","",""),
("Ölajn göljkàj wjl knaej awalbèräteg?","","","",""),
("Öl tröljtàg knaej färalawalbèräteg, klaej tröljkàj üke bljunegafes.","Kjaes fjsljkèfjegur tröljòwadegafer waej öndkĵgeg, klaej göljkàj knaej färalawalbèräteg.","","",""),
("Öl göljwùjk-awalbèräter bljuneges futegen.","","","",""),
("Klaej konpjùter göljwùlasj knaej ökjlug.","","","",""),
("Öl göljglàs traej kones wastùrnugen.","","","",""),
("Öles arwjles laewünùrnug göljwòjlegafar.","","","",""),
("Klaej laekug tröljtàjklar öles golunùrnug.","","","",""),
("Öl göljtàg knaej kones öwelug.","Ölajn jkë tröljràwolar tör wän öwelug!","","",""),
("Kones öwelugur göljkàj wärteges j bljuneges.","","","",""),
("","","","",""),
("Öl göljglàs kjaes gjldòwelugur.","","","",""),
("Öl göljglàs kjaes wärtòwelugur.","","","",""),
("Frederik göljtàg tötjö jgjaegen, j kjae älered göljtàg kaenòwelugen.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl jkë göljsfàej-wünelar bulöw waej jagaj!","","","",""),
("Wjlaej wünelaj, üke kajfútaegen göljbĵseler kjaegenes bjselùrnugen.","","","",""),
("Kon jkë sëgwùnelar'al waej wjwjtaj!","","","",""),
("Wjlaej sëgwùnelaj, waej kefjegen göljsfàej-ënskj kjaegenes wjkolaj.","","","",""),
("","","","",""),
("Öl göljwùjk-bejnar ölugenes kefjdĵlugeturen.","","","",""),
("Kones öndkĵgeget göljwùlasj ësjl bejnaj.","","","",""),
("Öl göljglàegafar-tag bejnajaf wjl öles rjnlug!","","","",""),
("Tjsälk wlaejaj, kon jkë bejnajafar'al waej aurkĵgeg.","","","",""),
("Kjae tröljdògöner öl wlaejar ä kjaes wajug.","","","",""),
("Kon bejnar'al kones awalaurkĵgeg. Göljkàj knaej dogönug.","","","",""),
("Öl göljkàj kones madre, kon dogönàlentar'al öl!","","","",""),
("Waej dogönàlentaj göljkàj knaej kläsjug wjlaej ejército.","","","",""),
("Öles kängules öndwùlejtug följkàj üke dogönàlentajes tör öl.","","","",""),
("Fülwuj göljkàj dogönalentfkèfjegen tjl Kones Dawegaj.","","","",""),
("Traej tröljkàj frät waej bëndjleg tjlaej wöjleg.","Waej kojwkèfjegen tröljknàler waej bëndjleg tjl Laedejug.","","",""),
("Kon göljwùjk-bëndjlar klaej tör öl?","","","",""),
("Klaej göljkàj waej fändjleg tjl kjaes rëndegafen.","","","",""),
("Öles glaegon för kon göljkàj fändjlegafes, öles lündkèfjeg.","Wjl knuwerfèjregur, göljkàj frejegafes klën waej fändjlegaf.","","",""),
("Kon göljklàsj-fändjlar klaej fejfug trölj tjlaej awalknòjar.","Öl göljsfàej-fàndjlar knöjan kon...?","","",""),
("Öl gägulfèjfar waej fejfàndjleg tjl öles fejfug.","","","",""),
("Öl jkë göljwènslar waej fejfbèndjlegen.","","","",""),
("Tröljkàj knaej enäj wenslaj!","","","",""),
("Öl jkë göljwènslar waej fejfbèndjlegen.","","","",""),
("Kjae tröljsöjwènslar ä fülwuj waej fjsljkèfjegur.","","","",""),
("Öl tröljglàs waej söjwènslaj tjlaej Gërtaj!","","","",""),
("Kon jöner'al ölegenes söjwaj, tjsälk wlaejaj.","","","",""),
("Waej jönug tjl klaej beräteg stjlaw jkë tröljkàj-fejferes.","","","",""),
("","","","",""),
("Kon jkë jönugafer'al...","","","",""),
("—Tjsälk kon göljkàj udaj? —Enäj, j kon?","","","",""),
("Jkë göljàw üke enäjeg wjl Laedejug, fälòj kon göljtàg üke.","Klaej grüfug göljkàj üke enäjeges!","","",""),
("Kon jkë dönjlajafar'al kjae, kon kläsj'al-enäjer.","","","",""),
("Kon jkë göljklàsj-jagwĵkolar, traej göljkàj färal.","","","",""),
("Kjae göljkàj knaej färaleges sjonkèfjeg.","Klaej laekug göljkàj färaleges faer kones dönjleg.","","",""),
("Waej wejkrjnkèfjegen göljfàraler faer jagnar.","","","",""),
("Kon jkë färalùjkar'al wjl knaejteg loke wöjlegafes.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl göljklàsj-ëgael ä waej jagaurkĵgeg!","","","",""),
("Öl göljklàsj-ëgael ä waej jagaurkĵgeg!","","","",""),
("Kjaes frogaelaj tröljàlar öl ljwkeges.","","","",""),
("Kjae tröljfrògael tör üke laekugen.","","","",""),
("Knaej fjalajen göljtàg ulerug.","Traej awàlajet göljkàj knaej ulerug faer kon.","","",""),
("Öl göljwùjk-fjaler ulerfjàlajen.","","","",""),
("","","","",""),
("Kon följlàeker traej?","Waej wjndleg tröljlàeker kones fejfegen.","","",""),
("","","","",""),
("Tjsälk wlaejaj, kon sëlger'al waej laektàjkleg knaej fjke.","","","",""),
("Öl följlùjkar ölajnes laekug.","Öl göljwùjk waej tösal laekug tjlaej laekĵgeg, tjsälk wlaejaj.","Glaeg göljkàj laekug faer waej blödùrnug.","",""),
("Öl följlùjkar laekug.","","","",""),
("","","","",""),
("","","","",""),
("Kon göljglàs waej wjwjtgòlunajes wänlàekugen?","","","",""),
("Öl göljsfàej-wänlàeker güwlan kon wändaj?","","","",""),
("Wäld ölugen följlàeker wjlaej sjonlàekug?","","","",""),
("Wäld kon göljwùjk-sjonlàeker?","","","",""),
("Udaj öl jkë följtàg knaej grüflàekug.","","","",""),
("Öl följgrüflàeker üke süjkaj udaj.","","","",""),
("Öl följlaektàjklar waej awalàekug, öles glaeg.","","","",""),
("Konegen ëgael'al ä awalàeker ä knaej laekĵgeg, öl göljlùjkar!","","","",""),
("Öl göljklàsj-käjker öles öwelugur.","","","",""),
("Kones käjkug gägulblòder üke.","","","",""),
("Fülwuj göljkàj enäj, göljkàj frät knaej käjkuget.","","","",""),
("Öl jkë göljsfàej-laeker ütan laekäjkfùtaj!","","","",""),
("Konugen göljwùlasj-dësljar knaejuj autonòwajl.","","","",""),
("Klaej dësljaj tröljkàj waej tösal tjlaej daj.","","","",""),
("Kon tröljlùjkar fülwuj ölegenes lujkaj wjlaej dësljkĵgeg!","","","",""),
("Öl göljwùjk-ünklar klaej kefjdĵlugetur laswäld klaej göljkàj enljegafes.","","","",""),
("Öl tröljtĵröl üke lujkaj tör waej ünklaj tjl öles autonòwajl.","","","",""),
("Stjlaw kjae jkë tröljlùjkar öl öles tänslùjkaj.","Kon tröljlùjkar fülwuj ölegenes lujkaj wjlaej dësljkĵgeg!","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl göljkàj knaej lujkegafes kefjeg.","","","",""),
("Göljkàj üke ljwkegafes wast loke lujkegafon.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl följtàg knaej wajug!","Kamĵla j kon kängulkèfjer konegenes wänes wajug?","Frät fajw sontegen? Kon gölkàj knaej wajug!","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Waej awalknòjar tröljlàjtegafer waej aurkjgeg.","Kjaes fejfegen tröljlàjtegafer öles blödùrnug.","","",""),
("Öl göljglàs-wast waej kojwgrjnlàjteg ä waej awalkòjweg!","","","",""),
("Göljàw üke kojwlajtsònteg wjlaej kojweg.","","","",""),
("Waej tajkleg tröljlàjter waej awalkòjweg.","Kon göljsfàej-lajter, tjsälk wlaejaj?","Kjaes rjnlug fjügulàjter tjsälk waej sjonug.","Kon lajter'al öl tör kones fëjrsfàejug.",""),
("Ölugen göljklàsj-alar klaej löwj!","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Ölegen alar'al klaej dünej...","","","",""),
("Kjae göljkàj üke dünejeges faer laeker.","","","",""),
("Kon dünejar'al kones dalënaj, tjsälk wlaejaj.","","","",""),
("Waej kälaeg tjl kjaes öwelugur tröljbljùnar öl.","","","",""),
("Kon kälaer'al, göljkàj kaeneges!","","","",""),
("Öl jkë göljsfàej-kaj kälaegafes, öl göljwùlasj-dalënar.","","","",""),
("Tjsälk wlaejaj, kon kälaegafer'al kones öndwùlejtug.","","","",""),
("Kon göljwùjk-wast knaej kälarĵgëlug tör öl?","","","",""),
("Waej kälarjgëlànördnug göljwùlasj electricidad.","","","",""),
("Ölegen egael'al ä waej kälarjgëlkĵgeg! Kon göljwùjk?","","","",""),
("Öl jkë följknàler kälarjgëlfèjregur.","","","",""),
("Kjn kon göljfrògael ä öles öndkĵgeget, kon göljsfàej-frojkàlaer knaej fjalaj?","Traej aleg följfrojkàlaer ükon rëndegafen.","","",""),
("","","","",""),
("","","","",""),
("Konstànsa tröljbèräter wäld kjae göljkàj wajsjònuges!","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Waej awalaj göljkàj üke lajteges.","Wjl öles awalbèrätegen, kon göljkàj waej awalaj!","","",""),
("Öles glaeg, kon göljkàj öles awàlajet.","","","",""),
("Üke awalkèfjegen göljglàs kjaejnes awàlajon.","Öl göljglàs waej awalkèfjegen awàlajones.","","",""),
("Waej kojweg göljkàj lajteges udaj.","","","",""),
("","","","",""),
("","","","",""),
("Udaj följkojwjàgar.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Kon göljkàj waej awalkèfjeg ësjl bljuneges tjlaej türajug.","Waej Sistema Solär göljtàg ëjwt türajugen.","","",""),
("Waej awalaj göljkàj knaej türajuget tjl Laedejug.","Rasmus göljkàj knaej türajuget tjl Fabjòla, göljkàj fülwuj waej daj fjslj tjl kjae.","","",""),
("Öl följtùrajer klaej glaeg faer ölegen.","","","",""),
("Wjl kones öndug göljàw üke krjten.","","","",""),
("Fülw kefjegur göljtàg knaej wenkegafes krjtur faer waej jagneg.","","","",""),
("Balanlàedenug göljtàg gräjuges krjtonen.","","","",""),
("Traej göljkàj-alentajafares bäsel ölegenes krjtonur.","","","",""),
("Ölegen göljklàsj-krjtar klaej tänsteg.","Balanlaèdenug tröljkrĵtar waej pena de muerte.","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Traej kefjegeten göljwùjk-kaj kojwljonkèfjegen.","","","",""),
("","","","",""),
("Wändaj följsjonknòjar ä 7:00.","","","",""),
("Kon göljglàs-wast waej knöjsjònug?","Klaej fejfeg göljkàj üke knöjsjònuges.","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Klaej jaglĵneg göljkàj kaeneges.","","","",""),
("Klaej jaglĵneg göljkàj kaeneges.","","","",""),
("Öl göljwùlasj-kaenegafar öl!","","","",""),
("Kon göljèwjd öl tö kaenjàgajn faer öles fjalaj?","Waej kaenjàgaj wjlaej kaenlàedejug göljkàj üke kaeneges.","","",""),
("Öl följkaenjàgar waej laeker.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Alek göljkàj tjl Swjarlàedenug.","","","",""),
("Mjrjam göljkàj saanjlàedenuges.","","","",""),
("Føjljonlàedenug göljkàj knaej kaeneges làedenug.","","","",""),
("Rüsslàedenug göljkàj knaej kaeneges làedenug.","","","",""),
("Frjwslawjlàedenug jkë göljàgnar ësjl, göljkàj knaej fjügules laedenug.","","","",""),
("Öl tröljwàjer wjl Balanlàedenug.","","","",""),
("Klaej laedenug göljklàsj-tënter waej knuwerer tjl öndkèfjegen.","","","",""),
("","","","",""),
("Udaj, ölegen följknuwertènter tjö tör fjr.","","","",""),
("Klaej knuwergùwlug göljkàj frejeges tjl klën.","","","",""),
("Tjsälk öl göljknuwertènter klaej?","","","",""),
("Waej knuwertènteg tjl tö för fjr göljkàj ejwt.","","","",""),
("Waej knuweregen göljkàj fändjlegafes.","","","",""),
("Ätej jlaek kon göljsfàej-knuwerer?","Kjae tröljknùwerer öles rëndegafen wjl waej fëjregur.","","",""),
("","","","",""),
("Wjlaej gägul, kefjeged göljtàg knaej knuwerfùtaj.","","","",""),
("Kon jkë göwelajafar'al-ewjd kjae öles laekfùtajn.","","","",""),
("Öl göljglàs waej sëjntegaf tjl laekugen tjlaej balanlàedenuges laekfèjregur.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Ölegenes kefjegur göljkàj-alares wjl wänkèfjegen.","","","",""),
("","","","",""),
("Froj göljàw tö kefjegen.","","","",""),
("Tatjàna j öl göljkàj tänswenkèfjegen, laswäld tökan gägultànstar wjl klaej fejfkĵgeg.","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl göljwùlasj knaej tondräj sëjntugen tjl klaej wülejtug.","","","",""),
("Laedejug göljtàg üke frasäjen tjl jgjaegen wjl kajeg.","","","",""),
("Öl göljklàsj-ëgael ä waej jagaurkĵgeg!","","","",""),
("Öl följègael äej daweglàedejug.","","","",""),
("Kjae tröljknàwar ägj öl.","","","",""),
("Ölegen fjügulglaewĵkolar bulöw waej kojweg.","","","",""),
("Ölegen fjüguljàgnar tör kulkeg.","","","",""),
("Ölugen gägulkàj-ljoner grej waej gräjuges wjndleg!","","","",""),
("Waej kulkeg tjl waej awalkòjweg.","","","",""),
("Traej göljkàj waej lujkeges tjlaej öndugur.","","","",""),
("Öl göljsfàej-wast kon sjng froj.","","","",""),
("Öl göljglàs-dalënar trësjaw waej awalkòjweg.","","","",""),
("Wjl waej fejfkĵgeg, öl tröljlùjkar kones fejfug.","","","",""),
("Öl tröljfjàler jagaj wjlaej laekĵgeg.","","","",""),
("Waej ljneg bjtbjn glaeg j glaegaf göljkàj üke gräjugafes.","","","",""),
("Kon jkë wast'al töwar waej tajkleg.","","","",""),
("Öl göljglàer kon ätej waej kojweg.","","","",""),
("Öl tröljègael ä Stokòlm tröuw öles autonòwajl.","","","",""),
("Kon göljèwjd öl tö kaenjàgajn faer öles fjalaj?","","","",""),
("Göljkàj för froj.","","","",""),
(".","","","",""),
("Bäsel kjaegen, udaj göljàlar kaeneg.","","","",""),
("Kon jkë göljsfàej-jagnar ütan glaeg.","","","",""),
("Konegen tröljlàewün waej beräteget kjøne Ana?","","","",""),
("Kon jkë kaj'al bëjand öl!","","","",""),
("Öl göljkàj Ramĵro.","Kjae göljglàer öl.","","",""),
("Kon göljglàs öl?","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("","","","",""),
("Öl göljwùjk knaejuj süjkaenjàgaj, tjsälk wlaejaj.","","","",""),
("Öl göljwùjk knaejteg süjkgòlunajes.","","","",""),
("Göljkàj knaejteged wëroj.","","","",""),
("Knaejfjeg göljtàg knaej blaekfejfùtaj?","","","",""),
("Knaejfjeged göljglàs klaej laekug!","","","",""),
("Klaej fejfeg göljkàj üke knöjsjònuges.","Öl göljglàs waej kaenĵgjaeget laswäld klaej göljtàg kaenaj!","","",""),
("","","","",""),
("—Kon göljwùjk knaej fjke tjl grüfug? —Ëgwej!","","","",""),
("—Öl älered tröljòkjler kones laektajklànördnug. —Tänksakon!","","","",""),
("Ölajn göljsfàej-laewün waej wülejtugen swejaug. Jäk!","","","",""),
("Waej tajseg göljkàj waej fändjleges futeg wäld kon göljòwadegafer.","","","",""),
("Waej fändjleges följkàj wänes.","","","",""),
("Kon kläsj'al-tajser waej grägajafkèfjegen faer waej grägajafet.","","","",""),
("Waej knuweregen göljkàj tajseges, ölegen följsfàej-dësljar waej öndkĵgeg!","","","",""),
("Kjaes rjnlug tröljdòjker tör tajsegaf.","","","",""),
("Waej awalkèfjegen göljtàg wän fajlaj.","","","",""),
("Waej sjonkèfjegen göljtàg wän glajsug.","","","",""),
("Göljàw fjke fajlajes dönjlegafen.","","","",""),
("Klaej göljfrùker tjsälk knaej glasjuges fönleg.","","","",""),
("Kjae göljwènkegetar tjsälk kon!","","","",""),
("Klaej wüljgaj göljkàj knjfajeges. Knaejfjeged tröljwùljgar klaej.","Kon jkë ëselar'al klaej, klaej göljkàj knaej knjfajeges wülejtug.","Tröljkàj knaej knjfajeges aleg, kjae jkë tröljfèlder.","",""),
("Öl göljsfàej-ëselar kones öwelugur?","","","",""),
("Kones ëseleg göljkàj dönjleges!","","","",""),
("Waej tajkleg jkë tröljdònjlajafar öl tör traej ëseleget.","Wäld göljfònler kones ëseleget?","","",""),
("Kjaes rjnlug tröljèselegetar waej jagaj.","Waej sjonkèfjeg tröljèselegetar waej awalkèfjeg raewenj kjaeug fjügulwàst kjaejes wastùrnugen.","","",""),
("Traej göljkàj knaej dönjleges laekug.","","","",""),
("Knaej wüljgajen göljkàj dönjlajes.","","","",""),
("Traej öndkĵgeg göljkàj wenkegetes ä waej öles.","","","",""),
("Öl jkë göljglàs ölegenes wenkegetaf.","","","",""),
("Klaej kolöreg göljkàj wenkegetafes ä waej öles.","","","",""),
("Frjwgorjölàedenug j Føjlgorjölàedenug göljkàj wenkegafes.","","","",""),
("Göljkàj knaej wöjleges awalkòjweg...","","","",""),
("Waej knaweg tjl knaej fjsljkèfjeg göljkàj knaejteg wöjlegafes.","","","",""),
("Waej tajkleg göljkàj üke dönjlajafes.","","","",""),
("Waej kefjegeten göljfènser tör fresteg.","","","",""),
("Kjaeuges fejfegen tröljfrèster öl.","","","",""),
("Kjaeug göljtàg öles sjfjànördnug.","","","",""),
("Kjaej göljkàj waej tägkèfjeg tjl öles blödùrnug.","","","",""),
("Kjaej göljkàj waej tägkèfjeg tjl öles blödùrnug.","Krug. Tjlkojwson göljkàj waej tägkèfjeg tjl klaej wjljnajafkèfjeg.","","","");

SELECT * FROM `dictionary`.`example`;